### ISSUE TITLE
Autoremove does not work

### ISSUE THREAD

**Issue by jwbrase** [bit-team/backintime#1040] opened 2019-11-01 20:46 UTC
I have BIT set up to autoremove if less than 10 GiB is available, but snapshots are not automatically removed, even though there is no space on my backup disk. I can't even manually delete snapshots from within backintime: they grey out until I open the settings dialog or exit and relaunch, but they're still there and intact afterwards. I have to manually remove the snapshot directories using system tools.

Do the "smart remove" options utterly bar a snapshot from being removed, or do they just give hints for what to remove first?

**Comment by CaninoDev** [comment] 2019-11-02 00:01
I am having the same problem and have the following settings: ![Screenshot_20191101_195729](https://user-images.githubusercontent.com/16412897/68062633-e0bf8600-fce1-11e9-9679-2259861f8ea3.png) Incidentally, when the backup media is at capacity, I receive the following error when attempting to change any of the settings: 
![Screenshot_20191101_200016](https://user-images.githubusercontent.com/16412897/68062675-3ac04b80-fce2-11e9-8464-e52388bcc83e.png)


Running Manjaro (5.3.7-2-Manjaro), BackInTime v1.2.1-1

**Comment by jwbrase** [comment] 2019-11-02 23:32
I'm not getting the "can't write" message. However, I did discover something that probably indicates this is a non-bug: Even a delete with rm failed, and the errors rm displayed indicated filesystem corruption. fsck is currently chugging away on the drive and has found errors.

So for my part, BIT was unable to remove certain files because nothing else could either (short of fsck), and the issue can be considered closed for my part. I'll leave it open for a while, though, in case CaninoDev is running into an actual issue in BIT

CaninoDev, could you run a fsck on your backup drive and report the results? If you're also running into filesystem corruption, I'll close the issue.

**Comment by CaninoDev** [comment] 2019-11-03 17:49
I just did a `fsck /dev/md0` and it showed up clean. But then again, I manually ran `backintime --smart-remove` recently and the RAID drives now have sufficient space so was able to continue backups.

**Comment by emtiu** [comment] 2022-09-09 11:05
Hi @coquizen, thanks for the report. Did you ever encounter this problem again, or has smartremove worked for you since you once triggered a manual remove?

**Comment by emtiu** [comment] 2022-10-22 16:56
Closing, because the reporter is not responding and we cannot reproduce. Possible duplicate of #824.

**Closed by emtiu** 2022-10-22 16:56 UTC
Labels: Feedback
