### ISSUE TITLE
No error given if server does not have rsync installed

### ISSUE THREAD

**Issue by kbogert** [bit-team/backintime#754] opened 2017-04-30 15:55 UTC
If the server, for whatever reason, does not have rsync installed, backintime will simply state that there has been no changes since the last snapshot and will not record an error, no give any indication that something is wrong other than the time to decide nothing has changed is ludicrously short (almost instant).

In my case, the server containing the snapshot was rebuilt and I forgot to reinstall rsync.  The error given when manually running the rsync command found in the information log on the shell is:

> bash: rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: remote command not found (code 127) at io.c(226) [sender=3.1.1]

**Comment by Germar** [comment] 2017-05-01 19:00
BiT does check the remote server if it is able to create snapshots when you press OK in Settings. But these tests are to heavy to run every time a new snapshot is executed.

I'm working on analyzing rsync return code. Currently the return code is not used.

Duplicate of #489

**Closed by Germar** 2017-05-01 19:00 UTC
Labels: duplicate
