### ISSUE TITLE
BiT systray eats CPU and RAM

### ISSUE THREAD

**Issue by black-silence** [bit-team/backintime#496] opened 2015-11-15 18:24 UTC
I can often see a process from "qt4systrayicon.py" that takes one CPU core and ~4G of RAM. I don't see a systray icon though. 

I'm sure the process is started with my weekly scheduled backup. I used the gui to check the backup log, some changed files usually, backup looks ok.

Desktop is xfce, I'm not sure if the qt systray works there. Can I disable the systray? Should I debug which code eats the memory?

**Comment by Germar** [comment] 2015-11-15 22:43
Which BIT version do you use? And which distribution release?

When it eats all memory are you still able to open the context menu?

There is no function to disable the systrayicon but you can rename/remove `/usr/share/backintime/plugins/qt4plugin.py` to temporary disable it.

**Comment by black-silence** [comment] 2015-11-16 07:50
Version 1.1.8 on arch linux. I haven't tried to open the gui in that situation, will do when it's backup time again. 
I have 8G memory so the 4G is not the maximum, I guess the gui should work when it's a separate process.

**Comment by black-silence** [comment] 2015-11-16 17:43
Added some print calls. The script "hangs" at line 80

    self.progressBar.render(self.pixmap, sourceRegion = ...
The print after that line never prints.

**Comment by Germar** [comment] 2015-11-16 21:11
I couldn't reproduce the high CPU/memory usage on Kubuntu 15.10 but the progress bar doesn't show up either. That line should render a progress bar on top of the systray icon. It's a little hack I used to show progress in systray.

**Comment by emtiu** [comment] 2022-09-22 19:36
Closing as obsolete, since backintime has migrated to qt5, and the problem likely isn't readily reproducable anymore.

**Closed by emtiu** 2022-09-22 19:36 UTC
Labels: systray
