### ISSUE TITLE
app.py crashed with SIGSEGV in sip_api_get_adress()

### ISSUE THREAD

**Issue by omexlu** [bit-team/backintime#1203] opened 2021-12-05 14:51 UTC
Hello,

Have been using backintime since today, works quite well, scheduled a backup today as root for 3pm (cronjob created by the GUI), this runs through (all files are included in the backup).

However, I get the following error message in the Ubuntu window:
`app.py crashed with SIGSEGV in sip_api_get_adress()`

Installed is version: 1.2.1 (from the Ubuntu store).

Thanks in advance.

**Comment by aryoda** [comment] 2022-09-09 00:33
Could you please add the full traceback/stacktrace here to be able to narrow down the problem?

And: Which Ubuntu and python version are you using?

THX :-)

PS: Could possibly be related to #1095 if Ubuntu is > 20.04 or python 3.9++. I suspect this because the sip* function problem was also reported there but without a stacktrace it is hard to say...

**Comment by emtiu** [comment] 2022-09-09 08:47
Yes, I suspect this is a duplicate of #1095, but maybe @omexlu has more information for us :)

**Comment by emtiu** [comment] 2022-10-22 16:52
Closing, since the reporter is not responding and we can't reproduce.

**Closed by emtiu** 2022-10-22 16:52 UTC
Labels: Feedback
