### ISSUE TITLE
f,g,h, i and j versions for ubuntu have disapeared from PPA stable

### ISSUE THREAD

**Issue by vaurat** [bit-team/backintime#1154] opened 2021-04-20 13:49 UTC
hello, got a 404 from my groovy 20.10.
http://ppa.launchpad.net/bit-team/stable/ubuntu/dists/ does not contain it. anymore ?

**Comment by buhtzz** [comment] 2022-09-25 12:14
@vaurat There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

What are f, g, h, i and j?

Tag: Feedback, Distro-Specific

**Comment by emtiu** [comment] 2022-09-25 17:21
Closing as duplicate of #1136.

**Closed by emtiu** 2022-09-25 17:21 UTC
