### ISSUE TITLE
When snapshot will be too large, backintime tries anyway, fails silently, leaves disk-filling "new_snapshot" behind, & subsequent backups fail silently even if not too large

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#386] opened 2015-10-11 17:17 UTC
I occasionally make the mistake of leaving in a backed-up directory a large temporary file/directory that cannot fit in the remaining space on the backup media.

I would have thought that backintime would see that it won't succeed before it even starts.  It could then send an email or desktop notification to alert me.

Instead, backintime fills up the backup medium with a new_snapshot directory, then silently terminates without finishing the backup, alerting me of the trouble, or even removing this huge directory.  The GUI will even state that the backup succeeded in its status line if it is running, though the backup will, unsurprisingly, not appear in the snapshot list.

I don't even get an email or notification the next day when backintime fails to take another shapshot.  It will just keep silently failing to back up, even if the large temporary files have since been removed, until someone deletes the "new_snapshot" directory.

This is obviously terribly broken.

I am, of course, running backintime 0.9.26-4 from Debian Squeeze (stable).

---

Imported from Launchpad using lp2gh.
- date created: 2011-09-28T16:39:17Z
- owner: thomas-reportbug
- the launchpad url was https://bugs.launchpad.net/bugs/861569

**Comment by emtiu** [comment] 2022-09-24 22:20
Closing as duplicate of #374.

**Closed by emtiu** 2022-09-24 22:20 UTC
Labels: Bug
