### ISSUE TITLE
Restore directory mtime

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#246] opened 2015-10-11 16:41 UTC
Can you change the behavior of the rsync call to honor the original DTS on files/dirs when a user chooses to restore a target from a backup set?

---

Imported from Launchpad using lp2gh.
- date created: 2013-11-16T13:01:11Z
- owner: graysky
- the launchpad url was https://bugs.launchpad.net/bugs/1251845

**Comment by Germar** [comment] 2015-10-11 20:16
(by germar)
I'm not sure if I understood your request. DTS is daylight saving time, correct?
AFAIK this doesn't matter as date/times are always stored in UTC Unix time (seconds from 01.01.1970). They will be transformed by tzdata as soon they are displayed with respect on your locale and DST.

**Comment by Germar** [comment] 2015-10-11 20:16
(by graysky)
No, DTS = date time stamp... you are thinking about DST which is the other :p

**Comment by Germar** [comment] 2015-10-11 20:16
(by germar)
Oh, stupid me :D
So you're talking about restoring atime and ctime, correct? mtime will be restored because rsync uses mtime and size to check if a file has changed.

For atime you would need to patch rsync with patches/atimes.diff in https://rsync.samba.org/ftp/rsync/src/rsync-patches-3.0.9.tar.gz. But atime will change for files in snapshots, too. So you can't make sure atime is the same after restoring.
AFAIK there is no way to modify ctime as non-root.

**Comment by Germar** [comment] 2015-10-11 20:16
(by graysky)
Hmm... could be be that the action of a restore does the following: check to see if target exists on file system, if no use archived DTS.  If yes, restore file using code as-is.

Is that possible?

**Comment by Germar** [comment] 2015-10-11 20:16
(by germar)
We could enhance 'Save/Restore permissions' to back up and restore atime into 'fileinfo.bz2'. But only for all files because only rsync knows which file had changed (okay, we could extract that from rsyncs output but that is quite fuzzy). Anyways, rsync will always mess around atime in source path when it transfer changed files.

Just for my own interest: why is it important to restore atime?

**Comment by Germar** [comment] 2015-10-11 20:16
(by graysky)
Sounds good.  To answer your question, I use the DTS on the dir to know when the last time a particular directory has been updated.  For example, I recently had a need to restore /home/me/PKGBUILDs which contains 50+ directories.  When I did the full restore, the DTS on all the dirs was all the same which is wrong.

**Comment by Germar** [comment] 2015-10-11 20:17
(by graysky)
...for example, if I restore from a tar backup, the DTS on /home/me/PKGBUILDs will be preserved; restoring from BIT should be the same.

Thanks!

**Comment by Germar** [comment] 2015-10-11 20:17
(by germar)
Ahh, okay. I think now I get it.
This is not about atime. This is just mtime which WILL be restored by rsync. But that only works for files. Dirs mtime is messed up because as soon as rsync writes a file inside a dir your filesystem will renew mtime for the dir. rsync would need to come back to the parent dir and reset mtime again. I'm not sure if there is such a function.

**Comment by SirHackselot** [comment] 2021-01-06 01:46
This could be done by hand (or by backintime) after the restore with a command like
`find $dir -type d -exec  touch --reference="$backupdir/{}" "{}" \;`

**Comment by emtiu** [comment] 2022-09-26 21:19
Closing as duplicate of #1007.

**Closed by emtiu** 2022-09-26 21:19 UTC
Labels: Feature
