### ISSUE TITLE
Tray icon missing/empty/not shown correctly

### ISSUE THREAD

**Issue by emtiu** [bit-team/backintime#1306] opened 2022-09-22 21:50 UTC
This is an attempt to combine/summarize multiple reports of the systray (notification area) icon being missing/empty/malformed, with a total of 9 users reporting as being affected, namely:
- 1 affected user: #849 
- 5 affected users: #1098
- 1 affected user: #1152
- 3 affected users: #1236 (related: #1240)

### backintime versions affected
Although the code relating to the systray icon has changed significantly since 1.1.0 (see below: **"Past progress bar over systray feature (1.1.0 until 1.1.24)"**), there is at least one report of version 1.3.2 being affected: https://github.com/bit-team/backintime/issues/1098#issuecomment-1255735848

### Distributions affected (where known)
- 6 rolling-release/DIY distros, thus difficult to reproduce:
  - 4x Arch (all in #1098)
  - 1x Gentoo (https://github.com/bit-team/backintime/issues/1236#issue-1174215325)
  - 1x openSUSE Tumbleweed (#1152)
- 3 non-rolling releases:
  - 1x Ubuntu 21.10 (https://github.com/bit-team/backintime/issues/1236#issuecomment-1079060370)
  - 1x Elementary OS Loki (now obsolete, #849)
  - 1x Fedora 35 (Soon obsolete, https://github.com/bit-team/backintime/issues/1236#issuecomment-1091120110 / #1240)

### Graphics/Desktop Environments (where known)
- 2 KDE/Plasma 5 on X11 (#1152 and https://github.com/bit-team/backintime/issues/1098#issuecomment-1255735848)
- 1 Cinnamon on X11 (https://github.com/bit-team/backintime/issues/1098#issuecomment-1256830467)
- 1 Budgie (https://github.com/bit-team/backintime/issues/1098#issuecomment-797061901)
- 1 no desktop environment (https://github.com/bit-team/backintime/issues/1098#issuecomment-811530185)
- 1 Elementary OS "Pantheon"/GNOME (#849)
- 1 XFCE 4 (#1236)
- 1 GNOME 40.4 on Ubuntu 21.10 (https://github.com/bit-team/backintime/issues/1236#issuecomment-1079060370)

### user account for backintime job
- 4x root user (https://github.com/bit-team/backintime/issues/1098#issue-661971312 and https://github.com/bit-team/backintime/issues/1098#issuecomment-857316902 and #1240 and https://github.com/bit-team/backintime/issues/1098#issuecomment-1256830467)
  - **significantly**, in one case, backintime is also missing an icon in the task bar when open for the root user: https://github.com/bit-team/backintime/issues/1098#issuecomment-1256830467** – this seems to rule out an issue associated with the past progress bar over systray feature (see below).

### Useful logs
From #1098, 2 users reporting identical messages (both for root jobs):
```
Jul 20 10:35:01 j python[80624]: backintime (root/1): INFO: Take a new snapshot. Profile: 1 Main profile
Jul 20 10:35:01 j python[80624]: backintime (root/1): INFO: Call rsync to take the snapshot
Jul 20 10:35:01 j python[80629]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Jul 20 10:35:01 j python[80629]: QPainter::begin: Paint device returned engine == 0, type: 2
Jul 20 10:35:01 j python[80629]: QWidget::render: Cannot render with an inactive painter
Jul 20 10:35:01 j python[80629]: QSystemTrayIcon::setVisible: No Icon set
Jul 20 10:35:08 j python[80624]: backintime (root/1): INFO: Save config file
Jul 20 10:35:08 j python[80624]: backintime (root/1): INFO: Save permissions
```

### Past progress bar over systray feature (1.1.0 until 1.1.24)
Version 1.1.0 introduced a progress bar displayed over the systray icon:
https://github.com/bit-team/backintime/blob/ab24e105e618b8b1f5d779e0d4713a6296ca46d3/CHANGES#L313

… but it caused trouble, as @Germar commented: https://github.com/bit-team/backintime/issues/849#issuecomment-356097028
> That's a problem on how I solved the progress bar in the tray icon. It will load a different icon as soon as it prints the progress bar. Should be fixed as soon as we have a proper BiT icon which will have a progress indicator by it self. I already have an idea for that...

… as well as here: https://github.com/bit-team/backintime/issues/496#issuecomment-157172054
> I couldn't reproduce the high CPU/memory usage on Kubuntu 15.10 but the progress bar doesn't show up either. That line should render a progress bar on top of the systray icon. It's a little hack I used to show progress in systray.

In the end, it was removed in 1.2.0:
https://github.com/bit-team/backintime/blob/ab24e105e618b8b1f5d779e0d4713a6296ca46d3/CHANGES#L41

## Current best guess: backintime cannot find icon from system theme to use
Backintime has no icon of its own (#215), so it uses the "save" icon (`Icon=document-save` in its .desktop file on Kubuntu) from any given Desktop Environment/theme as its main icon, both in menus and in the system tray. The same strategy is employed to set backintime's icon in Qt:
https://github.com/bit-team/backintime/blob/ab24e105e618b8b1f5d779e0d4713a6296ca46d3/qt/icon.py#L25

It might be the case that such an icon cannot be found in certains circumstances (in order of decreasing likelihood):
- the root user doesn't have the right paths set (https://github.com/bit-team/backintime/issues/1236#issuecomment-1091120110)
- an unusual combination of theme/DE is active,
- there is no DE installed (https://github.com/bit-team/backintime/issues/1098#issuecomment-811530185)

**Comment by aryoda** [comment] 2022-10-18 19:41
Perhaps my PR #1336 for issue #1244 is fixing this issue too (even though it is only meant for Wayland, not X11).

When I find the time I will look into this master issue too...

**Comment by aryoda** [comment] 2022-11-16 22:59
Looking into all the issues I also think that a missing "standard" icon is the root cause and it is my strong suspicion that we should use `QIcon::fromTheme("edit-undo", QIcon(":/undo.png"));` (https://doc.qt.io/qt-5/qicon.html#fromTheme-1)
instead of the currently implemented

https://github.com/bit-team/backintime/blob/e36d8dc85dd0181a38e174efc6d1f774be99ff4e/qt/icon.py#L24-L25

to enable a default logo for the tray icon when the current theme does not contain the BiT logo icon.

Instead of the `undo.png` we could provide a self-painted logo (artists - this is your chance now ;-)

Also we should check and log if the desktop environment does support a tray icon at all and write at least a info message if not.

Here are some commands to run some diagnostics in the current environment that works from the command line.

Since the BiT starter scripts to manipulate some env vars I would suggest to add (append) these lines into the `/usr/share/backintime/qt/backintime-qt` script file to support tests as normal (unprivileged) and root user:

```
python3 -c "from PyQt5.QtWidgets import QSystemTrayIcon,QApplication; app = QApplication(['']); print('isSystemTrayAvailable: ' + str(QSystemTrayIcon.isSystemTrayAvailable()))"
python3 -c "from PyQt5.QtGui import QIcon; from PyQt5.QtWidgets import QApplication; app = QApplication(['']); print('Theme name: ' + QIcon.themeName())"
python3 -c "from PyQt5.QtGui import QIcon; from PyQt5.QtWidgets import QApplication; app = QApplication(['']); print('has theme icon <document-save>: ' + str(QIcon.hasThemeIcon('document-save')))"
```

The output on my Ubuntu 20.04 with Gnome3 and X11 as user is:

```
isSystemTrayAvailable: True
Theme name: Yaru
has theme icon <document-save>: True
```

On Manjaro KDE Plasma with Wayland I get (as user):

```
isSystemTrayAvailable: True
Theme name: breeze
has theme icon <document-save>: True
```

**Comment by aryoda** [comment] 2022-11-16 23:31
I also think that the existing theme fallback algorithm does not fully work:

https://github.com/bit-team/backintime/blob/e36d8dc85dd0181a38e174efc6d1f774be99ff4e/qt/icon.py#L19-L22

On a non-Gnome non-Ubuntu distro the `gnome` and `ubuntu-mono-dark` themes will not deliver `NULL` as  `QIcon`
and if `oxygen` will find an icon (this theme seems to be quite common even on KDE) the loop "break"s **before** setting the `oxygen` theme...

I guess the intention of this algorithm was to check the actual theme first and then all themes from the list
but it performs an "all-except-last" theme activation.

**Comment by emtiu** [comment] 2022-11-17 08:25
So, if I understand correctly, this would try to load  `document-save` as backintime's icon, but fallback to `undo` if that's not found? Sounds like a very good solution to me!

But we'd need to check if we can reasonably expect `undo` to exist in situations where `document-save` doesn't. The best test would probably be to reproduce the abovementioned Issues, and/or ask affected users to test new code.

**Comment by aryoda** [comment] 2022-11-17 09:20
und is just an example, there are better Qt5 built-in icons (incl. a disk).

Yes, I want to reproduce the prob first in my VM to understand the cause (no guessed fixing)

Am 17. November 2022 09:26:10 MEZ schrieb "Michael Büker" ***@***.***>:

**Comment by aryoda** [comment] 2022-11-20 20:09
I kindly ask all affected users who still do not see the tray icon during taking a backup to run the appropriate diagnostics script in terminal and show the output here to help me to identify all possible reasons. THX a lot!

If you are not sure if the tray icon is working you can force a backup of a configured profile via

```
backintime --profile-id 1 --debug backup-job  
```

For BiT running as user (not as root):

```
python3 -c "
from PyQt5.QtGui import QIcon;
from PyQt5.QtWidgets import QSystemTrayIcon,QApplication,QStyleFactory;
import os
qapp = QApplication(['']);
env_var = 'XDG_SESSION_TYPE'; print(f'Display Server={os.environ.get(env_var)}');
print((f'QT QPA platform plugin: {qapp.platformName()}'));
env_var = 'QT_QPA_PLATFORMTHEME'; print(f'QT_QPA_PLATFORMTHEME={os.environ.get(env_var)}');
env_var = 'QT_STYLE_OVERRIDE'; print(f'QT_QPA_PLATFORMTHEME={os.environ.get(env_var)}');
print(f'QT active style: {qapp.style().objectName()}');
print(f'QT fallback style: {QIcon.fallbackThemeName()}');
print(f'QT supported styles: {QStyleFactory.keys()}');
print(f'themeSearchPaths: {str(QIcon.themeSearchPaths())}');
print(f'fallbackSearchPaths: {str(QIcon.fallbackSearchPaths())}');
print(f'Is SystemTray available: {str(QSystemTrayIcon.isSystemTrayAvailable())}');"
```

For BiT running as root with X11 as display server:

```
pkexec env DISPLAY=$DISPLAY XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR XAUTHORITY=$XAUTHORITY python3 -c "
from PyQt5.QtGui import QIcon;
from PyQt5.QtWidgets import QSystemTrayIcon,QApplication,QStyleFactory;
import os
qapp = QApplication(['']);
env_var = 'XDG_SESSION_TYPE'; print(f'Display Server={os.environ.get(env_var)}');
print((f'QT QPA platform plugin: {qapp.platformName()}'));
env_var = 'QT_QPA_PLATFORMTHEME'; print(f'QT_QPA_PLATFORMTHEME={os.environ.get(env_var)}');
env_var = 'QT_STYLE_OVERRIDE'; print(f'QT_QPA_PLATFORMTHEME={os.environ.get(env_var)}');
print(f'QT active style: {qapp.style().objectName()}');
print(f'QT fallback style: {QIcon.fallbackThemeName()}');
print(f'QT supported styles: {QStyleFactory.keys()}');
print(f'themeSearchPaths: {str(QIcon.themeSearchPaths())}');
print(f'fallbackSearchPaths: {str(QIcon.fallbackSearchPaths())}');
print(f'Is SystemTray available: {str(QSystemTrayIcon.isSystemTrayAvailable())}');"
```

For BiT running as root with Wayland as display server:

```
pkexec env QT_QPA_PLATFORM=wayland-egl XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR XAUTHORITY=$XAUTHORITY python3 -c "
from PyQt5.QtGui import QIcon;
from PyQt5.QtWidgets import QSystemTrayIcon,QApplication,QStyleFactory;
import os
qapp = QApplication(['']);
env_var = 'XDG_SESSION_TYPE'; print(f'Display Server={os.environ.get(env_var)}');
print((f'QT QPA platform plugin: {qapp.platformName()}'));
env_var = 'QT_QPA_PLATFORMTHEME'; print(f'QT_QPA_PLATFORMTHEME={os.environ.get(env_var)}');
env_var = 'QT_STYLE_OVERRIDE'; print(f'QT_QPA_PLATFORMTHEME={os.environ.get(env_var)}');
print(f'QT active style: {qapp.style().objectName()}');
print(f'QT fallback style: {QIcon.fallbackThemeName()}');
print(f'QT supported styles: {QStyleFactory.keys()}');
print(f'themeSearchPaths: {str(QIcon.themeSearchPaths())}');
print(f'fallbackSearchPaths: {str(QIcon.fallbackSearchPaths())}');
print(f'Is SystemTray available: {str(QSystemTrayIcon.isSystemTrayAvailable())}');"
```

The output does look similar to this (with other values):

```
Display Server=x11
QT QPA platform plugin: xcb
QT_QPA_PLATFORMTHEME=qt5ct
QT_QPA_PLATFORMTHEME=None
QT active style: qt5ct-style
QT fallback style: 
QT supported styles: ['Breeze', 'cleanlooks', 'gtk2', 'cde', 'motif', 'plastique', 'qt5ct-style', 'Windows', 'Fusion']
themeSearchPaths: ['/home/user/.local/share/icons', '/usr/local/share/icons', '/usr/share/icons', '/var/lib/snapd/desktop/icons', ':/icons']
fallbackSearchPaths: []
Is SystemTray available: True
```

**Comment by aryoda** [comment] 2023-02-03 23:53
I have created a new separate bug (see # 1404) for this message (that is shown sometimes when the systray icon does not show-up)  since it also occurs in other contexts (e. g. unit tests):

```
Jul 20 10:35:01 j python[80629]: QPainter::begin: Paint device returned engine == 0, type: 2
Jul 20 10:35:01 j python[80629]: QWidget::render: Cannot render with an inactive painter
```

**Comment by aryoda** [comment] 2023-07-17 21:27
I have fixed all known issues (hopefully) with my PR #1480, re-testing and feed-back welcome!

**Comment by aryoda** [comment] 2023-09-04 19:51
I am closing this now as fixed.

Please open a new issue in case of any problems (to get rid of this and the other related issues that are old and have along history of discussions)...

**Closed by aryoda** 2023-09-04 19:51 UTC
Labels: High, Qt, Meta, Distro-Specific, Discussion, Bug
