### ISSUE TITLE
Permanent systray tray icon

### ISSUE THREAD

**Issue by noyannus** [bit-team/backintime#1645] opened 2024-02-19 00:03 UTC
Currently the tray icon only appears when a backup is running, and its popup give information about that backup only. 

It would be nice to have permanent icon (or an option when to display it) that, when clicked, displays info about the status of all profiles: last backup and its success status, or simply a list of the most recent 5..10 backups with an icon to indicate status. Also it could show a badge whenever a backup failed, as an early warning if something starts going wrong.

**Comment by aryoda** [comment] 2024-02-19 00:10
Thanks a lot for your feature request. I think this (at least partly) a duplicate of #1370 and the idea of indicating errors more prominently is intriguing.

Since #1592 requires an overhaul of the systray icon logic (root cannot show a systray icon for another user) it is "overdue" to implement this (after our Qt6 migration). It is on my TODO list.

**Comment by buhtz** [comment] 2024-02-19 08:19
Yes, thanks for this report.

I would like to throw another Issue into the pit. #1018 is a feature request of my own (from 2019). It is about given a status report about all existing snapshot profiles: Timestamp of last run, with or without errors, etc. And all this in a machine readable format (e.g. JSON).

I wasn't sure where to use this information but would like to start with a simple JSON output and then see what is coming. I a persistent BIT systray icon is a good place to use such kind of information.

I would keep this Issue open and treat it as a feature request about having a "status of all profiles" accessible via the systray icon.

**Comment by buhtz** [comment] 2024-12-28 12:06
Closing this for now as duplicate of #1370.

**Closed as completed by buhtz** 2024-12-28 12:06 UTC
Labels: High, Discussion, Notifications, HELP-WANTED
