### ISSUE TITLE
Automated BiT setup for CLI

### ISSUE THREAD

**Issue by sbancal** [bit-team/backintime#582] opened 2016-05-31 13:23 UTC
In the doc, we see "You only need to specify 3 things :"
* where to save snapshots
* what folders to backup
* backup frequency (manual, every hour, every day, every month)

Which is the case if we use GUIs.

But for the servers (which we only configure through command line and files or even automate their setup in a script), this is more complicated.
The way I started to work is to configure the file `/root/.config/backintime/config` as an imitation of what a GUI does. This makes something like >70 lines of parameters which most of them I don't care.
Then I run `backintime check-config` to validate everything.

Is there a CLI way to configure from scratch BiT?
Or what would be the easiest / cleanest way to automate it's configuration?

Thanks!

**Comment by Germar** [comment] 2016-05-31 21:26
Nope, there is no CLI yet. A long time ago (long before I joined working on BIT) there was a branch providing a minimal CLI. But that one was never merged (I've no idea why) and is completely outdated by now. It would need to a complete rebuild from scratch.

You could create a new config on your local machine and copy it over to the headless server.

This is a duplicate of #254

**Closed by Germar** 2016-05-31 21:26 UTC
Labels: duplicate
