### ISSUE TITLE
Udev failure starting a backup

### ISSUE THREAD

**Issue by mhmulati** [bit-team/backintime#886] opened 2018-04-25 01:36 UTC
Hello guys

I've just started using BiT and it's been great. However, it isn't properly working when USB storage drive is connected (udev). When I click to make a snapshot, it works like a charm.

The error message in the system log:
24.04.2018 22:01:35:446	session-c2.scope	backintime (mhmulati/1): ERROR: Failed to write flock file /home/mhmulati/.local/share/backintime/worker.lock.flock: [30] Read-only file system

I'm using Kubuntu 17.10.

Any idea how to solve this?

Cheers
Mauro Henrique Mulati

**Comment by buhtzz** [comment] 2022-09-25 08:32
@mhmulati There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback, UDEV

**Comment by emtiu** [comment] 2022-10-22 16:27
Closing as outdated, reporter not responding, cannot reproduce.

**Closed by emtiu** 2022-10-22 16:27 UTC
