### ISSUE TITLE
Upon Restore, receive thousands of "FAILED" errors. 

### ISSUE THREAD

**Issue by TriggerDingus** [bit-team/backintime#1195] opened 2021-11-15 16:10 UTC
I am doing a test Restore of an entire directory structure from and external NTFS to my internal EXT4/LUKS. It restores all the files, however, at the end of my Back In TIme restore log are thousands of these errors. Any insight?

chgrp /home/bob/Desktop/TEST-RESTORE/TheDataHoard/Pictures/Australia Feb 2015/._2015-02-26 11.54.26.jpg 0 : FAILED
chgrp /home/bob/Desktop/TEST-RESTORE/TheDataHoard/Pictures/Australia Feb 2015/IMG_1099.JPG 0 : FAILED
chgrp /home/bob/Desktop/TEST-RESTORE/TheDataHoard/Pictures/Australia Feb 2015/._2015-03-01 03.55.33.jpg 0 : FAILED
chgrp /home/bob/Desktop/TEST-RESTORE/TheDataHoard/Pictures/Australia Feb 2015/IMG_1238.JPG 0 : FAILED
chgrp /home/bob/Desktop/TEST-RESTORE/TheDataHoard/Pictures/Australia Feb 2015/IMG_1214.JPG 0 : FAILED
chgrp /home/bob/Desktop/TEST-RESTORE/TheDataHoard/Pictures/Australia Feb 2015/IMG_1161.JPG 0 : FAILED
chgrp /home/bob/Desktop/TEST-RESTORE/TheDataHoard/Pictures/Australia Feb 2015/IMG_1054.JPG 0 : FAILED

**Comment by daveTheOldCoder** [comment] 2021-11-21 15:56
Looks like a permissions issue.

The user under which BackInTime is running doesn't have the privileges to use chgrp, or the user-group that BackInTime recorded for the backed-up files doesn't exist on the target file system.

The user/group for the backed-up files is recorded in fileinfo.bz2 in each snapshot. You could try using chgrp manually on one of the files and see if it works, or if it results in an error.

**Comment by buhtzz** [comment] 2022-09-25 12:00
@TriggerDingus There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

**Comment by emtiu** [comment] 2022-10-22 11:35
Closing as outdated. The cause of the issue is most likely particular to the reporter's system as stated by @daveTheOldCoder above. Feel free to re-open if there's more relevant information.

**Closed by emtiu** 2022-10-22 11:35 UTC
