### ISSUE TITLE
Integrate ZFS snapshots into BackInTime

### ISSUE THREAD

**Issue by hcw70** [bit-team/backintime#760] opened 2017-05-12 13:32 UTC
I am using ZFS very happyly since some time on my ubuntu box.
I am also a big fan of BackInTime due to its delta storage efficiency and its simplicity to do backups via a ssh tunnel.

What even would be greater is if there would be a possibility to let backInTime let take a ZFS snapshot at begin of the backup, back up the snapshot, and then destroy the snapshot at the end of the backup.

This would be a great way to backup a consistent set from a filesystem.

However, for this to work, some path mangling must be done, since i.e. /home/hcw/data will become 

`/home/.zfs/snapshot/<snapshot name>/hcw/data`

I am using ZFS very happyly since some time on my ubuntu box.
I am also a big fan of BackInTime due to its delta storage efficiency and its simplicity to do backups via a ssh tunnel.

What even would be greater is if there would be a possibility to let backInTime let take a ZFS snapshot at begin of the backup, back up the snapshot, and then destroy the snapshot at the end of the backup.

This would be a great way to backup a consistent set from a filesystem.

However, for this to work, some path mangling must be done, since i.e. 

`/home/hcw/data`

will become 

`/home/.zfs/snapshot/<snapshot name>/hcw/data` 

during backup, but should end up as `/home/hcw/data` in the backup folder on the remote host.

What do you think?

**Comment by Germar** [comment] 2017-05-20 17:43
Creating a ZFS snapshot mounting and unmounting it can all be done with a [user-callback](https://github.com/bit-team/user-callback) script.

Integrating something like this would be possible of course. But I'm sorry to say that I'm not interested in doing so. PR's are welcome ;)

**Comment by buhtzz** [comment] 2022-09-26 08:03
@hcw70 @mxa There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

**Comment by emtiu** [comment] 2022-10-09 22:57
Closing as duplicate of #1016.

**Comment by emtiu** [comment] 2022-10-09 23:00
I agree that this is out-of-scope. It's a nice idea, and I'm a fan of ZFS myself, but the best approach here is probably a custom user-callback script.

**Closed by emtiu** 2022-10-09 23:00 UTC
