### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by kerner1000** [bit-team/backintime#488] opened 2015-11-08 14:03 UTC
```
CRON[6880]: (root) CMD (/usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job >/dev/null 2>&1)
backintime (root/1): INFO: Lock
backintime (root/1): WARNING: Inhibit Suspend failed.
backintime (root/1): ERROR: Failed to unlock SSH private key /root/.ssh/[id]_rsa: 
Traceback (most recent call last):
#012  File "/usr/share/backintime/common/askpass.py", line 43, in <module>
#012    print(pw.get_password(None, profile_id, mode))
#012  File "/usr/share/backintime/common/password.py", line 375, in get_password
#012    password = self._get_password_from_pw_cache(service_name, user_name)
#012  File "/usr/share/backintime/common/password.py", line 412, in _get_password_from_pw_cache
#012    self.fifo.write('get_pw:%s/%s' %(service_name, user_name), timeout = 5)
#012  File "/usr/share/backintime/common/password_ipc.py", line 78, in write
#012    with open(self.fifo, 'w') as fifo:#012  File "/usr/share/backintime/common/tools.py", line 936, in handler
#012    raise Timeout()
#012exceptions.Timeout
```

**Comment by kerner1000** [comment] 2015-11-08 14:06
After a retry using cron instead of anacron (dont know if this makes a difference)
<code>
kernel: [ 4814.897145] python3[5694]: segfault at 40 ip 00007f844201ce84 sp 00007ffeed64b058 error 4 in libQtCore.so.4.8.6[7f8441e8e000+2d8000]
backintime-qt4 (root/1): ERROR: Failed to unlock SSH private key /root/.ssh/[id]_rsa: Traceback (most recent call last):#012  File "/usr/share/backintime/common/askpass.py", line 43, in <module>#012    print(pw.get_password(None, profile_id, mode))#012  File "/usr/share/backintime/common/password.py", line 375, in get_password#012    password = self._get_password_from_pw_cache(service_name, user_name)#012  File "/usr/share/backintime/common/password.py", line 412, in _get_password_from_pw_cache#012    self.fifo.write('get_pw:%s/%s' %(service_name, user_name), timeout = 5)#012  File "/usr/share/backintime/common/password_ipc.py", line 78, in write#012    with open(self.fifo, 'w') as fifo:#012  File "/usr/share/backintime/common/tools.py", line 936, in handler#012    raise Timeout()#012exceptions.Timeout
backintime-qt4 (root/1): ERROR: /root/.local/share/backintime/mnt/1_7186/backintime/[my-hostname]/root/1 does not exist
backintime-qt4 (root/1): INFO: Mountpoint /root/.local/share/backintime/mnt/C322B638/mountpoint is already mounted
</code>

**Comment by Germar** [comment] 2015-11-08 16:26
Please stop `pw-cache` once. Looks like it broken
```
backintime --pw-cache stop
```

**Comment by Germar** [comment] 2015-11-08 16:35
Hmm. Just after typing I run into exactly the same in one Ubuntu 15.10 Test VM. Just stopping pw-cache didn't help. But stopping and starting again did it.
```
backintime --pw-cache stop
backintime --pw-cache start
```
I'll have a look...

**Comment by kerner1000** [comment] 2015-11-08 17:18
Thanks Germar, that fixed the problem!
BTW: <code>Save Password to Keyring</code> is grayed out. How can I use it?

**Comment by Germar** [comment] 2015-11-08 17:42
root doesn't have a keyring. Only normal users who uses a DE (Gnome/KDE/Unity/whatever). So you can't use it, sorry.

**Comment by kerner1000** [comment] 2015-11-08 17:44
Yes, of course. Thanks!

**Comment by Germar** [comment] 2015-11-22 20:27
This is a duplicate of #468

**Closed by Germar** 2015-11-22 20:27 UTC
Labels: duplicate
