### ISSUE TITLE
encrypted ssh backup: can't save profile

### ISSUE THREAD

**Issue by johann-cm** [bit-team/backintime#1150] opened 2021-03-31 19:39 UTC
**situation:** I'm trying to set up an encrypted ssh backup via ssh. As I'm trying to save the profile, I get asked if I want to copy the public ssh key to the server. (I've already copied the public ssh key to the target server)

**problem:** both options (yes or no) do nothing after selecting them.

**expected behavoir:** backintime should give *some* sort of feedback, i.e. an error message explaining what went wrong

My system is:
- backintime version 1.2.1
- arch linux

**Comment by davipatti** [comment] 2021-08-25 14:48
I have a similar issue, but in (unencrypted) SSH mode.

I enter details for the profile and click OK. 

A box appears saying "Would you like to copy your public SSH key to the remote host to enable password-less login?"

Nothing happens clicking by either option, and the profile is not saved.

- Pop!_OS 20.10
- BIT 1.3.1

**Comment by buhtzz** [comment] 2022-09-25 12:15
@davipatti and @JayCeM There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback, Bug, External

**Comment by JayCeM** [comment] 2022-09-26 10:17
- I did not find a solution
- Personally, I have moved on from Back In Time to a duplicity based solution
- I still think the issue should be resolved, if it still exists. This issue is the core reason I abandoned Back In Time
- If the issue is resolved, I would consider switching back to Back In Time because of the easy user interface

**Comment by davipatti** [comment] 2022-09-26 13:17
I did not find a solution and also started using a different program.

**Comment by buhtz** [comment] 2024-06-04 14:34
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,
Christian

**Closed by buhtz** 2024-06-04 14:34 UTC
Labels: Medium, Bug, HELP-WANTED
