### ISSUE TITLE
BiT should not check all destionation paths

### ISSUE THREAD

**Issue by rugk** [bit-team/backintime#630] opened 2016-09-08 15:48 UTC
## Situation
I have an internal backup (same drive) and an external backup (external drive, which is not always connected) setup.

## Problem
Now when I want to change the settings for the internal backup I can do so, but when clicking on OK BiT shows me an error that the path to my external disk is not available.
And yes: That's true the external disk is not mounted, but I also have not changed any setting of the external backup. This means now I cannot change any setting of my internal backup without mounting my external backup drive first, which is of course silly.

So you should maybe only check for path issues if the user actually *modified* the path.

**Comment by Germar** [comment] 2016-09-08 20:04
Did you enable the `When drive get connected (udev)` schedule in external profile and use BiT version < 1.1.4? If so, please update to latest version as this is already fixed.

**Comment by rugk** [comment] 2016-09-08 20:45
1) Yes.
2) BiT 1.0.3, so yes.

BTW why would a higher version than 1.1.4 be bad?? Or do you used them incorrectly.
If so no, I won't update my BiT installation as it is the one from the Debian repos. You might just try to reproduce the issue with the latest version and if you say it is already fixed, then this is of course nice!

**Comment by Germar** [comment] 2016-09-08 22:07
It does matter with versions below 1.1.4

This is a duplicate of bug #134 which has been fixed in 1.1.4 so please upgrade to a more recent version.

**Closed by Germar** 2016-09-08 22:07 UTC
Labels: duplicate
