### ISSUE TITLE
Back in time works if I download the tar, extract, go into qt folder and run ./backintime-qt, but doesn't work if I install it 

### ISSUE THREAD

**Issue by MostHated** [bit-team/backintime#1014] opened 2019-07-08 01:47 UTC
A month or two ago I (seemingly randomly) had Back In Time fail to run due to python errors. I can't recall off hand what they were, but I believe they were similar to the one below. After hours of trying everything I could try to find, it just seemed to be one after another so I just removed it and forgot about it and went to find another application to use.

I randomly thought about it again today, and just for S&G I downloaded the release tar and went to manually run it. To my surprise, it fired right up, I did a backup and things looked fine, it picked up right where it left off.

For some reason though, it works just fine if I go into qt folder from the tar and run ./backintime-qt, but doesn't work if I install it. Once I install it, running backintime gives the below error. Even if I go back into the original folder and try to run ./backintime-qt again, which worked before installing, it gives the error. Once I uninstall it I can go back in and run ./backintime-qt and then it runs again.

If it is not installed via the deb, and is simply run manually, is it still going to run on my defined schedule? If not, what would be the best way to go about making it so it will without having to install it via the deb? Is there a list of the steps that occur during install and I can make sure the necessary ones are configured as needed?

Thanks,
-MH

```
~/Downloads/backintime-1.2.0/qt » ./backintime-qt                  mosthated@mosthated-pc

Back In Time
Version: 1.2.0

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/local/lib/python3.7/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/local/lib/python3.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mosthated/Downloads/backintime-1.2.0/qt/app.py", line 1592, in <module>
    cfg = backintime.startApp('backintime-qt')
  File "/home/mosthated/Downloads/backintime-1.2.0/common/backintime.py", line 521, in startApp
    return getConfig(args, False)
  File "/home/mosthated/Downloads/backintime-1.2.0/common/backintime.py", line 669, in getConfig
    cfg = config.Config(config_path = args.config, data_path = args.share_path)
  File "/home/mosthated/Downloads/backintime-1.2.0/common/config.py", line 279, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/home/mosthated/Downloads/backintime-1.2.0/common/tools.py", line 1715, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/local/lib/python3.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/local/lib/python3.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/local/lib/python3.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/local/lib/python3.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/local/lib/python3.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1

```

**Comment by codesmaker** [comment] 2019-07-08 13:22
Hi,

Could be the same as #1013?

**Comment by MostHated** [comment] 2019-07-08 22:57
Ah, yeah, it does look like it. Strange it works fine when not installed, I would imagine it might work for him as well. I will post in there.

**Comment by emtiu** [comment] 2022-10-08 21:59
Closing as duplicate of #921.

**Closed by emtiu** 2022-10-08 21:59 UTC
