### ISSUE TITLE
Unable to start backup

### ISSUE THREAD

**Issue by ont4300** [bit-team/backintime#1253] opened 2022-05-07 21:45 UTC
This is a new install.
When creating a new profile using SSH, I get the following error message when I go to save it

Remote host 192.168.50.100 doesn't support '['rsync', '--recursive', '--times', '--devices', '--specials', '--hard-links', '--human-readable', '--links', '--perms', '--executability', '--group', '--owner', '--rsh=ssh -o ServerAliveInterval=240 -o LogLevel=Error -o IdentityFile=/root/.ssh/id_rsa -p 22', '/tmp/tmp6lzinc5n/a', 'backman@192.168.50.100:"/Backup/tmp_PHJHSC"/']':
rsync: mkdir "/home/backman/"/Backup/tmp_PHJHSC"" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(664) [Receiver=3.1.3]

I can do a local backup with no problems. I am able to do passwordless logins using SSH. The configuration comes from a prior backup that worked. I have attached a screenshot of the settings that I am using.

Thanks... Tom.

![Screenshot_20220507_173809](https://user-images.githubusercontent.com/24478202/167272533-9b39aeff-090d-4a31-b2a2-dcd5df675a5d.png)

**Comment by jjinco33** [comment] 2022-05-09 04:10
This just started for me as well. 

I had a good backup on May 4th from Kubuntu 21.10 install (unsure what BiT or rsync versions installed there), updated to Kubuntu 22.04 and it failed (once again unclear what BiT and rsync versions installed there). Ignored initially as several things broke on that install. 

On a fresh install of openSUSE Tumbleweed ran into this trying to configure to connect to the same server previously used with identical settings as before. Passwordless login works between source and target machines, have not tried a local location as target.

On my current install I have Back In Time 1.3.1 and rsync 3.2.3.

Error text (user and machine names changed):
`Remote host 192.168.1.3 doesn't support '['rsync', '--recursive', '--times', '--devices', '--specials', '--hard-links', '--human-readable', '--links', '--acls', '--xattrs', '--perms', '--executability', '--group', '--owner', '--rsh=ssh -o ServerAliveInterval=240 -o LogLevel=Error -o IdentityFile=/home/user/.ssh/id_rsa -p 7885', '/tmp/tmp4ahvf_th/a', 'user@192.168.1.3:"/home/user/Personal/name/DesktopName/tmp_J1KNCX"/']':
rsync: [Receiver] mkdir "/home/user/"/home/user/Personal/name/DesktopName/tmp_J1KNCX"" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(787) [Receiver=3.2.3]`

Please update if I am just missing something obvious or if there is an issue, and if there is an issue what I can provide to help sort it.

**Comment by jjinco33** [comment] 2022-05-12 18:58
Testing between two VMs, Ubuntu 22.04 using build from PPA bit-team/stable can backup to opensuse tumbleweed without the error. 

Opensuse tumbleweed guest client still encounters the issue when attempting to connect to Ubuntu or opensuse server, including itself. This was attempted with 1.3.1 from Yast install, 1.3.0 compiled from source, and 1.3.2 compiled from source.

**Comment by ont4300** [comment] 2022-05-12 23:06
Not to be outdone...

I am installing ubuntu studio 22.04 on a friend's laptop. I installed Ubuntu's version from their regular repository which had some problems running. Checking further, I found that there was a newer version available which corrected some problem with python. I installed that version and had no problem doing local files backup.

Following jjinco33's lead, I created a SSH backup from the ubuntu machine to the backup server and had no problems running. That is, a backup from Ubuntu 22.04 to openSuse 15.3.

Hope this helps... Tom.

**Comment by arvidjaar** [comment] 2022-05-13 09:19
This is behavior change in rsync 3.2.4 which is included in Tumbleweed. rsync now quotes all shell meta-characters by default which means remote side receives wrong file name with double quotes as part of it. Probably the most portable is to export `RSYNC_OLD_ARGS=1` to restore previous behavior (should have no impact on previous rsync versions). See https://download.samba.org/pub/rsync/NEWS#BEHAVIOR_CHANGES-3.2.4.

**Comment by asiergda** [comment] 2022-05-14 16:26
Hi, you can add the option --old-args in the Expert Options tab of the gui.
![image](https://user-images.githubusercontent.com/30633798/168440424-5cb0c3a0-fc1c-4625-a57c-208ac8775996.png)

Regards

**Comment by ont4300** [comment] 2022-05-14 17:02
Thanks for that. I had been wondering where to put that parameter.  Everything is good now.

Thanks... Tom.

**Comment by jjinco33** [comment] 2022-05-14 20:43
Confirm this worked for me as well.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment] 2022-06-19 15:05
This seems to be a a duplicate of #1247. @emtiu please close.

The problem is known and workarounds also. This problem has a high priority for fixing.

**Closed** 2022-06-19 15:39 UTC
Labels: High
