### ISSUE TITLE
trouble with symlinks on a FUSE external SSD

### ISSUE THREAD

**Issue by Herve5** [bit-team/backintime#1085] opened 2020-05-06 16:43 UTC
Hello,
In order to improve the speed of regular backups I tried to exchange my ordinary external USB HD with one that is SSD-based, whose performance when measured with things like hdparm -t /dev/sdb is indeed way faster. Requesting info on the disk shows it is formatted as Fuse.
The trouble is, I get hundreds of error messages with "function not supported" apparently when trying to copy elements that MAY be symlinks; at least, what I can see at the end of the process ("done with errors") is a gigantic archive where probably many of the things that should be symlinked are just duplicated.
As there are many parameters in the setup (and I am not a pro) I may have made an error somewhere, but otherwise is there an experience of trouble with Fuse and symlinks, or more generally with Fuse and BIT?
Thank you!
Hervé

**Comment by buhtzz** [comment] 2022-09-25 12:39
@Herve5 There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Documentation (Again the symlink problem)

**Comment by emtiu** [comment] 2022-10-22 11:45
"Fuse" is not a filesystem, but a mechanism to support certain non-*nix filesystems such as NTFS. Filesystems mounted this way can often lack features which backintime needs (such as symlinking or hardlinking). This is likely the cause of this problem. Closing as outdated/unanswered.

**Closed by emtiu** 2022-10-22 11:45 UTC
