### ISSUE TITLE
rsyncRemove needs to handle rsyncOptionsEnabled

### ISSUE THREAD

**Issue by Jskud** [bit-team/backintime#1507] opened 2023-08-23 19:27 UTC
Issue: `rsyncRemove `needs to handle `rsyncOptionsEnabled`
Change: 

```
[Jskud@home backintime]$ diff -F def -u  /usr/share/backintime/common/tools*.py
--- /usr/share/backintime/common/tools-ORIG.py	2023-08-23 10:54:03.491235473 -0700
+++ /usr/share/backintime/common/tools.py	2023-08-23 11:20:49.606744959 -0700
@@ -665,6 +665,12 @@ def rsyncRemove(config, run_local = True
     """
     cmd = ['rsync', '-a', '--delete']
     if run_local:
+##----------------
+##      add any needed extra rsync arguments, e.g., ``--old-args'' as needed w/ new rsync in Ubuntu 20.04
+##      // Jskud Wed Aug 23 10:56:25 PDT 2023
+        if config.rsyncOptionsEnabled():
+            cmd.extend(shlex.split(config.rsyncOptions()))
+##----------------
         cmd.extend(rsyncSshArgs(config))
     return cmd
```
 

To help us diagnose the problem quickly, please provide the output of the console command `backintime --diagnostics`.

backintime 1.2.1

backintime: error: Unknown Argument(s): --diagnostics

Additionally, please specify as precisely as you can the package or installation source where you got BackInTime. Sometimes there are multiple alternatives, like [for Arch-based distros](https://aur.archlinux.org/packages?K=backintime).

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

Section: universe/utils
Source: backintime
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Jonathan Wiltshire <jmw@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug

1.2.1-2 (/var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_focal_universe_binary-amd64_Packages) (/var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_focal_universe_binary-i386_Packages) (/var/lib/dpkg/status)

**Comment by buhtz** [comment] 2023-08-24 07:02
Dear Jskud,

thanks for reporting this. It is not easy to understand your report because you provide only a diff without further explanations.

Let me try to rephrase it and please confirm if I'm right here or not:
 - You do use Back In Time version 1.2.1-2 from Ubuntu universe repository?
 - You do use Ubuntu 20.04 LTS?
 - You created a fix you show us with the diff?

Am I get it correct? The primary problem is that the _additional rsync options_ from the _Export Options_ (see screenshot) are not used while removing snapshots?

![image](https://github.com/bit-team/backintime/assets/11861496/e95f0e82-2b24-4080-bf32-692d77267891)

Can you give an example of rsync options that are relevant to you when removing a snapshot?

If this is about `--old-args` as I do read from your diff comment:
There is no need for that argument anymore which was a workaround for a [fixed bug](https://github.com/bit-team/backintime/issues/1247). Please see [Incompatibility with rsync >= 3.2.4](https://github.com/bit-team/backintime#incompatibility-with-rsync-324-or-newer).
Your specific problem might be a bug with Ubuntus update policy and there ignorance with common standards.  In short: Beginning with rsync 3.2.4 the default behavior with _argument protection_ in rsync changed. The problem with Ubuntu was that Ubuntu did backported that behavior into their own rsync versions **lower** (!!!) then 3.2.4. They IMHO violated their own LTS policy.

You now have sevaral options:
  - Upgrade to Ubuntu 23.04 because it provides a fixed Back In Time and an up to date rsync version. I know it is not LTS.
  - Install Back In Time from source (via `./configure && make && sudo make install`) as described in our readme). This should work also on such an "old" Ubuntu installation. But there is no guarantee.
  - Install Back In Time from PPA (see Readme.md)

You can find several bug reports arround rsync and backintime on Ubuntus bug tracker discussing this problem. If you use LTS because you insist to have a "stable" distribution you should think about migrating to Debian stable. They won't mess with versions and backporting like this.

**Comment by Jskud** [comment] 2023-08-24 07:48
Dear buhtz,

Right on all counts, and BIG THANKS for the extra info about how Canonical/Ubuntu is a culprit in this ...

In more detail,

You do use Back In Time version 1.2.1-2 from Ubuntu universe repository?
_Yes,_
You do use Ubuntu 20.04 LTS?
_Yes_.
You created a fix you show us with the diff?
_Yes_.
The primary problem is that the additional rsync options from the Export Options (see screenshot) are not used while removing snapshots?
_Yes.  It's the **--old-args** option that needs to be passed to rsync when using rsyncRemove._

FYI: wIthout the fix, we still get the snapshot removed -- rsync fails quickly when invoked from snapthots.py's remove, and it looks like shutil.rmtree() ends up doing the job ... but it seems to take longer.

I should be able to build and install on Ubuntu 20.04, so I plan to go that route.

Thanks again.  Your detailed, constructive, and gentle reply is much appreciated.

**Comment by buhtz** [comment] 2023-08-24 08:24
I missed something. If you need to stay at the current Ubuntu and Back In Time version not doing any upgrades you could set the environment variable `RSYNC_OLD_ARGS`. This should force rsync to use the "old behavior". But I'm not sure if the messed-up-backported-ubuntu-rsync take care of that.

> extra info about how Canonical/Ubuntu is a culprit in this ...

It is only my personal opinion. Some people might disagree with me.

> I should be able to build and install on Ubuntu 20.04, so I plan to go that route.

Feel free to ask further questions.

We know about two PPAs. The [https://launchpad.net/~bit-team/+archive/ubuntu/stable](first) is managed by one of our upstream maintainers. And there is [this PPA](https://git.sdxlive.com/PPA/). Please report to their maintainers first if you have problems with it.

I will leave this issue open for some time because we need to think about if we need "extra rsync options" when removing snapshots. I would say know and I can not imagine one of them.

But we should be more clear in the settings dialog that this extra options are going only to the do-snapshot-rsync-call.

**Comment by Jskud** [comment] 2023-08-24 09:53
Hi buhtz,

Thanks for the pointers to the PPAs, including the pedigree for https://github.com/bit-team/backintime/issues/first.

I do think we need the extra arguments in rsyncRemove so the usual rsync --delete works efficiently.  Having rsync --delete fail and falling through to the call to shutil.rmtree() seems to take longer.  And of course, errors reported in the logs can confuse people ... so we should fix it for that reason as well.

FYI: I did set the environment variable RSYNC_OLD_ARGS (as well as tried to pass in --old-args), but without --old-args getting picked up ( I guess the backport got botched), I get failures like this -- note the odd "/root//"/backup/..." in the error message
```
	Aug 23 03:46:32 [redacted-local] backintime (root/1): DEBUG: [common/snapshots.py:1379 Execute.smartRemove] Call command "rsync -a --delete --rsh=ssh -o ServerAliveInterval=240 -o LogLevel=Error -o IdentityFile=/root/.ssh/id_rsa -p 22 /tmp/tmp4b868_qa/ root@[redacted-remote]:"/backup/__BackInTime__/backintime/[redacted-local]/root/1/20230821-122912-150""
	Aug 23 03:46:32 [redacted-local] backintime (root/1): WARNING: [common/snapshots.py:1379 Execute.smartRemove] Command "rsync -a --delete --rsh=ssh -o ServerAliveInterval=240 -o LogLevel=Error -o IdentityFile=/root/.ssh/id_rsa -p 22 /tmp/tmp4b868_qa/ root@[redacted-remote]:"/backup/__BackInTime__/backintime/[redacted-local]/root/1/20230821-122912-150"" returns 3 | rsync: change_dir#3 "/root//"/backup/__BackInTime__/backintime/[redacted-local]/root/1" failed: No such file or directory (2)#012rsync error: errors selecting input/output files, dirs (code 3) at main.c(694) [Receiver=3.1.2]
```

**Comment by buhtz** [comment] 2023-08-24 10:23
I finally find my own rsyc-update-bug-report: https://answers.launchpad.net/ubuntu/+source/rsync/+question/705772
And this is a related BIT bug report:https://bugs.launchpad.net/ubuntu/+source/backintime/+bug/2009756

And reading this I might have explained the original problem wrong. Can you show me your rsync version? It might be higher then 3.2.4. The problem was not they backported new behavior to an older rsync version. The problem was that the upgraded the rsync version in the LTS release. For me LTS means "stable". But injecting a newer rsync version with a completely modified default behavior broke some things. That was the problem.

> FYI: I did set the environment variable RSYNC_OLD_ARGS

Thanks for testing this. If I'm right and your rsync is 3.2.4 or newer it should work. Please look into rsync manpage to find the correct environment variable. It could be that your rsync is that new that `RSYNC_OLD_ARGS` is not supported anymore. But there is `RSYNC_PROTECT_ARGS` with the opposite effect.

> I do think we need the extra arguments in rsyncRemove so the usual rsync --delete works efficiently.

Which argument would it be? As I tried to pointing out `--old-args` is not relevant anymore in the latest BIT release.. Bit 1.2.1 is kind of outdated. Of course we try to support all users with all versions but we have limited ressources. And 1.2.1 is quit old. If Ubuntu does put it into its LTS then they should use their own ressources to fix it.

> Having rsync --delete fail and falling through to the call to shutil.rmtree() seems to take longer.

I aggree that this is not an elegant solution. But it is a different Issue. It is on our todo list to re-design parts like this.
Myself I even don't understand why there is an rsync-delete-and-try-shutil.rm-if-it-fails-flow. It needs further investigation before touching it.

Keep in mind that the current maintenance team is fresh and we have not founded BIT. Most of the code is foreign to us and we need to do research about it before touching it.

To my current point of view and knowledge I don't see a need for "extra rsync arguments" for the removeSnapshot step.

The situation you are into is nearly specific to Ubuntu only because Canonical introduced an rsync-update into an LTS release without taking sideeffects into account. Of course there are exceptions. But I won't workaround Canonicals mistakes.

> And of course, errors reported in the logs can confuse people ... so we should fix it for that reason as well.

Improving log output is also a separate Issue we have on our list. But the error you describe shouldn't happen to users with up-2-date BIT and Ubuntu systems.

**Comment by Jskud** [comment] 2023-08-24 10:35
(1) $ rsync --version
rsync  version 3.1.3  protocol version 31
Copyright (C) 1996-2018 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/

(2) RSYNC_OLD_ARGS is the right env var -- as documented in the man page, and partially active in practice -- I needed it to get some other paths through backintime to work.

Thanks for the research and info -- much appreciated.

**Comment by buhtz** [comment] 2023-08-24 10:50
Now I'm confused. 😄
The Ubuntu update problem I refereed to seems not to be relevant in your case because your Ubuntu is much older.
I'm back on start and don't know why you got this error messages. With rsync 3.1.3 the `--old-args` argument should not be needed. Or maybe Ubuntu backported much more then I know. The latest rsync version in "focal" is "3.1.3-8ubuntu0.6" from August this year. They might have introduced something.

The cleanest solution would be to upgrade your Ubuntu, BIT or migrate to another GNU/Linux distro.

It is possible that I'm on a totally wrong trail here.

**Comment by buhtz** [comment] 2023-08-24 10:52
https://bugs.launchpad.net/ubuntu/+source/rsync/+bug/2032932

**Comment by Jskud** [comment] 2023-08-24 14:21
I'm not sure what's really going on here either, but I know what failed, and I know what works.  And I'm glad to have it working, as well as to know what's going on, so thanks for your persistent assistance and constructive suggestions.
Thanks too for filing that bug report to get the issue investigated for ongoing focal fossa releases.

These backintime/rsync issues are fallout from a clean upgrade to Ubuntu 20.04(LTS) from 18.04 that I did a few days ago.

Indeed, I'm running this (older release -- from 2018), but I need both the --old-args and RSYNC_OLD_ARGS fixes.
```
$ rsync --version
rsync  version 3.1.3  protocol version 31
Copyright (C) 1996-2018 by Andrew Tridgell, Wayne Davison, and others.
```

Per this [Ubuntu website](https://packages.ubuntu.com/search?keywords=rsync), that's what I should have.  
```
focal (20.04LTS) (net): fast, versatile, remote (and local) file-copying tool
3.1.3-8ubuntu0.5 [security]: amd64 i386
3.1.3-8 [ports]: arm64 armhf ppc64el riscv64 s390x
focal-updates (net): fast, versatile, remote (and local) file-copying tool
3.1.3-8ubuntu0.5: amd64 arm64 armhf i386 ppc64el riscv64 s390x 
```

Oddly, if I was on Ubuntu 20 latest (w/ updates), then it shows I should have 3.1.3-8ubuntu0.5, not 3.1.3-8ubuntu0.6 as you reported.

Thanks again.

**Comment by buhtz** [comment] 2023-09-05 05:32
I do close it because we can not reproduce it.
Please feel free to reopen it if it happens again.

**Closed as completed by buhtz** 2023-09-05 05:32 UTC
Labels: Bug
