### ISSUE TITLE
Backup of $HOME hangs infinitely at "saving permissions" after upgrading to bionic 18.04

### ISSUE THREAD

**Issue by bentolor** [bit-team/backintime#927] opened 2018-09-03 17:07 UTC
Since my update to bionic two months ago from xenial, my BIT backup plan for my home directory never completed at all even once.

It seems to complete the first rsync stage, but then hangs at the "Saving permission"-stage and I don't have any clue how to diagnose / debug the issue.

Running from command line and triggering a backup does

```
$ backintime-qt --debug 
DEBUG: [common/backintime.py:585 argParse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.2.0~alpha17

…

INFO: [common/snapshots.py:1010 Snapshots.takeSnapshot] Call rsync to take the snapshot
DEBUG: [common/snapshots.py:690 Snapshots.backup] Call command "rsync --recursive --times --devices DEBUG: [common/snapshots.py:690 Snapshots.backup] Command "rsync --recursiv..." returns 0
INFO: [common/snapshots.py:835 Snapshots.backupConfig] Save config file
INFO: [common/snapshots.py:872 Snapshots.backupPermissions] Save permissions
DEBUG: [common/sshtools.py:206 SSH.startSshAgent] ssh-agent already running. Skip starting a new one.
DEBUG: [common/sshtools.py:319 SSH.unlockSshAgent] Private key /home/ben/.ssh/REDACTED is already unlocked in ssh agent
DEBUG: [common/encfstools.py:579 Decode.startProcess] start 'encfsctl decode' process
DEBUG: [common/encfstools.py:583 Decode.startProcess] Call command: encfsctl decode --extpass=backintime-askpass /home/ben/.local/share/backintime/mnt/4A0B37D9/mountpoint
DEBUG: [common/snapshots.py:1057 Snapshots.takeSnapshot] Call command "rsync --dry-run -r --out-format=%n --rsh=ssh -o ServerAliveInterval=240 -o LogLevel=Error -o IdentityFile=/home/ben/.ssh/REDACTED -p 22 admin@REDACTED:"/share/MD0_DATA/Backups/home/7QxnYjsi5RSEftKDx9qGbzq3/k7ZyYNV0C,yeUTgnIuhcEQBb/AyR8ehutEqbvovJLf36EYUH1/weJqrGaptTSMwTPoezYN2mTb/YHVULaNfHtETJIiYx8-MmqN6/zBksKzx1a3G0lIbOPqKeJEe1"/ /tmp/tmpnamkxtyr/"
```

And there it hangs an indefinite time. 

I tried to run the last statement from the commandline to get more info about the issue, but unfortunately I failed. Rsync claims `Unexpected remote arg` and I was unable to find out how to quote/run the last rsync-Command..

Any hints how to better understand the issue. I.e. how can I change `-o LogLevel=Error` to a more verbatim version?

Thanky you very much!

**Comment by bentolor** [comment] 2019-03-28 13:44
Any hints how one would be able to debug this issue? On trying to manually run the rsync command on client side I fail to figure out how to properly reformat/quote the rsync command. 

     $ rsync --dry-run -r --out-format=%n --rsh=ssh -o ServerAliveInterval=240 -o LogLevel=Debug -o IdentityFile=/home/ben/.ssh/id_rsa -p 22 bentolor@storage1:'/data/share/home/bentolor/YZ-dv7qHc-LhAfTOKzIFrf2B/TG5hAow5ZCSB4LlkfugUNPYX/3TfDTCeD2bWDS2GOog0F2D4-/TA7x88VZ1UxLaX1nzTlnDbFU/jw1o4qfrsSgopckAbsxlC50r/FPXoR-qewxXInvPh3AYDCq13'/ /tmp/tmpib28logx
     Unexpected remote arg: bentolor@storage1:/data/share/home/bentolor/YZ-dv7qHc-LhAfTOKzIFrf2B/TG5hAow5ZCSB4LlkfugUNPYX/3TfDTCeD2bWDS2GOog0F2D4-/TA7x88VZ1UxLaX1nzTlnDbFU/jw1o4qfrsSgopckAbsxlC50r/FPXoR-qewxXInvPh3AYDCq13/

**Comment by nod0n** [comment] 2019-05-16 07:15
I have a same issue with BiT 1.2.0. My Backups did work for ~2 years. Now as I got the 1.2.0 update, the backup never finishes. I let it backup the complete night, and it didn't finish until the morning. The step "Working: Saving permissions" was running the complete night.

**Comment by buhtzz** [comment] 2022-09-26 09:10
@bentolor @nod0n There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Bug, Feedback

Maybe a duplicate of #988 ?

**Comment by emtiu** [comment] 2022-10-08 13:01
Possibly related to #988, but I'm not sure. The Issue concerns pre-1.2.0 backups running 1.2.0 code for the first time, which is an increasingly rare situation. Let's wait for reporter feedback a little more.

**Comment by bentolor** [comment] 2022-10-08 13:58
Hi @bbuhtzz  and @emtiu.  This big is no longer reproducible on my side. But I've also switched/upgraded systems. 

Please close this issue. Thank you guys!

**Closed** 2022-10-08 19:55 UTC
Labels: Bug, Feedback
