### ISSUE TITLE
Dark system theme doesn't work for application after upgrading from Xubuntu 18.04 to 22.04

### ISSUE THREAD

**Issue by olegpoltora** [bit-team/backintime#1428] opened 2023-04-23 05:45 UTC
Dark system theme (Adwaita-dark) doesn't work for application after upgrading from Xubuntu 18.04 to 22.04

backintime 1.2.1

Of course in Xubuntu 18.04 all was ok.

See screenshot
![Screenshot_2023-04-23_08-42-33](https://user-images.githubusercontent.com/66324201/233821945-e859cc7a-3438-4ae5-8116-e899ac503b88.png)

**Comment by buhtz** [comment] 2023-04-23 15:56
Dear Oleg,
thanks for reporting.

Looking into the package archive of Ubuntu I see that Ubuntu 18.04 LTS ("bionic") had BIT 1.1.12 on board. In this years BIT had a Gnome (Gtk?) and KDE GUI.

In 18.04 ("jammy") there is Qt only.

A lot of things changed since 1.1.12 which is *more than 9 years* old!

I'm not into the Qt part of BIT yet. So I don't have more details. I'm assume that Qt does support dark modes but BIT maybe isn't prepared for that.

I would keep this open as a Feature Request if no one else as something to add to it.

**Comment by buhtz** [comment] 2023-04-23 17:34
~Not verified but it seems that Qt5 (PyQt5) doesn't support systems dark them out of the box.
https://stackoverflow.com/q/48256772/4865723
It means Qt doesn't detect the systems default system and do use it. I suggest not touch it in Qt5 but take this into account when migrating to Qt6.~

**Comment by emtiu** [comment] 2023-04-23 18:42
Dark Theme definitely works in Kubuntu 22.04, even for the old BackInTime 1.2.1. Not sure what role exactly KDE plays in that, though.

**Comment by buhtz** [comment] 2023-04-23 18:48
Then maybe it depends on the installed theme used by the desktop environment (or Qt). Maybe dark and light themes are fusioned into one such theme file?

Did you tried to switch the theme of your desktop environment to another one?

**EDIT**: Can you please post the output of `neofetch` for us.

**Comment by buhtz** [comment] 2023-05-16 13:11
Dear @olegpoltora,
can you please show us the output of `neofetch` on your system. This will give us more information's about your desktop environment and help us to reproduce your problem in a virtual machine.

**Comment by buhtz** [comment] 2023-06-29 12:56
Closing this issue in near future if no new information's are added.

**Comment by aryoda** [comment] 2023-07-09 16:25
I have upgraded my DEV system from U20.04 to U22.04 and can observe the same problem:

- The BiT windows uses a light instead of the dark theme (so the background is white instead of dark!)

I cannot remember if it worked before but obviously Qt5 is choosing too apply another style for unknown reasons:

> DEBUG: [qt/qttools.py:225 createQApplication] QT QPA platform plugin: xcb
> DEBUG: [qt/qttools.py:226 createQApplication] QT_QPA_PLATFORMTHEME=qt5ct
> DEBUG: [qt/qttools.py:231 createQApplication] QT_STYLE_OVERRIDE=<not set>
> DEBUG: [qt/qttools.py:234 createQApplication] QT active style: fusion
> DEBUG: [qt/qttools.py:235 createQApplication] QT fallback style: 
> DEBUG: [qt/qttools.py:236 createQApplication] QT supported styles: ['Breeze', 'cleanlooks', 'gtk2', 'cde', 'motif', 'plastique', 'Windows', 'Fusion']

**Comment by aryoda** [comment] 2023-07-09 16:36
The reason is that `qt5ct` is used as QT platform theme which uses an additional (qt-specific) GUI to configure the theme: `qt5ct` ("Qt5 Configuration Utility - you have to install this using your package manager).

Here you can change the style in a combo:
![Screenshot from 2023-07-09 18-34-30](https://github.com/bit-team/backintime/assets/11374410/0ade58c2-b8a6-424a-a481-ca4c12d657ce)

The only thing is: There is no nice dark theme (only gtk2 in my case) and no way to use the active Gnome/Gtk theme... 

**Edit:** For more background see also: https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications

**Edit 2:** See also: https://askubuntu.com/a/910143

**Comment by buhtz** [comment] 2024-06-04 14:13
I can not reproduce this on Debian 12 with adwaita-dark. Do I misunderstand something? Is it still relevant?

I can only say that BIT need to be restarted when the DE theme changed. BIT does not react immediately. This issue is know but won't be fixed because it would need a lot of extra code to make it work.

**Comment by buhtz** [comment] 2024-06-30 06:53
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,

**Closed as completed by buhtz** 2024-06-30 06:53 UTC
Labels: Qt, Feature, GUI & Cosmetics, Low
