### ISSUE TITLE
BIT won't start

### ISSUE THREAD

**Issue by donkarziavelli** [bit-team/backintime#1052] opened 2019-12-15 10:09 UTC
Hey there! Trying to get it running on Xubuntu 19.04 and this comes up.

`Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 363, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 1592, in <module>
    cfg = backintime.startApp('backintime-qt')
  File "/usr/share/backintime/common/backintime.py", line 521, in startApp
    return getConfig(args, False)
  File "/usr/share/backintime/common/backintime.py", line 669, in getConfig
    cfg = config.Config(config_path = args.config, data_path = args.share_path)
  File "/usr/share/backintime/common/config.py", line 279, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1715, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 280, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1
`

Anyone an idea what to do?

**Comment by yochananmarqos** [comment] 2019-12-15 16:37
Same here on Manjaro Linux and building from source fails during the test:
```
python -m unittest  -b test/test_applicationinstance.py
...................
----------------------------------------------------------------------
Ran 19 tests in 0.048s

OK
python -m unittest  -b test/test_argparser.py
.....................
----------------------------------------------------------------------
Ran 21 tests in 3.647s

OK
python -m unittest  -b test/test_backintime.py
FF
Stderr:
/home/yochanan/Documents/pkgbuilds/backintime/src/backintime-1.2.1/common/test/test_backintime.py:33: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals("", subprocess.getoutput("python3 backintime.py --quiet"))

======================================================================
FAIL: test_local_snapshot_is_successful (test.test_backintime.TestBackInTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yochanan/Documents/pkgbuilds/backintime/src/backintime-1.2.1/common/test/test_backintime.py", line 68, in test_local_snapshot_is_successful
    self.assertEqual(proc.returncode, 0, msg)
AssertionError: 1 != 0 : Returncode: 1
stderr: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yochanan/Documents/pkgbuilds/backintime/src/backintime-1.2.1/common/backintime.py", line 1165, in <module>
    startApp()
  File "/home/yochanan/Documents/pkgbuilds/backintime/src/backintime-1.2.1/common/backintime.py", line 517, in startApp
    args.func(args)
  File "/home/yochanan/Documents/pkgbuilds/backintime/src/backintime-1.2.1/common/backintime.py", line 1150, in checkConfig
    cfg = getConfig(args)
  File "/home/yochanan/Documents/pkgbuilds/backintime/src/backintime-1.2.1/common/backintime.py", line 669, in getConfig
    cfg = config.Config(config_path = args.config, data_path = args.share_path)
  File "/home/yochanan/Documents/pkgbuilds/backintime/src/backintime-1.2.1/common/config.py", line 279, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/home/yochanan/Documents/pkgbuilds/backintime/src/backintime-1.2.1/common/tools.py", line 1715, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1

stdout: 
Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Update to config version 6


======================================================================
FAIL: test_quiet_mode (test.test_backintime.TestBackInTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yochanan/Documents/pkgbuilds/backintime/src/backintime-1.2.1/common/test/test_backintime.py", line 33, in test_quiet_mode
    self.assertEquals("", subprocess.getoutput("python3 backintime.py --quiet"))
AssertionError: '' != 'Traceback (most recent call last):\n  Fil[2163 chars]de 1'
Diff is 2241 characters long. Set self.maxDiff to None to see it.

Stderr:
/home/yochanan/Documents/pkgbuilds/backintime/src/backintime-1.2.1/common/test/test_backintime.py:33: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals("", subprocess.getoutput("python3 backintime.py --quiet"))

----------------------------------------------------------------------
Ran 2 tests in 0.966s

FAILED (failures=2)
make: *** [Makefile:566: unittest] Error 1
```

**Comment by usulofarakis** [comment] 2019-12-15 17:39
I also have the same error on Manjaro Testing.

`Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Update to config version 6
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1165, in <module>
    startApp()
  File "/usr/share/backintime/common/backintime.py", line 521, in startApp
    return getConfig(args, False)
  File "/usr/share/backintime/common/backintime.py", line 669, in getConfig
    cfg = config.Config(config_path = args.config, data_path = args.share_path)
  File "/usr/share/backintime/common/config.py", line 279, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1715, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1`

**Comment by yochananmarqos** [comment] 2019-12-16 15:45
The issue was resolved with the `python-pyqt5` [5.13.2-8](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/pyqt5&id=1f1442dbeff260d21ae79d3139c2e42847478065) update today.

**Comment by usulofarakis** [comment] 2019-12-16 19:10
> The issue was resolved with the `python-pyqt5` [5.13.2-8](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/pyqt5&id=1f1442dbeff260d21ae79d3139c2e42847478065) update today.

Confirmed, now running as expected.

**Comment by picousse** [comment] 2020-05-13 09:40
I still got the same error with version 5.14.1 (ubuntu 20.04)

**Comment by picousse** [comment] 2020-05-13 10:02
I found a solution,
However not sure what did the trick...

I uninstalled pip3 PyQt5
and installed using python3-pyqt5

Fixed it for me on ubuntu 20.04

running
/usr/bin/python3 -Es /usr/share/backintime/qt/serviceHelper.py
was helpfull

**Comment by bighegi** [comment] 2022-01-17 18:19
Same Problem here,
Ubuntu 20.04 LTS, python3-pyqt5-5.14.1+dfsg-3build1, same error:

```
$ backintime-qt

Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 1592, in <module>
    cfg = backintime.startApp('backintime-qt')
  File "/usr/share/backintime/common/backintime.py", line 521, in startApp
    return getConfig(args, False)
  File "/usr/share/backintime/common/backintime.py", line 669, in getConfig
    cfg = config.Config(config_path = args.config, data_path = args.share_path)
  File "/usr/share/backintime/common/config.py", line 279, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1715, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program net.launchpad.backintime.serviceHelper: Permission denied
```

Interesting though, I have another similar machine just with slight differences and there BIT works normal.
The challenge is to find the difference ... but I got no good idea where to start. All installed BIT and python3-pyqt5* packages are the same ...

Thanks a lot in advance!
Stefan.

**Comment by emtiu** [comment] 2022-09-10 22:01
Thanks for reporting and debugging! Does this bug still happen for anyone, or have updates eliminated the problem?

**Comment by aryoda** [comment] 2022-09-17 22:21
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

This error message is reported in several issues:

Related to: #1233, #1014, #1013, #963, #921, #756
Possibly also to: #1068

@emtiu Could/should this type of issue be "escalated" to a "high incident"?

**Comment by emtiu** [comment] 2022-09-23 11:35
Thanks for the good spot! I'll try and combine/collect those Issues. Yes, https://github.com/bit-team/backintime/labels/High is the right label for this problem.

It's always the rolling release distros that run into this kind of trouble, isn't it? ;) Moving target makes it so much harder to reproduce.

**Comment by buhtzz** [comment] 2022-09-26 08:43
If this here is the main/collecting issue for all the duplicates can we modify its title to a more informative one please?

**Comment by emtiu** [comment] 2022-10-08 21:58
Closing as duplicate of #921.

@bighegi: Your report is almost the only one about this problem from a recent, non-rolling-release distro. Please comment in #921 if you have more information. Thanks :)

**Closed by emtiu** 2022-10-08 21:58 UTC
Labels: High, Bug, Feedback, Heisenbug
