### ISSUE TITLE
Backintime complaining about crontab being not installed

### ISSUE THREAD

**Issue by afettouhi** [bit-team/backintime#617] opened 2016-08-12 18:42 UTC
I recently build a new PC and I moved the config file from backintime from my old machine over to the new one so that I can restore from all the snapshots I have. This has worked fine but I deceided to move some the restored files around. After doing that I wanted to change setup of backtime and point it to the new directories where my files now are. But when I try remove directories and add new ones it complains about crontab not being installed. But I have fcron installed and running on my Arch Linux box. I then try to remove the run nice option under advanced but everytime I click ok it complains

Can't find crontab.
Are you sure cron is installed ?
If not, then deactivate all automatic backups.

Why is it complaining about this. My new install is almost identical to my old one.

**Comment by Germar** [comment] 2016-08-12 19:01
Duplicate of #610 

Can you install a different cron daemon which provides `crontab` instead of `fcrontab` until I fixed this?
Alternative you could add a symlink `ln -s fcrontab /usr/bin/crontab`

**Closed by Germar** 2016-08-12 19:01 UTC
Labels: duplicate

**Comment by afettouhi** [comment] 2016-08-12 19:12
Yeah I installed cronie instead.
