### ISSUE TITLE
Remote rsync hangs

### ISSUE THREAD

**Issue by bspiegel33** [bit-team/backintime#1133] opened 2021-02-14 15:51 UTC
I am running backintime on Ubuntu 18 desktop and the remote end is a DD-WRT router with entware and an external drive.  Backintime hangs when setting up the profile.  Debugging this, the problem boils down to the rsync command.

I manually ran several versions of the rsync command.  This command worked perfectly:
rsync --log-file=/home/bob/rsync.log -avPh  --rsh="ssh -p 4444  -o IdentityFile=/home/user/.ssh/mine.key"   --chmod=Du+wx /home/user/scripts "root@localhost:/mnt/sda2/test"

However, the command from backintime hangs when I run this manually:
rsync -rtDHh --links --no-p --no-g --no-o --info=progress2 --no-i-r --bwlimit=10000 --rsh="ssh -p 4444  -o IdentityFile=/home/user/.ssh/mine.key"  --dry-run --chmod=Du+wx /home/user/scripts "root@10.47.67.213:/mnt/sda2/test"

rsync is version on both ends:
rsync  version 3.1.2  protocol version 31

The backintime command initializes 2 rsync processes on the remote side that seem to hang.    If I kill them on the remote machine, the source command ends.

I suspect it's one of the rsync parameters that is causing this.  Ideas?

**Comment by bspiegel33** [comment] 2021-02-14 15:56
Oops - posting error.  The 2nd command was this:
rsync -rtDHh --links --no-p --no-g --no-o --info=progress2 --no-i-r --bwlimit=10000 --rsh="ssh -p 4444 -o IdentityFile=/home/user/.ssh/mine.key" --dry-run --chmod=Du+wx /home/user/scripts "root@localhost:/mnt/sda2/test"

I have the router connect to the source machine via ssh and open a remote port forward so the source machine can connect back.

**Comment by buhtzz** [comment] 2022-09-25 12:23
@bspiegel33 There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback, External, Bug

**Comment by emtiu** [comment] 2022-10-22 16:13
Closing, because the reporter is not responding, and we can't reproduce the problem.

**Closed by emtiu** 2022-10-22 16:13 UTC
