### ISSUE TITLE
BIT include folders that are not specified

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#345] opened 2015-10-11 17:15 UTC
BiT is looking even better these days (I am using 0.9.99.56) and the ability to open the logs directly is very helpful, thank you! This enabled me to discover something that I don't understand. I have excluded hidden files from my home folder backup but I have included two hidden folders to be backed up, viz:

home/martin/.openoffice.org/3/user/basic
home/martin/.openoffice.org/3/user/wordbook

because I want to back up my custom dictionary and my macros for OpenOffice. 

However, when I look at the log of the most recent backup I see this

[C] >f.st...... home/martin/.openoffice.org/3/user/registry/data/org/openoffice/Setup.xcu
[C] >f.st...... home/martin/.openoffice.org/3/user/registry/data/org/openoffice/Office/Recovery.xcu
[C] >f..t...... home/martin/.openoffice.org/3/user/registry/data/org/openoffice/Office/Views.xcu

and this led me to look at what was backed up. I found that the folder .openoffice.org is being backed up (all subfolders and files) even though I have included only two subfolders.

Is this a bug?

With grateful thanks, Martin

---

Imported from Launchpad using lp2gh.
- date created: 2011-01-12T21:38:40Z
- owner: danleweb
- the launchpad url was https://bugs.launchpad.net/bugs/702139

**Comment by Germar** [comment] 2015-10-11 21:35
(by danleweb)
It seems to be a bug.
Can you attach the list of all included / excluded items ?
Can you run from command line "backintime -b" and check the "rsync" commands ?

Regards,
Dan

**Comment by Germar** [comment] 2015-10-11 21:35
(by yusuf-martin)
Many thanks, and please see below!

All included items:

/home/martin
/home/martin/.openoffice.org/3/user/wordbook

All excluded items:

.gvfs
.cache*
[Cc]ache*
.thumbnails*
[Tt]trash*
*~
/home/martin/Ubuntu One
.dropbox*
.*
/home/martin/Downloads


Result of backintime -b

Back In Time
Version: 1.0.6

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: on process begins
INFO: [GnomePlugin.Systray.run]
INFO: Profile_id: 1
INFO: [GnomePlugin.Systray.run] begin loop
INFO: Compare with old snapshot: 20110310-110009-725
INFO: Command "rsync -rtDH --links --no-p --no-g --no-o  --delete --delete-excluded  -i --dry-run --out-format="BACKINTIME: %i %n%L" --chmod=Du+wx  --exclude="/media/littleblack" --exclude="/home/martin/.local/share/backintime" --include="/home/martin/" --include="/home/" --include="/home/martin/.openoffice.org/3/user/wordbook/" --include="/home/martin/.openoffice.org/3/user/" --include="/home/martin/.openoffice.org/3/" --include="/home/martin/.openoffice.org/" --exclude=".gvfs" --exclude=".cache*" --exclude="[Cc]ache*" --exclude=".thumbnails*" --exclude="[Tt]rash*" --exclude="*.backup*" --exclude="*~" --exclude="/home/martin/Ubuntu One" --exclude=".dropbox*" --exclude=".*" --exclude="/home/martin/Downloads" --include="/home/martin/**" --include="/home/martin/.openoffice.org/3/user/wordbook/**" --exclude="*" / "/media/littleblack/backintime/martin-laptop/martin/1/20110310-110009-725/backup/"" returns 0
INFO: Nothing changed, no back needed
INFO: Command "rm -rf "/media/littleblack/backintime/martin-laptop/martin/1/20110310-122507-927"" returns 0
WARNING: No new snapshot
INFO: Remove backups older than: 20010310-000000
INFO: [smart remove] considered: ['20110310-110009-725', '20110310-100002-986', '20110309-190005-885', '20110309-180003-221', '20110309-170011-790', '20110309-160004-560', '20110309-150004-244', '20110309-130002-691', '20110309-110004-894', '20110309-100003-129', '20110309-080002-179', '20110308-190008-101', '20110308-180010-607', '20110308-170003-812', '20110308-160007-599', '20110308-150008-392', '20110308-100002-103', '20110307-190002-339', '20110305-150004-426', '20110304-220004-418', '20110228-220009-940', '20110226-200002-239', '20110219-170001-820', '20110131-220001-328', '20101231-100001-890', '20101129-163942-838', '20101031-180008-414', '20100930-140254-350', '20100826-150001-783', '20100730-220001-797', '20100630-170001-797', '20100531-170002-797', '20100430-200004-459', '20100331-130010-459', '20100226-160010-459', '20100131-160011-459', '20091227-220007-459']
INFO: [smart remove] keep all >= 20110308-000000-506 and < 20110311-000000-836
INFO: [smart remove] keep first >= 20110310-000000-326 and < 20110311-000000-947
INFO: [smart remove] keep first >= 20110309-000000-165 and < 20110310-000000-100
INFO: [smart remove] keep first >= 20110308-000000-608 and < 20110309-000000-789
INFO: [smart remove] keep first >= 20110307-000000-837 and < 20110308-000000-162
INFO: [smart remove] keep first >= 20110306-000000-605 and < 20110307-000000-897
INFO: [smart remove] keep first >= 20110305-000000-553 and < 20110306-000000-526
INFO: [smart remove] keep first >= 20110304-000000-929 and < 20110305-000000-804
INFO: [smart remove] keep first >= 20110306-000000-694 and < 20110314-000000-924
INFO: [smart remove] keep first >= 20110227-000000-781 and < 20110307-000000-611
INFO: [smart remove] keep first >= 20110220-000000-406 and < 20110228-000000-411
INFO: [smart remove] keep first >= 20110213-000000-936 and < 20110221-000000-850
INFO: [smart remove] keep first >= 20110301-000000-489 and < 20110401-000000-725
INFO: [smart remove] keep first >= 20110201-000000-296 and < 20110301-000000-514
INFO: [smart remove] keep first >= 20110101-000000-948 and < 20110201-000000-193
INFO: [smart remove] keep first >= 20101201-000000-580 and < 20110101-000000-193
INFO: [smart remove] keep first >= 20101101-000000-136 and < 20101201-000000-206
INFO: [smart remove] keep first >= 20101001-000000-304 and < 20101101-000000-914
INFO: [smart remove] keep first >= 20100901-000000-893 and < 20101001-000000-850
INFO: [smart remove] keep first >= 20100801-000000-638 and < 20100901-000000-548
INFO: [smart remove] keep first >= 20100701-000000-615 and < 20100801-000000-358
INFO: [smart remove] keep first >= 20100601-000000-462 and < 20100701-000000-506
INFO: [smart remove] keep first >= 20100501-000000-747 and < 20100601-000000-829
INFO: [smart remove] keep first >= 20100401-000000-596 and < 20100501-000000-460
INFO: [smart remove] keep first >= 20100301-000000-684 and < 20100401-000000-219
INFO: [smart remove] keep first >= 20100201-000000-939 and < 20100301-000000-182
INFO: [smart remove] keep first >= 20100101-000000-719 and < 20100201-000000-939
INFO: [smart remove] keep first >= 20091201-000000-230 and < 20100101-000000-535
INFO: [smart remove] keep first >= 20091101-000000-956 and < 20091201-000000-675
INFO: [smart remove] keep first >= 20091001-000000-256 and < 20091101-000000-615
INFO: [smart remove] keep first >= 20090901-000000-380 and < 20091001-000000-702
INFO: [smart remove] keep first >= 20090801-000000-524 and < 20090901-000000-406
INFO: [smart remove] keep first >= 20090701-000000-442 and < 20090801-000000-937
INFO: [smart remove] keep first >= 20090601-000000-975 and < 20090701-000000-443
INFO: [smart remove] keep first >= 20090501-000000-216 and < 20090601-000000-819
INFO: [smart remove] keep first >= 20090401-000000-736 and < 20090501-000000-679
INFO: [smart remove] keep first >= 20090101-000000-445 and < 20100101-000000-760
INFO: [smart remove] keep first >= 20100101-000000-387 and < 20110101-000000-805
INFO: [smart remove] keep first >= 20110101-000000-156 and < 20120101-000000-358
INFO: [smart remove] keep snapshots: ['20110310-110009-725', '20110310-100002-986', '20110309-190005-885', '20110309-180003-221', '20110309-170011-790', '20110309-160004-560', '20110309-150004-244', '20110309-130002-691', '20110309-110004-894', '20110309-100003-129', '20110309-080002-179', '20110308-190008-101', '20110308-180010-607', '20110308-170003-812', '20110308-160007-599', '20110308-150008-392', '20110308-100002-103', '20110307-190002-339', '20110305-150004-426', '20110304-220004-418', '20110226-200002-239', '20110219-170001-820', '20110228-220009-940', '20110131-220001-328', '20101231-100001-890', '20101129-163942-838', '20101031-180008-414', '20100930-140254-350', '20100826-150001-783', '20100730-220001-797', '20100630-170001-797', '20100531-170002-797', '20100430-200004-459', '20100331-130010-459', '20100226-160010-459', '20100131-160011-459', '20091227-220007-459']
INFO: Keep min free disk space: 1024 Mb
INFO: [GnomePlugin.Systray.run] end loop
INFO: Unlock

**Comment by Germar** [comment] 2015-10-11 21:35
(by danleweb)
The problem is your include:
    "/home/martin" means this folder and all files/folders in it recursively.
("/home/martin/.openoffice.org/3/user/wordbook" is included too).

For your case you can, keep the 2 includes:
   1. /home/martin
   2. /home/martin/.openoffice.org/3/user/wordbook
and add to exclude list:
   /home/martin/.openoffice.org/*

This way all "/home/martin/.openoffice.org/*" will be excluded, except "/home/martin/.openoffice.org/3/user/wordbook".

Regards,
Dan

**Comment by Germar** [comment] 2015-10-11 21:35
(by yusuf-martin)
Thanks Dan. I have tried your suggestion and as far as I can tell it does not help. I have run backupintime -b again and provide the output below, along with the same previous information so that you can be sure of what is now included and excluded (note it is actually .libreoffice rather than .openoffice.org now).

All included items:

/home/martin
/home/martin/.libreoffice/3/user/wordbook

All excluded items:

.gvfs
.cache*
[Cc]ache*
.thumbnails*
[Tt]trash*
*~
/home/martin/Ubuntu One
.dropbox*
.*
/home/martin/Downloads
/home/martin/.libreoffice/*

Result of backintime -b

Version: 1.0.6

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: [GnomePlugin.Systray.run]
 INFO: on process begins
INFO: [GnomePlugin.Systray.run] begin loop
INFO: Profile_id: 1
INFO: Compare with old snapshot: 20110310-140002-942
INFO: Command "rsync -rtDH --links --no-p --no-g --no-o  --delete --delete-excluded  -i --dry-run --out-format="BACKINTIME: %i %n%L" --chmod=Du+wx  --exclude="/media/littleblack" --exclude="/home/martin/.local/share/backintime" --include="/home/martin/" --include="/home/" --include="/home/martin/.libreoffice/3/user/wordbook/" --include="/home/martin/.libreoffice/3/user/" --include="/home/martin/.libreoffice/3/" --include="/home/martin/.libreoffice/" --exclude=".gvfs" --exclude=".cache*" --exclude="[Cc]ache*" --exclude=".thumbnails*" --exclude="[Tt]rash*" --exclude="*.backup*" --exclude="*~" --exclude="/home/martin/Ubuntu One" --exclude=".dropbox*" --exclude=".*" --exclude="/home/martin/Downloads" --exclude="/home/nartin/.libreoffice/*" --include="/home/martin/**" --include="/home/martin/.libreoffice/3/user/wordbook/**" --exclude="*" / "/media/littleblack/backintime/martin-laptop/martin/1/20110310-140002-942/backup/"" returns 0
INFO: Create hard-links
INFO: Command "find "/media/littleblack/backintime/martin-laptop/martin/1/20110310-140002-942/backup/" -type d -exec chmod u+wx {} \;" returns 0
INFO: Command "cp -aRl "/media/littleblack/backintime/martin-laptop/martin/1/20110310-140002-942/backup/"* "/media/littleblack/backintime/martin-laptop/martin/1/new_snapshot/backup/"" returns 0
INFO: Command "find "/media/littleblack/backintime/martin-laptop/martin/1/20110310-140002-942/backup/" -type d -exec chmod a-w {} \;" returns 0
INFO: Command "chmod -R a+w "/media/littleblack/backintime/martin-laptop/martin/1/new_snapshot"" returns 0
INFO: Call rsync to take the snapshot
INFO: Command "rsync -rtDH --links --no-p --no-g --no-o  --delete --delete-excluded  -v  --chmod=Du+wx  --exclude="/media/littleblack" --exclude="/home/martin/.local/share/backintime" --include="/home/martin/" --include="/home/" --include="/home/martin/.libreoffice/3/user/wordbook/" --include="/home/martin/.libreoffice/3/user/" --include="/home/martin/.libreoffice/3/" --include="/home/martin/.libreoffice/" --exclude=".gvfs" --exclude=".cache*" --exclude="[Cc]ache*" --exclude=".thumbnails*" --exclude="[Tt]rash*" --exclude="*.backup*" --exclude="*~" --exclude="/home/martin/Ubuntu One" --exclude=".dropbox*" --exclude=".*" --exclude="/home/martin/Downloads" --exclude="/home/nartin/.libreoffice/*" --include="/home/martin/**" --include="/home/martin/.libreoffice/3/user/wordbook/**" --exclude="*" / "/media/littleblack/backintime/martin-laptop/martin/1/new_snapshot/backup/" 2>&1" returns 0
INFO: Save config file
INFO: Command "cp /home/martin/.config/backintime/config /media/littleblack/backintime/martin-laptop/martin/1/new_snapshot/backup/.." returns 0
INFO: Save permissions
INFO: Create info file
INFO: Command "chmod -R a-w "/media/littleblack/backintime/martin-laptop/martin/1/20110310-142059-532/backup"" returns 0
INFO: Command "chmod -R a-w "/media/littleblack/backintime/martin-laptop/martin/1/20110310-140002-942/backup/"" returns 0
INFO: Remove backups older than: 20010310-000000
INFO: [smart remove] considered: ['20110310-142059-532', '20110310-140002-942', '20110310-135646-227', '20110310-135159-201', '20110310-130002-341', '20110310-123106-679', '20110310-110009-725', '20110310-100002-986', '20110309-190005-885', '20110309-180003-221', '20110309-170011-790', '20110309-160004-560', '20110309-150004-244', '20110309-130002-691', '20110309-110004-894', '20110309-100003-129', '20110309-080002-179', '20110308-190008-101', '20110308-180010-607', '20110308-170003-812', '20110308-160007-599', '20110308-150008-392', '20110308-100002-103', '20110307-190002-339', '20110305-150004-426', '20110304-220004-418', '20110228-220009-940', '20110226-200002-239', '20110219-170001-820', '20110131-220001-328', '20101231-100001-890', '20101129-163942-838', '20101031-180008-414', '20100930-140254-350', '20100826-150001-783', '20100730-220001-797', '20100630-170001-797', '20100531-170002-797', '20100430-200004-459', '20100331-130010-459', '20100226-160010-459', '20100131-160011-459', '20091227-220007-459']
INFO: [smart remove] keep all >= 20110308-000000-792 and < 20110311-000000-415
INFO: [smart remove] keep first >= 20110310-000000-411 and < 20110311-000000-784
INFO: [smart remove] keep first >= 20110309-000000-575 and < 20110310-000000-911
INFO: [smart remove] keep first >= 20110308-000000-146 and < 20110309-000000-532
INFO: [smart remove] keep first >= 20110307-000000-175 and < 20110308-000000-554
INFO: [smart remove] keep first >= 20110306-000000-567 and < 20110307-000000-286
INFO: [smart remove] keep first >= 20110305-000000-324 and < 20110306-000000-178
INFO: [smart remove] keep first >= 20110304-000000-980 and < 20110305-000000-617
INFO: [smart remove] keep first >= 20110306-000000-983 and < 20110314-000000-783
INFO: [smart remove] keep first >= 20110227-000000-760 and < 20110307-000000-531
INFO: [smart remove] keep first >= 20110220-000000-154 and < 20110228-000000-923
INFO: [smart remove] keep first >= 20110213-000000-633 and < 20110221-000000-712
INFO: [smart remove] keep first >= 20110301-000000-111 and < 20110401-000000-324
INFO: [smart remove] keep first >= 20110201-000000-104 and < 20110301-000000-943
INFO: [smart remove] keep first >= 20110101-000000-315 and < 20110201-000000-799
INFO: [smart remove] keep first >= 20101201-000000-200 and < 20110101-000000-665
INFO: [smart remove] keep first >= 20101101-000000-531 and < 20101201-000000-105
INFO: [smart remove] keep first >= 20101001-000000-165 and < 20101101-000000-536
INFO: [smart remove] keep first >= 20100901-000000-769 and < 20101001-000000-649
INFO: [smart remove] keep first >= 20100801-000000-742 and < 20100901-000000-479
INFO: [smart remove] keep first >= 20100701-000000-526 and < 20100801-000000-943
INFO: [smart remove] keep first >= 20100601-000000-175 and < 20100701-000000-187
INFO: [smart remove] keep first >= 20100501-000000-206 and < 20100601-000000-181
INFO: [smart remove] keep first >= 20100401-000000-211 and < 20100501-000000-362
INFO: [smart remove] keep first >= 20100301-000000-890 and < 20100401-000000-478
INFO: [smart remove] keep first >= 20100201-000000-904 and < 20100301-000000-226
INFO: [smart remove] keep first >= 20100101-000000-967 and < 20100201-000000-196
INFO: [smart remove] keep first >= 20091201-000000-467 and < 20100101-000000-242
INFO: [smart remove] keep first >= 20091101-000000-786 and < 20091201-000000-574
INFO: [smart remove] keep first >= 20091001-000000-196 and < 20091101-000000-671
INFO: [smart remove] keep first >= 20090901-000000-320 and < 20091001-000000-341
INFO: [smart remove] keep first >= 20090801-000000-388 and < 20090901-000000-559
INFO: [smart remove] keep first >= 20090701-000000-247 and < 20090801-000000-566
INFO: [smart remove] keep first >= 20090601-000000-344 and < 20090701-000000-668
INFO: [smart remove] keep first >= 20090501-000000-135 and < 20090601-000000-683
INFO: [smart remove] keep first >= 20090401-000000-227 and < 20090501-000000-126
INFO: [smart remove] keep first >= 20090101-000000-417 and < 20100101-000000-342
INFO: [smart remove] keep first >= 20100101-000000-481 and < 20110101-000000-263
INFO: [smart remove] keep first >= 20110101-000000-448 and < 20120101-000000-153
INFO: [smart remove] keep snapshots: ['20110310-142059-532', '20110310-140002-942', '20110310-135646-227', '20110310-135159-201', '20110310-130002-341', '20110310-123106-679', '20110310-110009-725', '20110310-100002-986', '20110309-190005-885', '20110309-180003-221', '20110309-170011-790', '20110309-160004-560', '20110309-150004-244', '20110309-130002-691', '20110309-110004-894', '20110309-100003-129', '20110309-080002-179', '20110308-190008-101', '20110308-180010-607', '20110308-170003-812', '20110308-160007-599', '20110308-150008-392', '20110308-100002-103', '20110307-190002-339', '20110305-150004-426', '20110304-220004-418', '20110226-200002-239', '20110219-170001-820', '20110228-220009-940', '20110131-220001-328', '20101231-100001-890', '20101129-163942-838', '20101031-180008-414', '20100930-140254-350', '20100826-150001-783', '20100730-220001-797', '20100630-170001-797', '20100531-170002-797', '20100430-200004-459', '20100331-130010-459', '20100226-160010-459', '20100131-160011-459', '20091227-220007-459']
INFO: Keep min free disk space: 1024 Mb
INFO: [GnomePlugin.Systray.run] end loop
INFO: Unlock

**Comment by emtiu** [comment] 2022-09-24 22:14
Closing as duplicate of #561.

**Closed by emtiu** 2022-09-24 22:14 UTC
Labels: discuss
