### ISSUE TITLE
Backintime ignores old backups

### ISSUE THREAD

**Issue by ghost** [bit-team/backintime#999] opened 2019-05-16 18:43 UTC
I do backups with Backintime since Fedora25 now and it always worked like a charme. Two weeks ago i upgraded from Fedora29 to Fedora30 and since the update to **Backintime 1.20** i cannot create any backup with Backintime.

I use a 1TB external HDD for my backups with a free space of 100GB. I used to backup my userhome only, no system backup.

When i took a backup in F29, in the status bar of Backintime and also in the protocol there was written, that the current files are compared with the last backup. This comparison seems to be gone, Backintime ignores all existing backups and wants to backup all my files, my complete /home directory, instead of just backing up only the changed files since the last backup with F29.

This leads to the next bug i detected. Backintime runs into errors because of the HDD running out of space, but in the status bar of Backintime one can read the message "Ready. No need for a backup". But this is not true, i have definitely some files which have changed. When i start the backup again, the folder new_snapshot with all the files of the last backup is deleted and Backintime creates the folder new_snapshot again and starts to backup my complete /home directory to this new_snapshot folder again. It's a neverending loop :-(

I took further investigations about this and created a new profile to backup only a small folder for the first time. This folder was backed up correctly and changes on the files were also backed up correctly without backing up the whole folder every time. So the problem is only while using backups created with Backintime of F29 and older.

Here is the protocol with the backup command of F29:
[I] …
**[I] Mit Schnappschuss 2019-04-30 18:22:42 vergleichen** **_(=compare with snapshot ...)_**
[I] rsync -rtDHh --links --no-p --no-g --no-o --info=progress2 --no-i-r  --delete --delete-excluded  -i --dry-run --out-format="BACKINTIME: %i %n%L" --chmod=Du+wx  --exclude="/run/media/frank/TimeMachine-MBP" --exclude="/home/frank/.local/share/backintime" --exclude=".local/share/backintime/mnt" --include="/home/frank/" --include="/home/" --exclude=".gvfs" --exclude=".cache/*" --exclude=".thumbnails*" --exclude="[Tt]rash*" --exclude="*.backup*" --exclude="*~" --exclude=".dropbox*" --exclude="/proc/*" --exclude="/sys/*" --exclude="/dev/*" --exclude="/run/*" --exclude="/etc/mtab" --exclude="/var/cache/apt/archives/*.deb" --exclude="lost+found/*" --exclude="/tmp/*" --exclude="/var/tmp/*" --exclude="/var/backups/*" --exclude=".Private" --exclude="/home/frank/VirtuelleMaschinen" --include="/home/frank/*" **--exclude="*" / "/run/media/frank/TimeMachine-MBP/backintime/franks-macbookpro/frank
/1/20190430-182242-685/backup/"**

Here is the protocol with the backup command of F30:
[I] …
**[I] Schnappschuss wird erstellt** **_(=create snapshot)_**
[I] rsync --recursive --times --devices --specials --hard-links --human-readable --links --perms --executability --group --owner --info=progress2 --no-inc-recursive --delete --delete-excluded -v -i --out-format=BACKINTIME: %i %n%L --link-dest=../../20190501-093501-787/backup --chmod=Du+wx --exclude=/run/media/frank/TimeMachine-MBP --exclude=/home/frank/.local/share/backintime --exclude=.local/share/backintime/mnt --include=/home/frank/ --include=/home/ --exclude=.gvfs --exclude=.cache/* --exclude=.thumbnails* --exclude=[Tt]rash* --exclude=*.backup* --exclude=*~ --exclude=.dropbox* --exclude=/proc/* --exclude=/sys/* --exclude=/dev/* --exclude=/run/* --exclude=/etc/mtab --exclude=/var/cache/apt/archives/*.deb --exclude=lost+found/* --exclude=/tmp/* --exclude=/var/tmp/* --exclude=/var/backups/* --exclude=.Private --exclude=/home/frank/VirtuelleMaschinen --include=/home/frank/* **--exclude="*" / /run/media/frank/TimeMachine-MBP/backintime/franks-macbookpro/frank/1/new_snapshot/backup**

**Comment by Aeron1** [comment] 2019-05-16 19:29
just downloaded version 1.1.24 and compiled it with qt4 and now my backups works again :-)

**Comment by csperle** [comment] 2019-05-19 09:35
Same for me on an Ubuntu machine. I have Backintime running for years without problems. But with version 1.2.0 Backintime ignores the old backups and therefore does not do an incremental backup any more. After purging the  bit-team ppa and rolling back to version 1.1.24 everything works again.

**Comment by Herve5** [comment] 2019-05-19 10:42
I am definitely the opposite of a pro, but have been running BackInTime for a couple of years now.
What I know is, when you make a deep upgrade to the system, the old backups appear to belong to the old user, not you, and many things go wrong with them, while new backups are OK.
That was the case when I switched from Ubuntu to pure Debian : I now have two structure on my backup disk (backup folder/backintime/myTuxmachine/measanewuser and /meastheolduser) and I even cannot delete the old architecture as it is not 'belonging to me'...
Indeed I tried to delete it in the terminal (sudo failed for whichever reason), then sudoing Caja (!) to just throw the old folder away : it disappeared, but far to fast, and as there is nothing in the dustbin I now don't even know where it is :(

**Comment by Aeron1** [comment] 2019-05-19 10:51
>... What I know is, when you make a deep upgrade to the system, the old backups appear to belong to the old user, not you, and many things go wrong with them, while new backups are OK. ...

yes, this may happen, if you backup your system, but this must not happen, if you only backup your /home directory. there the user must always be the same.

**Comment by Herve5** [comment] 2019-05-19 14:29
I am definitely the opposite of a pro, but have been running BackInTime for a couple of years now.
What I know is, when you make a deep upgrade to the system, the old backups appear to belong to the old user, not you, and many things go wrong with them, while new backups are OK.
That was the case when I switched from Ubuntu to pure Debian : I got two structure on my backup disk (backup folder/backintime/myTuxmachine/measanewuser and /meastheolduser) and I as newuser even couldn't delete the old architecture easily as it was not 'belonging to me'...
Could it be something like this?
H.

**Comment by andreasklostermaier** [comment] 2019-05-23 17:30
Can confirm: BiT 1.2.0 is not doing incremental backups anymore. I have tried 3 backups since the update with following results:
- initial backup to a brandnew disk: works fine.
- incremental backup to an existing disk: drive ran full because a full backup was executed. No success or error messages, BiT just stalls.
- incremental backup to an existing disk that has a lot of empty space left: full backup was executed instead of the incremental backup but succeeded due to sufficient space on the disk. The snapshot is not shown in the list, though.

I suggest anyone doing fresh backups on new disks, preferrably with an older version of BiT asap, as I do not quite know in which state the stalled backups are.

**Comment by timbo-lino** [comment] 2019-06-06 04:15
> just downloaded version 1.1.24 and compiled it with qt4 and now my backups works again with 1.1.24 :-)

@Aeron1 

I am on F30 too but running into some errors during the configure process:

```
./configure
which: no coverage in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:....
```

But python3-coverage is installed

Can you tell me how you compiled it?

**Comment by Aeron1** [comment] 2019-06-06 15:55
hi timbo-lino

hmmm. it was my first program ever that i compiled :-)...

i downloaded the files from here https://github.com/bit-team/backintime/tree/series1.1
than followed the instructions further down this link. I did all the commands as root.

###From sources
#####Common
Command:
  cd common
  ./configure
  make
  make test
  sudo make install

#####Qt4 GUI
Command:
  cd qt4
  ./configure
  make
  sudo make install

hope this helps

**Comment by buhtzz** [comment] 2022-09-26 08:39
There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

I assume this is because of the breaking changes starting with 1.2.0. So #988 is relevant here?

Tag: Feedback, Bug

Close as duplicate.

**Comment by emtiu** [comment] 2022-10-09 22:12
Closing as duplicate of #988.

**Closed by emtiu** 2022-10-09 22:12 UTC
