### ISSUE TITLE
Python3 segmentation fault

### ISSUE THREAD

**Issue by phiebie** [bit-team/backintime#1183] opened 2021-08-05 13:09 UTC
Debian bullseye uptodate, no unmet dependencies according to aptitude.
Starting with backintime 1.2.1-2 from Debian I got 5 out of 10 times after the backup-proces had finished and I closed backintime via the end-button
[   ]
/usr/bin/backintime-qt: line 31:  2771 Segmentation fault      python3
-Es ${APP_PATH}/app.py "$@"
[   ]
and was on the command prompt.
Upgraded to version 1.3.1 from github, installed with makedeb.sh, but the same problem stays. Even 5 minutes waiting before pressing the end-button has no effect. BIT does not finish completely as the backup-directory stays still open with this last snapshot contained in it.
My concern is: is this merely a cosmetical problem and are all my backups still 100% reliable or must I fear, that, when it comes to a restore, I am left with a mess iso a flawless system.
This mishap is not reproducible intentionally, it happens... or not.
Where could I look for the culprit?

**Comment by aryoda** [comment] 2022-09-09 00:40
Possibly related to #1095

**Comment by emtiu** [comment] 2022-09-09 08:31
Yes, this is certainly a duplicate of #1095. Thank you for the report, @phiebie!

**Closed by emtiu** 2022-09-09 08:31 UTC
