### ISSUE TITLE
Clicked the button restore after selecting a snapshot but no restoring takes place

### ISSUE THREAD

**Issue by giteauserbit** [bit-team/backintime#1508] opened 2023-08-28 16:25 UTC
I am testing restoring a snapshot, in vain.

**Actual**

1. Launch "Back in Time (root)" from the Trisquel menu.
2. Type sudo password
3. A pop up window displays the message: "Back in Time is not configured. [...] restore previous configuration?"
4. I click "Yes"
5. A GUI opens
6. I select the snapshot I want to restore (the last one)
7. The home GUI of BiT opens but no restoring takes place

**Expected**

I imagine that BiT should restore `/home` of the snapshot I selected.

Other info:

The external drive where the snapshots live is mounted. I can browse through the snapshots folders. 

```
$ backintime -v
backintime 1.2.1
$ uname -a
Linux computer 5.4.0-156-generic #173+10.0trisquel11 SMP Fri Aug 11 20:08:50 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

> To help us diagnose the problem quickly, please provide the output of the console command `backintime --diagnostics`.

```
$ backintime --diagnostics
backintime: error: Unknown Argument(s): --diagnostics
```

> Additionally, please specify as precisely as you can the package or installation source where you got BackInTime. Sometimes there are multiple alternatives, like [for Arch-based distros](https://aur.archlinux.org/packages?K=backintime).

Backintime is installed by default on Trisquel GNU/Linux.

**Comment by aryoda** [comment] 2023-08-28 17:28
- Did you take the snapshot on the same computer with the same user (root)?
- Why is the configuration gone ("Back in Time is not configured")?
- Where did you get the "previous configuration" file from?
- **Edit:** Which source folder are backed-up in the snapshot (home folder, remote drives...)
- **Edit:** Which "mode" is configured in the profile of the snapshot ("local", "local encrypted", "SSH", "SSH encrypted")?

> $ backintime --diagnostics

You are using an old (but still commonly installed) version of BiT which does not yet support diagnostics information so this option will not work.

**Comment by giteauserbit** [comment] 2023-08-30 17:18
Thank you for your answers.

> Did you take the snapshot on the same computer with the same user (root)?

No. I took the snapshots on a different computer with a different user (root).

>Why is the configuration gone ("Back in Time is not configured")?

It is a freshly installed GNU/Linux OS. BiT was never used on this computer, although it is installed by default.

I am testing restoring the last snapshot I took on my other "main" computer to a freshly installed system.

>Where did you get the "previous configuration" file from?

On my "main" computer I guess (I'm not sure I'm answering your question correctly). The one where I have been taking the snapshots.

>Edit: Which source folder are backed-up in the snapshot (home folder, remote drives...)

/home

>Edit: Which "mode" is configured in the profile of the snapshot ("local", "local encrypted", "SSH", "SSH encrypted")?

"local"

>You are using an old (but still commonly installed) version of BiT which does not yet support diagnostics information so this option will not work.

Thank you for clarifying. 

Shall I infer from your questions that I should try to restore snapshots on a computer with the same username? Or, is it possible to restore a snapshot on a different computer (from the one where the snapshots where taken) with a different username?

Thanks again for your help.

**Comment by aryoda** [comment] 2023-08-30 19:00
> is it possible to restore a snapshot on a different computer (from the one where the snapshots where taken) with a different username?

This should work :open_mouth: 

1. Could you please do the test again and provide me the log output (anonymize user names and other sensitive + pick only the relevant log output from the bottom of the output):

   `journalctl --since=today | grep -i backintime`

2. Did you start BiT at the new computer also as `root` or as normal user

3. Into which folder did you try to restore?

4. **Edit:** Do you take snapshots of the complete `home` folder?

**Comment by aryoda** [comment] 2023-08-30 19:17
Possible duplicate of #933 (still open so a great chance to fix this now :wink:)

**Comment by emtiu** [comment] 2023-08-31 09:54
Okay, I've tested this scenario in a VM, and I think that @giteauserbit may just be **missing an extra step** to trigger a restore of the snapshot. I see why this is unexpected, and I think that Back In Time is being confusing here.

When choosing to "restore a previous configuration", and choosing a snapshot to restore from, this concerns **only the configuration** to be loaded. @giteauserbit describes his Step 7: "The home GUI of BiT opens but no restoring takes place". This is actually the intended behavior or Back In Time. At this point, the previous configuration is restored, and Back In Time is ready for use – but no files have been restored yet.

If you want to actually **restore files from a snapshot**, you need to trigger that separately, afterwards. So in the GUI that has now loaded, you would select a snapshot and/or some files, and **use the "Restore" function from the main menu (or right-click menu)**. Let's call this **"Step 8: Start the restore process from the GUI."**

Could you test if you can trigger a restore as expected with this Step 8, @giteauserbit?

**Comment by emtiu** [comment] 2023-08-31 09:59
The best way to avoid this confusion is to change the wording, I think. We use **"restore"** to mean _copy files from a backup into their original place_.

We shouldn't use "restore" to _also_ mean _import the configuration from a snapshot_. We should call this process **"import a configuration"**. Also, the button in the dialog to choose a snapshot should not say "Restore", it should say **"Import"**.

Then it is probably clearer to users what is supposed to happen when you use Back In Time in this scenario:
1. **First, you import a configuration** from a previous snapshot,
3. **then you restore files** from the imported snapshots.

**Comment by giteauserbit** [comment] 2023-09-01 21:47
There is a piece of information I initially omitted I am thinking could maybe help you: in the past, I copied snapshots from the external hard-drive on which snapshots were taken to the external (encrypted) hard-drive I am trying to restore from. I used the command I found in the FAQ: https://github.com/bit-team/backintime/blob/dev/FAQ.md#how-to-move-snapshots-to-a-new-hard-drive to do so. That is:  `rsync -avhH --info=progress2 /SOURCE /DESTINATION`.

I thought this info might be relevant when I read the "step 8" of emtiu's comment. In my case, there is no snapshots in the column titled "snapshots" on the left of the GUI. The column is empty. I am wondering if that is because the path of the present hard-drive is different from the path on the former hard-drive. The one used to take snapshots. Could it be it? I don't know but I thought this information might of some use.

Emtiu, I think you are right to note that the copy of these two steps is confusing. I might have got confused myself, thinking I was restoring a snapshot when I was only restoring a configuration file - but again, in my case, there no snapshots where there should be. In the column on the left.

Answer to [the above questions](https://github.com/bit-team/backintime/issues/1508#issuecomment-1699687811):

> Could you please do the test again and provide me the log output (anonymize user names and other sensitive + pick only the relevant log output from the bottom of the output):

I deleted the .config file of BiT to try to reproduce. Unsuccessfully. BiT does not take me to the path to restore when I open the GUI. Anyway. I think this snippet documents the activities when I tried to restore on August 28th: 

```
Aug 28 16:51:37 computer dbus-daemon[614]: [system] Activating service name='net.launchpad.backintime.serviceHelper' requested by ':1.65' (uid=1000 pid=1128 comm="python3 -Es /usr/share/backintime/common/backintim" label="unconfined") (using servicehelper)
Aug 28 16:51:37 computer dbus-daemon[614]: [system] Successfully activated service 'net.launchpad.backintime.serviceHelper'
Aug 28 16:51:37 computer python3[1128]: backintime (user/1): ERROR: Back In Time is not configured!
Aug 28 16:56:26 computer polkitd(authority=local)[623]: Operator of unix-session:c1 successfully authenticated as unix-user:user to gain TEMPORARY authorization for action net.launchpad.backintime.qtgui for unix-process:1378:29772 [/bin/sh /usr/bin/backintime-qt_polkit] (owned by unix-user:user)
Aug 28 16:56:26 computer pkexec[1381]: user: Executing command [USER=root] [TTY=unknown] [CWD=/home/user] [COMMAND=/usr/bin/backintime-qt]
Aug 28 16:56:26 computer python3[1397]: backintime-qt (root/1): INFO: Update to config version 6
Aug 28 17:01:07 computer python3[1397]: backintime-qt (root/1): ERROR: Failed to get crontab lines: 1, no crontab for root
Aug 28 17:03:22 computer polkitd(authority=local)[623]: Operator of unix-session:c1 successfully authenticated as unix-user:user to gain TEMPORARY authorization for action net.launchpad.backintime.qtgui for unix-process:1967:71659 [/bin/sh /usr/bin/backintime-qt_polkit] (owned by unix-user:user)
Aug 28 17:03:22 computer pkexec[1969]: user: Executing command [USER=root] [TTY=unknown] [CWD=/home/user] [COMMAND=/usr/bin/backintime-qt]
```

Let me know if you need more of the output of `journalctl`.
 
>Did you start BiT at the new computer also as root or as normal user

As root.

> Into which folder did you try to restore?

I am not sure I got there. I don't think I  was asked which folder to restore into.

> Edit: Do you take snapshots of the complete home folder?

I excluded one directory nested under /Documents - and /Download, but I remember the latter is excluded by default by BiT.

**Comment by emtiu** [comment] 2023-09-01 22:20
> In my case, there is no snapshots in the column titled "snapshots" on the left of the GUI. The column is empty. I am wondering if that is because the path of the present hard-drive is different from the path on the former hard-drive. The one used to take snapshots. Could it be it? I don't know but I thought this information might of some use.

That's definitely very relevant ;)

In that case, you need to adjust the configuration so that Back In Time can look for your snapshots in the place where they actually exist.

Between your Steps 6 and 7, you should be presented with a "Settings" dialog. There, you should adjust the path in "Where to save snapshots" to your NEW snapshot location on the NEW drive. You should point this to the folder that contains the `backintime` folder, so if you have `/media/user/EXTERNALDRIVE/backintime`, then you should use the setting `/media/user/EXTERNALDRIVE`.

Play around a little with the paths if it doesn't work at first. You should be able to adjust the settings so that the Back In Time GUI will show your existing snapshots.

**Comment by giteauserbit** [comment] 2023-09-08 13:22
I had tried updating the path to the snapshots, however no snapshots were shown in the left column of the GUI. 

I found my mistake though.

Back when I moved all the snapshots from the former hard drive to the present hard drive where snapshots now live, I moved the directory *nested under* the directory titled `/backintime.` So instead of having a path like `/media/user/drive/backintime/computer/user/1/20230901-180130-241` when trying to restore, I had a path  like `/media/user/drive/computer/user/1/20230901-180130-241` where `/backintime` was missing from the path.

All I had to do to fix this was to create a directory `/backintime `on the drive and nest the existing directory i.e. `/user` under. Then I was able to get BiT to list snapshots in the left column of the GUI.

Since I made the mistake of omitting the `/backintime` directory when I moved snapshots from one drive to another, I am wondering if it would be useful to update the documentation on how to move snapshots to a new drive https://github.com/bit-team/backintime/blob/dev/FAQ.md#how-to-move-snapshots-to-a-new-hard-drive and specify that the directory `/backintime` should be moved (not the one below like I did). I don't know, maybe that is obvious. I will let the maintainers of this repository decide. 

emtiu, aryoda, feel free to close this issue.

**Closed as completed** 2023-09-09 18:24 UTC
Labels: Bug

**Comment by emtiu** [comment] 2023-09-09 18:26
Thanks for your cooperation, @giteauserbit, you've been very helpful in identifying the problem :)

**Comment by aryoda** [comment] 2023-09-10 22:35
See commit 8ffb060634b7cb68203b2c909971041e00fb8239 for the updated FAQ text (mentioning the `backintime` folder as required).

THX @emtiu for updating it!

**Comment by giteauserbit** [comment] 2023-09-15 14:57
And, thank you to both of you @emtiu and @aryoda for taking the time to guide me through to spot my mistake.
