### ISSUE TITLE
No systray icon when running as root

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#408] opened 2015-10-11 17:18 UTC
When run as root, it may not be possible to put the systray icon on the desktops of any user that is logged in, but what about sending a notification?

The objective is to let the user know that a shutdown/reboot would interrupt the backup. (backintime -b is run by anacron)

---

Imported from Launchpad using lp2gh.
- date created: 2012-04-21T13:50:11Z
- owner: ceg
- the launchpad url was https://bugs.launchpad.net/bugs/986570

**Comment by dinoboy197** [comment] 2016-02-11 04:57
> When run as root, it may not be possible to put the systray icon on the desktops of any user that is logged in

BIT, in root mode, begins executing as root, and completes the backup process as root, then exits.

I am not a *nix socket expert, especially when it comes to multiple processes that execute as different users (even with a parent / child process relationship), but I wonder if it would be technically possible (ignoring for the moment any code restructuring required) to, when in root mode:

BIT begins executing as the user who scheduled the backup (not root), but then starts a child process as root which runs the actual snapshot logic and is able to communicate with the parent, which can manage the systray icon.

**Comment by Germar** [comment] 2016-02-11 19:07
I'd rather do it the other way around: 

Start BIT as root (from crontab) and fork a systray-process with `os.seteuid()` to change process owner. The user who created the profile (could be read from `PKEXEC_UID` or `SUDO_USER` environ) should be that new process owner. The user would also need read access to `/root/.local/share/backintime/`

I didn't try yet if this would work. Incorrect environ could still make troubles...

**Comment by Wabuo** [comment] 2016-02-27 08:20
I get an systray icon while the aktualy backup is running but not while the GUI is open.

Im running Archlinux with:
* GNOME Shell 3.18.3
* backintime-qt4
* starting BIT with pkexec

**Comment by Germar** [comment] 2016-02-28 00:18
The systray icon should only show up while creating a new snapshot (no matter if GUI is open). If you just open the GUI it is supposed to not show up.

**Comment by emtiu** [comment] 2022-09-09 09:46
With backintime 1.2.1 on Kubuntu 22.04, this works for me: A backintime icon appears in the systray when a snapshot is being taken, both:
1) from root's crontab, or
2) from the backintime-as-root GUI.

I'll try and test this on some other system, but this Issue cal probably be closed.

**Comment by emtiu** [comment] 2022-10-21 22:33
Other systray problems exist (see #1306), but I'm closing this 10-year-old report that can no longer be reproduced.

**Closed by emtiu** 2022-10-21 22:33 UTC
Labels: Discussion, Feedback
