### ISSUE TITLE
backintime-qt issues with very large screens

### ISSUE THREAD

**Issue by nsoft** [bit-team/backintime#1124] opened 2020-12-13 16:56 UTC
**Description:** When attempting to open `backintime-qt` on my Ubuntu 18.04 desktop with a Samsung Oddessy G9 49" monitor running at 5120x1440 pixels there is a long delay and then the intial "question" and "settings" screens are created at a window size much LARGER than my screen. No text or controls are visible, and the windows created cannot be resized via side or top corners. Bottom corners are inaccessible because they hang off the bottom of the screen. The following error messages are seen in the terminal window: 
````
gus@ns-l1:~$ backintime-qt

Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

ERROR:dbus.proxies:Introspect error on :1.19:/org/gnome/SessionManager: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
ERROR:dbus.proxies:Introspect error on :1.69:/modules/kwalletd5: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
ERROR:dbus.proxies:Introspect error on :1.69:/modules/kwalletd: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::deviceTransform: Painter not active
QPainter::worldTransform: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::setPen: Painter not active
QPainter::setPen: Painter not active
QPainter::end: Painter not active, aborted
QPainter::end: Painter not active, aborted
````

**Steps to reproduce**: 

1. Download version 1.2.1 and unpack on a machine with a 32:9 DQHD monitor 
2. From a terminal run `backintime-qt`

**Workaround**:
I can get the program to start normally if I activate Picture By Picture which divides the screen to show two inputs (since I only have one, half the screen is blank) and halves the horizontal resolution to 2560x1440. Once I do that I an see that the first "Question" dialog is asking "Back in Time is not configured. Would you like to restore a previous configuration?" And settings has 6 tabs all of which seem normal, and once the program is opened I seem to be able to safely restore the original resolution.

**Comment by ploplo** [comment] 2020-12-25 22:14
I have exactly the same issue on a Samsung 49" running Kubuntu 20.04.
I do not get any error output in the terminal.
This happens when I run as root. If I start as regular user it states that it has no saved configuration and opens the gui to navigate to previous backup.
Changing to a smaller screen and starting as root it starts (but with a small window) and configurations are there .

**Comment by sbaragnaus2** [comment] 2021-01-16 10:05
Hi, any chance to get bug fixed? Developement of backintime seems stopped since 2019. Thanks.

**Comment by aryoda** [comment] 2022-10-07 20:21
Does the issue still occur?

It is difficult to reproduce without the same hardware (perhaps on a VM it it is possible to set the screen size beyond the size of the host).

According to this link it may be fixed with a Qt update (so not directly connected to BiT):

https://github.com/bitcoin-core/gui/issues/175#issuecomment-1008627020

**Comment by emtiu** [comment] 2022-10-07 21:15
Well, I nearly broke my wrist, but I managed to crank up an OpenSUSE Tumbleweed VM to >5400x1500, and `backintime-qt` ran just fine, without any failures. So I'm closing this Issue.
![Screenshot_20221007_231217](https://user-images.githubusercontent.com/2159933/194653437-86a16f16-0270-4ac6-ace9-6e9ae707f2f9.png)

**Closed by emtiu** 2022-10-07 21:15 UTC
Labels: Qt, Bug

**Comment by aryoda** [comment] 2022-10-22 13:45
Whichever may have caused the huge window size - the first aid in such cases is:

Open your BiT config file with a text editor (normally stored in this file and location: `~/.config/backintime/config`)
and search for these lines at the end of the config:

```
qt.main_window.height=1142
qt.main_window.width=1482
```

You can now edit the numbers to change the windows size (in pixels).
