### ISSUE TITLE
BIT doesn't backup automatically anymore after the latest update

### ISSUE THREAD

**Issue by codesmaker** [bit-team/backintime#722] opened 2017-03-20 11:00 UTC
Hi Germar,

I've updated BIT to v1.1.14. After the update, the "repeatedly anacron" schedule stopped working. The computers which are still using v1.1.12.a works fine. Any idea?

**Comment by Germar** [comment] 2017-03-21 21:15
I was able to reproduce this but didn't found the reason yet. Looks like I made the last release a bit overhasty, sorry.

**Comment by codesmaker** [comment] 2017-03-22 08:07
It's OK:). Only two PCs were affected and I've disabled the automatic updates of BIT on the other PCs. I would like you to know that BIT is a beautiful piece of software and we depend on it for our laptops' backup. I also would like to take the opportunity to thank you for your hard work, commitment, and great support! Any idea how long will it take to debug?

**Comment by Germar** [comment] 2017-03-28 20:12
Fixed in new release 1.1.16
Sorry for the troubles

**Closed by Germar** 2017-03-28 20:12 UTC
Labels: bug

**Comment by codesmaker** [comment] 2017-03-29 11:25
Thanks Germar. It works.
