### ISSUE TITLE
BIT  repeatedly creates a snapshot for the same file which has not changed

### ISSUE THREAD

**Issue by LateJunction** [bit-team/backintime#1577] opened 2023-12-05 16:33 UTC
To help us diagnose the problem quickly, please provide the output of the console command `backintime --diagnostics`:

```
tony@MS-7D15:~$ backintime --diagnostics
{
    "backintime": {
        "name": "Back In Time",
        "version": "1.4.1-1",
        "latest-config-version": 6,
        "local-config-file": "/home/UsernameReplaced/.config/backintime/config",
        "local-config-file-found": true,
        "global-config-file": "/etc/backintime/config",
        "global-config-file-found": false,
        "started-from": "/usr/share/backintime/common",
        "running-as-root": false,
        "user-callback": "/home/UsernameReplaced/.config/backintime/user-callback",
        "keyring-supported": true
    },
    "host-setup": {
        "platform": "Linux-6.2.0-37-generic-x86_64-with-glibc2.35",
        "system": "Linux #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2",
        "OS": {
            "/etc/os-release": "Linux Mint 21.2",
            "/etc/lsb-release": "DISTRIB_ID=LinuxMint\nDISTRIB_RELEASE=21.2\nDISTRIB_CODENAME=victoria\nDISTRIB_DESCRIPTION=\"Linux Mint 21.2 Victoria\"\n",
            "/etc/debian_version": "bookworm/sid\n"
        },
        "display-system": "x11",
        "locale": "en_GB, UTF-8",
        "PATH": "/home/UsernameReplaced/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/UsernameReplaced/.local/bin",
        "RSYNC_OLD_ARGS": "(not set)",
        "RSYNC_PROTECT_ARGS": "(not set)"
    },
    "python-setup": {
        "python": "3.10.12 main Nov 20 2023 15:14:05 CPython GCC 11.4.0",
        "python-executable": "/usr/bin/python3",
        "python-executable-symlink": true,
        "python-executable-resolved": "/usr/bin/python3.10",
        "sys.path": [
            "/usr/share/backintime/qt/plugins",
            "/usr/share/backintime/common/plugins",
            "/usr/share/backintime/plugins",
            "/usr/share/backintime/common",
            "/usr/lib/python310.zip",
            "/usr/lib/python3.10",
            "/usr/lib/python3.10/lib-dynload",
            "/usr/local/lib/python3.10/dist-packages",
            "/usr/lib/python3/dist-packages",
            "/usr/lib/python3.10/dist-packages"
        ],
        "qt": {
            "Version": "PyQt 5.15.6 / Qt 5.15.3",
            "Theme": "Mint-Y",
            "Theme Search Paths": [
                "/home/UsernameReplaced/.icons",
                "/home/UsernameReplaced/.local/share/icons",
                "/usr/share/cinnamon/icons",
                "/var/lib/flatpak/exports/share/icons",
                "/usr/share/icons",
                ":/icons"
            ],
            "Fallback Theme": "",
            "Fallback Search Paths": []
        }
    },
    "external-programs": {
        "rsync": {
            "version": "3.2.7",
            "protocol": "31.0",
            "capabilities": {
                "file_bits": 64,
                "inum_bits": 64,
                "timestamp_bits": 64,
                "long_int_bits": 64,
                "socketpairs": true,
                "symlinks": true,
                "symtimes": true,
                "hardlinks": true,
                "hardlink_specials": true,
                "hardlink_symlinks": true,
                "IPv6": true,
                "atimes": true,
                "batchfiles": true,
                "inplace": true,
                "append": true,
                "ACLs": true,
                "xattrs": true,
                "secluded_args": "optional",
                "iconv": true,
                "prealloc": true,
                "stop_at": true,
                "crtimes": false
            },
            "optimizations": {
                "SIMD_roll": true,
                "asm_roll": false,
                "openssl_crypto": true,
                "asm_MD5": false
            },
            "checksum_list": [
                "xxh128",
                "xxh3",
                "xxh64",
                "md5",
                "md4",
                "sha1",
                "none"
            ],
            "compress_list": [
                "zstd",
                "lz4",
                "zlibx",
                "zlib",
                "none"
            ],
            "daemon_auth_list": [
                "sha512",
                "sha256",
                "sha1",
                "md5",
                "md4"
            ]
        },
        "ssh": "OpenSSH_8.9p1 Ubuntu-3ubuntu0.4, OpenSSL 3.0.2 15 Mar 2022",
        "sshfs": "3.7.1",
        "encfs": "1.9.5",
        "shell": "/bin/bash",
        "shell-version": "GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)"
    }
}
```

Additionally, please specify as precisely as you can the package or installation source where you got Back In Time from. Sometimes there are multiple alternatives, like in [for Arch-based distros](https://aur.archlinux.org/packages?K=backintime).
From PPA:
deb [signed-by=/etc/apt/keyrings/bit-team-stable-jammy.gpg] https://ppa.launchpadcontent.net/bit-team/stable/ubuntu jammy main

As an alternative fell free to use our mailing list for every topic about Back In Time. Visit the subscribtion page at https://mail.python.org/mailman3/lists/bit-dev.python.org or send an email with subject "Subscribe" to bit-dev-join@python.org.

One of my BIT profiles takes a snapshot every 30 minutes of a folder tree + files to which I have made no changes in the last 3 days, except as part of gathering data on this potential bug. The snapshot logs show just a single file - always the same file - as having changed. the file is locked; I do not have the key so I cannot change it. I have compared every copy of the file in the snapshot back with the first snapshot taken some days previously, using the 'diff' command. No change has been flagged. I have copied/pasted the snapshot log contents for the past few hours, during which time I took a copy of this one file and moved the original to the wastebin, to test if there was some property of the file which BIT keyed on. BIT has flagged the copy file as changing in the same way as the original. Here is a summary of the snapshot logs:

```
========== Take snapshot (profile 3): Tue Dec  5 09:00:01 2023 ==========

[C] cf...p..... home/tony/Documents/Bereavement matters/Financial Related/Fidelity/FILPaymentDetails.pdf

========== Take snapshot (profile 3): Tue Dec  5 10:00:01 2023 ==========

[C] cf...p..... home/tony/Documents/Bereavement matters/Financial Related/Fidelity/FILPaymentDetails.pdf

========== Take snapshot (profile 3): Tue Dec  5 11:00:01 2023 ==========

[C] cf...p..... home/tony/Documents/Bereavement matters/Financial Related/Fidelity/FILPaymentDetails.pdf

========== Take snapshot (profile 3): Tue Dec  5 14:30:01 2023 ==========

[C] cf...p..... home/tony/Documents/Bereavement matters/Financial Related/Fidelity/FILPaymentDetails.pdf

========== Take snapshot (profile 3): Tue Dec  5 15:00:02 2023 ==========

[C] >f+++++++++ home/tony/Documents/Bereavement matters/Financial Related/Fidelity/FILPaymentDetails (copy).pdf

========== Take snapshot (profile 3): Tue Dec  5 16:00:01 2023 ==========

[C] cf...p..... home/tony/Documents/Bereavement matters/Financial Related/Fidelity/FILPaymentDetails (copy).pdf

```

**Comment by buhtz** [comment] 2023-12-05 20:09
The `cf...p.....` indicates that something is about the permissions.

What files ystem do you use on your source and on your destination drive/volume?

Please show us the inode number of the `FILPaymentDetails.pdf` file in all your snapshots. I guest the following path. Please check it. Replace `BACKUPDESTINATION`. Keep the `*`.

    ls -li /home/user/BACKUPDESTINATION/.backintime/backintime/MS-7D15/tony/*/backup/home/tony/Documents/Bereavement matters/Financial Related/Fidelity/FILPaymentDetails.pdf

Please show us the original file.

    ls -l /home/tony/Documents/Bereavement matters/Financial Related/Fidelity/FILPaymentDetails.pdf

@bit-team Might this be something about our permission-bug-syndrome?

**Comment by LateJunction** [comment] 2023-12-05 21:24
File systems: Source: ext4; destination: ext4

    ls -li
    /home/tony/7D-Backup/.backintime/backintime/MS-7D15/tony/*/backup/home/tony/Documents/'Bereavement
    matters'/'Financial Related'/Fidelity/FILPaymentDetails.pdf - this location
    does not exist, but
    ls -li
    /media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231202-183002-241/backup/home/tony/Documents/'Bereavement
    matters'/'Financial Related'/Fidelity/FILPaymentDetails.pdf
     result is:
    42731460 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
    '/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231202-183002-241/backup/home/tony/Documents/Bereavement
    matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
    for the original file:
    ls -l /home/tony/Documents/'Bereavement matters'/'Financial
    Related'/Fidelity/FILPaymentDetails.pdf the result is:
    -r--rw-r-- 1 tony tony 49570 Nov  9 09:30 '/home/tony/Documents/Bereavement
    matters/Financial Related/Fidelity/FILPaymentDetails.pdf'

I hope this is what you wanted - my command line skills are limited

**Comment by buhtz** [comment] 2023-12-06 06:31
Please do not answer via mail but use the formatting options of Microsoft GitHub using code blocks. This makes it much easier for us to read your terminal output. Also please read what we write, here and on the mailing list. IT seems to me you don't carefully read what we write. We invest our spare time to help you here. So please take your time and read.
I wrote you should keep the `*` ( a wildcard).

Please try again and execute exactly this command on your machine and copy and paste the output as a code block (using the formatting options of GitHub!) here.

    ls -li /media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/*/backup/home/tony/Documents/'Bereavement matters'/'Financial Related'/Fidelity/FILPaymentDetails.pdf

**Comment by aryoda** [comment] 2023-12-06 08:22
May be related to issue #994

See the work-around described here:

https://github.com/bit-team/backintime#file-permissions-handling-and-therefore-possible-non-differential-backups

**Comment by emtiu** [comment] 2023-12-06 08:24
Yes, the file in question has permissions `-r--rw-r--`, so this is most certainly our bug #994.

It's a big one, and we have a plan in mind to fix it, but it's going to take some more time, I'm afraid.

**Comment by LateJunction** [comment] 2023-12-06 08:34
I now realise that this is what you requested:

ectory
***@***.***:~$ ls -li
/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/*/backup/home/tony/Documents/'Bereavement
matters'/'Financial Related'/Fidelity/FILPaymentDetails.pdf
42731460 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231202-183002-241/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42731542 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231202-193001-444/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42731625 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231202-203001-166/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42734920 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231202-213001-316/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42734997 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231202-223002-418/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42861146 -rw-rw-r-- 2 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231203-090001-969/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42861146 -rw-rw-r-- 2 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231203-093001-752/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42867716 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231203-130001-420/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42867798 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231203-140002-347/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42867883 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231203-150001-248/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
43152230 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231203-160001-192/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
43152312 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231203-170001-341/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
43152399 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231203-180002-553/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
43254472 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231203-190001-772/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
43254554 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231203-200001-642/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
43254642 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231203-210001-681/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
43154970 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231203-220001-414/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
43257984 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231204-090001-634/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42598430 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231204-100001-117/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42598516 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231204-110002-505/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42598604 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231204-120001-707/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42602115 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231204-130001-613/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42602201 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231204-140001-428/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42602289 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231204-150001-950/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42607129 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231204-160001-872/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42607215 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231204-170001-149/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42730062 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231204-190001-475/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42732434 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231204-200001-353/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42732514 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231204-210001-541/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
43123776 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231204-220002-842/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
43123864 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231205-090001-264/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42861228 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231205-100001-339/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42861313 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231205-110001-200/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
42864695 -r--rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231205-143001-623/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
43516642 -rw-rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231205-213001-506/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
43516687 -r--rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/20231206-083001-849/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'
43516687 -r--rw-r-- 1 tony tony 49570 Nov  9 09:30
'/media/tony/7D-Backup/backintime/MS-7D15/tony/bereavement/last_snapshot/backup/home/tony/Documents/Bereavement
matters/Financial Related/Fidelity/FILPaymentDetails.pdf'

**Comment by buhtz** [comment] 2023-12-06 12:11
Thanks for reporting back.

As @aryoda and @emtiu mentioned this is a known bug. See #994 and click there on the "Subscribe" button to keep yourself informed about further developments. Myself I am not deep enough into that bug to give you further advice.

After a cooling off period I would close this issue as a duplicate of #994.

**Closed as completed** 2024-01-09 15:04 UTC
Labels: Discussion, Bug
