### ISSUE TITLE
backintime don't see external disk

### ISSUE THREAD

**Issue by Lumaja** [bit-team/backintime#690] opened 2017-01-07 13:54 UTC
Back in Time Ver: 1.1.12
Ubuntu 16.04 LTS
Backup some directories from my main HDD to external HDD not successful, Backintime does not 
show the external drive on  “where to save the snapshot”.
Can you please help me to fix this and thank you.

**Comment by Germar** [comment] 2017-01-07 21:09
Please browse to `/media/<YOUR_USER>/<NAME_OF_EXTERNAL>`

**Comment by Lumaja** [comment] 2017-01-13 07:15
Thank you for the answer but still having problems as follows.
Backing up to external drive following you advice (my external has a long number). On Settings have a profile name, Where to Save Snapshot, (/media/<user>/<number>) go to Include Add folder then Click on OK nothing happens. When backing up to the main drive Clicking  on OK it opens the main page and from there click on Take Snapshot and it is done. Don't know why this happens I need some one to explain what I am doing wrong.
Thank you

**Comment by Germar** [comment] 2017-01-14 17:36
`/media//` ? Your external should be a subfolder of `/media`

Please open a Terminal, run `backintime-qt4 --debug`, configure your profile again and post the output from Terminal if it fails again. Sounds like there is a bug...

**Comment by Lumaja** [comment] 2017-01-15 06:06
There is two profiles in Backintime one is “Main Profile” the other is one I was trying and was successful but I deleted from the drive, removing the profiles is never complete removed they 
come back again when open Settings how is that.
Terminal:
luis@luis-Ubuntu-16:~$ backintime-qt4 --debug
DEBUG: [common/backintime.py:509 arg_parse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.1.12

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:576 getConfig] config file: /home/luis/.config/backintime/config
DEBUG: [common/backintime.py:577 getConfig] profiles: ['1', '2']
DEBUG: [common/pluginmanager.py:88 PluginManager.load_plugins] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin qt4plugin.py
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin userscriptsplugin.py
DEBUG: [common/snapshots.py:774 Snapshots.get_snapshots_list] Failed to get snapshots list: [Errno 2] No such file or directory: '/media/luis/0c0645d8-d5c9-4791-98ff-c7527084f33c/home/luis/BackTime - 2 TRY/backintime'
DEBUG: [common/snapshots.py:947 Snapshots.has_old_snapshots] Found old snapshots: False
DEBUG: [common/tools.py:611 keyring_supported] Found appropriate keyring 'keyring.backends.SecretService'
DEBUG: [common/mount.py:50 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:59 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
ERROR: [common/config.py:1330 Config.can_backup] /media/luis/0c0645d8-d5c9-4791-98ff-c7527084f33c/home/luis/BackTime - 2 TRY/backintime/luis-Ubuntu-16/luis/1 does not exist
DEBUG: [common/snapshots.py:804 Snapshots.get_snapshots_and_other] Failed to get snapshots list: [Errno 2] No such file or directory: '/media/luis/0c0645d8-d5c9-4791-98ff-c7527084f33c/home/luis/BackTime - 2 TRY/backintime/luis-Ubuntu-16/luis/1'
DEBUG: [common/tools.py:611 keyring_supported] Found appropriate keyring 'keyring.backends.SecretService'
DEBUG: [common/tools.py:611 keyring_supported] Found appropriate keyring 'keyring.backends.SecretService'
DEBUG: [common/tools.py:611 keyring_supported] Found appropriate keyring 'keyring.backends.SecretService'
DEBUG: [common/configfile.py:476 Config.set_current_profile] change current profile: 2
DEBUG: [common/configfile.py:476 Config.set_current_profile] change current profile: 2
DEBUG: [common/config.py:375 Config.set_snapshots_path] Check snapshot folder: /media/luis/External01
DEBUG: [common/config.py:385 Config.set_snapshots_path] Create folder: /media/luis/External01/backintime/Ubuntu-16/luis/1
Traceback (most recent call last):
  File "/usr/share/backintime/common/tools.py", line 189, in make_dirs
    os.makedirs( path )
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/media/luis/External01/backintime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/qt4/settingsdialog.py", line 1698, in accept
    if self.validate():
  File "/usr/share/backintime/qt4/settingsdialog.py", line 1452, in validate
    if not self.save_profile():
  File "/usr/share/backintime/qt4/settingsdialog.py", line 1351, in save_profile
    ret = self.config.set_snapshots_path( snapshots_path, mode = mode )
  File "/usr/share/backintime/common/config.py", line 386, in set_snapshots_path
    tools.make_dirs( full_path )
  File "/usr/share/backintime/common/tools.py", line 192, in make_dirs
    %(path, str(e)), self, 1)
NameError: name 'self' is not defined
DEBUG: [common/configfile.py:476 Config.set_current_profile] change current profile: 1

**Comment by Germar** [comment] 2017-01-15 17:09
Okay, this is a known bug in `1.1.12`. Please update to current dev version `1.2.0~alpha`. It's fixed in there.
```
sudo add-apt-repository ppa:bit-team/testing
sudo apt-get update
sudo apt-get upgrade
```

You also need to fix permissions in `/media/luis/External01`. Your user currently has no write access.
```
sudo chown luis /media/luis/External01
sudo chmod 755 /media/luis/External01
```

**Comment by Germar** [comment] 2017-01-15 17:12
Duplicate of #622

**Closed by Germar** 2017-01-15 17:12 UTC
Labels: duplicate

**Comment by Lumaja** [comment] 2017-01-16 13:15
It is working thank you for the help.
I have few other issues than needs fixing. When I was getting familiar with the program made few profiles and they never get complete removed how can I remove them?
The other is a backup has a lot sub folders my last one has 10 cant it be shorter ?
On “Main Profile” “Where to save snapshots” I have this entry /media/luis/0c0645d8-d5c9-4791-98ff-c7527084f33c/home/luis/BackTime - 2 TRY. How to delete this?

**Comment by Germar** [comment] 2017-01-16 19:48
> When I was getting familiar with the program made few profiles and they never get complete removed how can I remove them?

In `Settings` at the top there are three buttons beside the profile drop-down: `Edit`, `Add` and `Remove`. Just choose the profile you want to remove and press `Remove`

> The other is a backup has a lot sub folders my last one has 10 cant it be shorter ?

If you are talking about `/path/to/backintime/<HOST>/<USER>/<PROFILE_ID>/<SNAPSHOT_ID>/backup/` than no. You can add a symlink to the snapshots path if you want to go there quicker.

> On “Main Profile” “Where to save snapshots” I have this entry /media/luis/0c0645d8-d5c9-4791-98ff-c7527084f33c/home/luis/BackTime - 2 TRY. How to delete this?

What do you mean with delete? You can choose a different destination for the profile, but you can't remove "Main Profile" at all.
