### ISSUE TITLE
Restore Fails on 20.04 with rsync error (code 23)

### ISSUE THREAD

**Issue by bit-user** [bit-team/backintime#1075] opened 2020-04-25 19:29 UTC
I just installed the current Xubuntu 20.04 and tried to restore my backup from my backintime backup via sshfs.
Unfortunately, this failed. I checked the full log in `/home/user/.local/share/backintime/restore_3.log`

It has about 450k lines, where the most important ones are:

    receiving file list ... done
    rsync: failed to set times on "/home": Operation not permitted (1)
    home/
    home/user/
    home/user/.ICEauthority
    [... 450k lines of restored files ...]
    sent 7.47M bytes  received 464.32G bytes  47.33M bytes/sec
    total size is 464.22G  speedup is 1.00
    rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1677) [generator=3.1.3]
     
     
    Restore permissions:
    chmod /home/user/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml 100644
    chmod /home/user/.config/xfce4/xfconf/xfce-perchannel-xml/thunar.xml 100644
    
    Restore permissions: Done

Some questions I have:

 1. Is the only error that backintime couldn't set attributes on /home?
 2. If yes to 1): Why would backintime set attributes on /home? I backupped /home/user/
 3. If no: How do I find missing files and attributes? I searched for 'error' and 'fail' in the aforementioned log, without success.
 4. received 464.32G vs. total size is 464.22G. Why?
 5. Backintime didn't finish. It was just at 99% for some time when I lost patience and closed it. How do I know, if it was finished?
 6. And finally: I was unable to add the ppa and find backintime-gnome. Is this gone for the sake of qt4?

Thanks!

**Comment by deprecated-github-account** [comment] 2022-08-23 20:35
Did you restore from root? Please see https://github.com/bit-team/backintime/issues/1273#issuecomment-1224387163 and following comment https://github.com/bit-team/backintime/issues/1273#issuecomment-1224835583.

**Comment by deprecated-github-account** [comment] 2022-08-24 05:47
Closing this issue since it seems to be a duplicate of #1273.

**Closed** 2022-08-29 21:26 UTC
