### ISSUE TITLE
backintime 1.2.1 "reentrant call inside"

### ISSUE THREAD

**Issue by michaelof** [bit-team/backintime#1177] opened 2021-07-08 11:21 UTC
New openSUSE issue for this is https://bugzilla.opensuse.org/show_bug.cgi?id=1188115

Upgraded openSUSE Leap from 15.2 to 15.2, means backintime from 1.1.24 to 1.2.1
backintime does NOT work anymore, starts etc., but can't finalize a snapshot. 

Reproducible error on command line (bash) is:
```
INFO: Remove leftover 'new_snapshot' folder from last run
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
INFO: Call rsync to take the snapshot
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1165, in <module>
    startApp()
  File "/usr/share/backintime/common/backintime.py", line 517, in startApp
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 739, in backup
    ret = takeSnapshot(cfg, force)
  File "/usr/share/backintime/common/backintime.py", line 94, in takeSnapshot
    ret = snapshots.Snapshots(cfg).backup(force)
  File "/usr/share/backintime/common/snapshots.py", line 692, in backup
    ret_val, ret_error = self.takeSnapshot(sid, now, include_folders)
  File "/usr/share/backintime/common/snapshots.py", line 1036, in takeSnapshot
    proc.run()
  File "/usr/share/backintime/common/tools.py", line 1981, in run
    self.callback(line, self.user_data)
  File "/usr/share/backintime/common/snapshots.py", line 809, in rsyncCallback
    self.snapshotLog.append('[C] ' + line[12:], 2)
  File "/usr/share/backintime/common/snapshotlog.py", line 195, in append
    self.logFile.write(msg + '\n')
  File "/usr/share/backintime/common/tools.py", line 1513, in handler
    self.callback()
  File "/usr/share/backintime/common/snapshotlog.py", line 203, in flush
    self.logFile.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/root/.local/share/backintime/takesnapshot_.log'>
```

**Comment by buhtzz** [comment] 2022-09-25 12:08
The distro bug is closed.
The bug is outdated and not reproducible with newer versions of BIT.
Close.

**Comment by emtiu** [comment] 2022-09-25 16:19
It seems like the same error also occurs on more modern distros with the latest BiT version. Closing as a duplicate of #1003.

**Closed by emtiu** 2022-09-25 16:19 UTC
