### ISSUE TITLE
Smart remove doesn't work proparly all the time

### ISSUE THREAD

**Issue by codesmaker** [bit-team/backintime#586] opened 2016-06-13 13:22 UTC
First of all, let me thank you all of this awesome backup software. You made the life of so many people much easier.

On one of my computer, "working: smart remove" keeps showing in the status bar (on the left bottom of backintime window). The backups work OK but smart remove doesn't remove the snapshots as configured. I have two profiles on the same PC, one works OK which backup my home directory and the other one doesn't and it hangs which backups the whole system. I also use "run in backgroud on remote host. EXPERIMENTAL!". To be honest, I don't know how to start debugging and where should I start. Could you please enlighten me with what should I do?

**Comment by Germar** [comment] 2016-06-14 12:17
Sounds like a duplicate of #581. Can you confirm this?

**Comment by codesmaker** [comment] 2016-06-15 12:34
Thanks a lot Germar! It indeed was. I've just increased "snapshots.ssh.max_arg_length" in "~/.config/backintime/config" and it worked. I also couldn't be able to change any settings for that profile. This also solved it. I'm not sure why there was a problem with this profile in particular.

**Comment by Germar** [comment] 2016-06-17 20:03
Thanks for the feedback.

**Closed by Germar** 2016-06-17 20:03 UTC
Labels: duplicate
