### ISSUE TITLE
BIT bottom status line unreadable

### ISSUE THREAD

**Issue by MatNieuw** [bit-team/backintime#868] opened 2018-02-04 20:20 UTC
System Mint 18.3 Xfce, BIT 1.1.12 .
While BIT is running, the bottom status line is a very dark blue. It could be there is black text is there, but I just cannot make it out. I have a very good monitor, changing Xfce settings don´t seem to make a difference to this bottom line. After the backup has finished, the bottom line becomes a light color and there is text visible.
Maybe the bottom line could be made light green or something else that makes text visible?
Even, if it displays progress lines as enter up in the log (I cannot see what it does right now), change the color to red for error lines?

**Comment by Germar** [comment] 2018-02-05 19:46
duplicate of #612

**Closed by Germar** 2018-02-05 19:46 UTC
