### ISSUE TITLE
backintime crashes on an unchanged source directory

### ISSUE THREAD

**Issue by Abelian-grape** [bit-team/backintime#844] opened 2017-12-06 02:28 UTC
How to avoid this?

**Comment by Germar** [comment] 2017-12-06 22:16
Please run `backintime --debug backup` in Terminal and post the output

**Comment by Abelian-grape** [comment] 2017-12-07 03:10
`Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:585 getConfig] config file: /.autofs/home/nho/Desktop/arcdir/default_config_shared
DEBUG: [common/backintime.py:586 getConfig] profiles: ['1']
DEBUG: [common/pluginmanager.py:88 PluginManager.load_plugins] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin qt4plugin.py
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin userscriptsplugin.py
DEBUG: [common/snapshots.py:953 Snapshots.has_old_snapshots] Found old snapshots: False
DEBUG: [common/applicationinstance.py:73 ApplicationInstance.check] No PID file
DEBUG: [common/applicationinstance.py:73 ApplicationInstance.check] No PID file
INFO: [common/snapshots.py:991 Snapshots.take_snapshot] Lock
INFO: [common/tools.py:808 inhibitSuspend] Inhibit Suspend started. Reason: take snapshot
DEBUG: [common/tools.py:616 keyring_supported] Found appropriate keyring 'keyring.backends.SecretService'
DEBUG: [common/applicationinstance.py:73 ApplicationInstance.check] No PID file
DEBUG: [common/mount.py:50 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:59 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
INFO: [common/snapshots.py:1024 Snapshots.take_snapshot] Take a new snapshot. Profile: 1 Main profile
INFO: [common/snapshots.py:1339 Snapshots._take_snapshot] Call rsync to take the snapshot
DEBUG: [common/snapshots.py:1357 Snapshots._take_snapshot] Call command "rsync -rtDHh --checksum --links -pEgo --info=progress2 --no-i-r  --delete --delete-excluded  -v  --chmod=Du+wx  --exclude="/.autofs/home/nho/Desktop/arcdir" --exclude="/home/nho/.local/share/backintime" --exclude=".local/share/backintime/mnt" --include="/.autofs/home/nho/Desktop/testdir/" --include="/.autofs/home/nho/Desktop/" --include="/.autofs/home/nho/" --include="/.autofs/home/" --include="/.autofs/" --exclude="/.autofs/home/nho/Desktop/arcdir" --exclude=".cache/*" --exclude=".thumbnails*" --exclude="[Tt]rash*" --exclude="*.backup*" --exclude="*~" --exclude=".dropbox*" --exclude="/proc/*" --exclude="/sys/*" --exclude="/dev/*" --exclude="/run/*" --exclude="/etc/mtab" --exclude="/var/cache/apt/archives/*.deb" --exclude="lost+found/*" --exclude="/tmp/*" --exclude="/var/tmp/*" --exclude="/var/backups/*" --exclude=".Private" --include="/.autofs/home/nho/Desktop/testdir/**" --exclude="*" / "/.autofs/home/nho/Desktop/arcdir/backintime/archive/bsp/1/new_snapshot/backup/" --link-dest="../../20171206-220641-988/backup" -i --out-format="BACKINTIME: %i %n%L" 2>&1"
DEBUG: [common/snapshots.py:1357 Snapshots._take_snapshot] Command "rsync -rtDHh --c..." returns 0
DEBUG: [common/snapshots.py:1363 Snapshots._take_snapshot] Failed to remove snapshot progress file /home/nho/.local/share/backintime/worker.progress: [Errno 2] No such file or directory: '/home/nho/.local/share/backintime/worker.progress'
DEBUG: [common/snapshots.py:1384 Snapshots._take_snapshot] Call command "find "/.autofs/home/nho/Desktop/arcdir/backintime/archive/bsp/1/new_snapshot" -type d -exec chmod u+wx "{}" +"
DEBUG: [common/snapshots.py:1384 Snapshots._take_snapshot] Command "find "/.autofs/h..." returns 0
DEBUG: [common/snapshots.py:1385 Snapshots._take_snapshot] Call command "rm -rf "/.autofs/home/nho/Desktop/arcdir/backintime/archive/bsp/1/new_snapshot""
DEBUG: [common/snapshots.py:1385 Snapshots._take_snapshot] Command "rm -rf "/.autofs..." returns 0
INFO: [common/snapshots.py:1387 Snapshots._take_snapshot] Nothing changed, no back needed
DEBUG: [common/snapshots.py:1053 Snapshots.take_snapshot] Call command "rm -rf "/.autofs/home/nho/Desktop/arcdir/backintime/archive/bsp/1/20171206-220647-515""
DEBUG: [common/snapshots.py:1053 Snapshots.take_snapshot] Command "rm -rf "/.autofs..." returns 0
INFO: [common/snapshots.py:1672 Snapshots._free_space] Remove backups older than: 20071201-000000
INFO: [common/snapshots.py:1702 Snapshots._free_space] Keep min free disk space: 1024 MiB
INFO: [common/snapshots.py:1735 Snapshots._free_space] Keep min 2% free inodes
DEBUG: [common/snapshots.py:1987 Snapshots.create_last_snapshot_symlink] Create symlink /.autofs/home/nho/Desktop/arcdir/backintime/archive/bsp/1/last_snapshot => 20171206-220641-988
DEBUG: [common/tools.py:616 keyring_supported] Found appropriate keyring 'keyring.backends.SecretService'
DEBUG: [common/applicationinstance.py:73 ApplicationInstance.check] No PID file
DEBUG: [common/mount.py:50 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:59 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
INFO: [common/snapshots.py:1091 Snapshots.take_snapshot] Unlock
INFO: [common/tools.py:827 unInhibitSuspend] Release inhibit Suspend
INFO: [qt4systrayicon] begin loop
INFO: [qt4systrayicon] end loop
backintime --debug --config /.autofs/home/nho/Desktop/arcdir/default_config_shared backup failed:`

**Comment by Abelian-grape** [comment] 2017-12-07 03:11
Thanks for the reply! This is the second invocation.

**Comment by Germar** [comment] 2017-12-07 22:46
Sorry, but I don't see a crash in there. Only the last line `backintime [...] failed:` is unusual. Does your shell create this line? It doesn't come from BiT...

Does it return an errorcode <> 0? Please run `backintime backup; echo $?` last line should be `0`

**Comment by buhtzz** [comment] 2022-09-25 08:03
@Abelian-grape There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback

**Comment by emtiu** [comment] 2022-10-22 16:21
Closing as outdated, reporter not responding, cannot reproduce.

**Closed by emtiu** 2022-10-22 16:21 UTC
