### ISSUE TITLE
Snapshot logs do not contain file deletions

### ISSUE THREAD

**Issue by TimGS** [bit-team/backintime#1263] opened 2022-06-30 20:30 UTC
1. Create a file 'foo'. Take a snapshot.
2. Delete 'foo'. Try to take a snapshot. BiT refuses and reports nothing changed.
3. Create a file 'bar'. Take a snapshot. The snapshot _log_ will include the new file 'bar', but not the deletion of 'foo'.

The contents of each snapshot as per the right hand side of the GUI, appear to be correct. File 'foo' is not seen in the snapshot taken in step 3.

BiT 1.2.1 on Debian 11 Bullseye.

BiT on Debian 10 Buster (possibly 1.1.24?) correctly included deletions in the log. I also _think_, but am not certain, that deletions were enough for BiT to save another snapshot, unlike the behaviour in step 2 above.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment] 2022-08-25 15:06
I also observed that in some situations but didn't analysed it yet. Seems to be an **urgent** problem that was introduced somewhere between 1.1.* and 1.2.*.

**Comment by emtiu** [comment] 2022-09-12 14:13
This might be related to #136, but I'm not sure yet.

**Comment by emtiu** [comment] 2022-10-07 22:36
Closing as duplicate of #136.

**Closed by emtiu** 2022-10-07 22:36 UTC
Labels: High, Reproduced, Bug
