### ISSUE TITLE
Unable to run backintime via x11

### ISSUE THREAD

**Issue by philm001** [bit-team/backintime#1720] opened 2024-05-13 03:09 UTC
Hello everyone, I am unable to run backintime through x-11. This is really unfortunate because it would give us headless users a nice way to work with this program. I am adding the output of the command here. I should note, that I am pretty sure I have the authorization correct for what I am doing

```
Back In Time
Version: 1.4.1-1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

MoTTY X11 proxy: Unsupported authorisation protocol
qt.qpa.xcb: could not connect to display localhost:10.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
```
Here is an output of the diagnostics:

```
{
    "backintime": {
        "name": "Back In Time",
        "version": "1.4.1-1",
        "latest-config-version": 6,
        "local-config-file": "/root/.config/backintime/config",
        "local-config-file-found": false,
        "global-config-file": "/etc/backintime/config",
        "global-config-file-found": false,
        "started-from": "/usr/share/backintime/common",
        "running-as-root": true,
        "user-callback": "/root/.config/backintime/user-callback",
        "keyring-supported": false
    },
    "host-setup": {
        "platform": "Linux-5.15.0-106-generic-x86_64-with-glibc2.35",
        "system": "Linux #116-Ubuntu SMP Wed Apr 17 09:17:56 UTC 2024",
        "OS": {
            "/etc/os-release": "Ubuntu 22.04.4 LTS",
            "/etc/lsb-release": "DISTRIB_ID=Ubuntu\nDISTRIB_RELEASE=22.04\nDISTRIB_CODENAME=jammy\nDISTRIB_DESCRIPTION=\"Ubuntu 22.04.4 LTS\"\n",
            "/etc/debian_version": "bookworm/sid\n"
        },
        "display-system": "($XDG_SESSION_TYPE not set)",
        "locale": "en_US, UTF-8",
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin",
        "RSYNC_OLD_ARGS": "(not set)",
        "RSYNC_PROTECT_ARGS": "(not set)"
    },
    "python-setup": {
        "python": "3.10.12 main Nov 20 2023 15:14:05 CPython GCC 11.4.0",
        "python-executable": "/usr/bin/python3",
        "python-executable-symlink": true,
        "python-executable-resolved": "/usr/bin/python3.10",
        "sys.path": [
            "/usr/share/backintime/qt/plugins",
            "/usr/share/backintime/common/plugins",
            "/usr/share/backintime/plugins",
            "/usr/share/backintime/common",
            "/usr/share/backintime/qt",
            "/usr/lib/python310.zip",
            "/usr/lib/python3.10",
            "/usr/lib/python3.10/lib-dynload",
            "/usr/local/lib/python3.10/dist-packages",
            "/usr/lib/python3/dist-packages"
        ],
        "qt": {
            "Version": "PyQt 5.15.6 / Qt 5.15.3"
        }
    },
    "external-programs": {
        "rsync": {
            "version": "3.2.7",
            "protocol": "31.0",
            "capabilities": {
                "file_bits": 64,
                "inum_bits": 64,
                "timestamp_bits": 64,
                "long_int_bits": 64,
                "socketpairs": true,
                "symlinks": true,
                "symtimes": true,
                "hardlinks": true,
                "hardlink_specials": true,
                "hardlink_symlinks": true,
                "IPv6": true,
                "atimes": true,
                "batchfiles": true,
                "inplace": true,
                "append": true,
                "ACLs": true,
                "xattrs": true,
                "secluded_args": "optional",
                "iconv": true,
                "prealloc": true,
                "stop_at": true,
                "crtimes": false
            },
            "optimizations": {
                "SIMD_roll": true,
                "asm_roll": false,
                "openssl_crypto": true,
                "asm_MD5": false
            },
            "checksum_list": [
                "xxh128",
                "xxh3",
                "xxh64",
                "md5",
                "md4",
                "sha1",
                "none"
            ],
            "compress_list": [
                "zstd",
                "lz4",
                "zlibx",
                "zlib",
                "none"
            ],
            "daemon_auth_list": [
                "sha512",
                "sha256",
                "sha1",
                "md5",
                "md4"
            ]
        },
        "ssh": "OpenSSH_8.9p1 Ubuntu-3ubuntu0.6, OpenSSL 3.0.2 15 Mar 2022",
        "sshfs": "3.7.1",
        "encfs": "1.9.5",
        "shell": "/bin/bash",
        "shell-version": "GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)"
    }
}



```
If you need anything else or need me to check anything, please let me know.

This is my xauth values:

```
localhost/unix:10  MIT-MAGIC-COOKIE-1  27e035688dd89483c6fe48b2470172f5
<Server_Name>:10  MIT-MAGIC-COOKIE-1  27e035688dd89483c6fe48b2470172f5
192.168.68.53/unix:10  MIT-MAGIC-COOKIE-1  27e035688dd89483c6fe48b2470172f5
<Server_Name>/unix:10  MIT-MAGIC-COOKIE-1  e52026058cc1dc0e4c2818ed13f461a8
```

**Comment by buhtz** [comment] 2024-05-13 05:26
Hello Phillip,

Thank you for taking the time to report the bug and providing the
details. I appreciate your feedback.

Can you describe please in more details what "through x-11" means. I see "MoTTY" in your output. Might this be some kind of remote desktop setup like VNC or XRDP?

In this case I would suggest to ask the community of your client first and provide the same details. They might have an idea what could be the cause.

btw: I don't have problems running BIT via XRDP (using "Windows Remote Desktop" as client) on Debian 11 and 12.

Best regards,
Christian

**Comment by aryoda** [comment] 2024-05-13 07:47
@philm001

Are you using [MobaXterm](https://mobaxterm.mobatek.net/) for X11-forwarding?

I don't know if X11-forwarding with BiT GUI was ever tested or reported as working.

> This is my xauth values:

Is "my" a normal user or `root`?

**Comment by Martii** [comment] 2024-05-13 09:11
> I don't know if X11-forwarding with BiT GUI was ever tested ...

Not sure if this is what is being looked for but this seems to load and pull up my existing snapshots:
``` console
$ ssh -CX machine.localdomain /usr/bin/backintime-qt
```

That target machine is "headless" when it comes to hardware i.e. no monitor *(except when selected with a KVM)* but still has the same distro Windows Manager installed. I usually use VNC though as it is "detachable" i.e. continues to run when host system is rebooted or otherwise busy. The BiT GUI *(Qt)* in general looks a bit different on fonts/button images... might be applying the default KDE theme instead of my distros.

**Comment by ptilopteri** [comment] 2024-05-13 12:33
* Marti Martz ***@***.***> [05-13-24 05:12]:
> > I don't know if X11-forwarding with BiT GUI was ever tested ...
> 
> Not sure if this is what is being looked for but this seems to load and pull up my existing snapshots:
> ``` console
> $ ssh -CX machine.localdomain /usr/bin/backintime-qt
> ```
> 
> That target machine is "headless" when it comes to hardware i.e. no monitor *(except when selected with a KVM)* but still has the same distro Windows Manager installed. I usually use VNC though as it is "detachable" i.e. continues to run when host system is rebooted or otherwise busy. The BiT GUI *(Qt)* in general looks a bit different on fonts/button images... might be applying the default KDE theme instead of my distros.

confirm, has worked for me for many years
openSUSE Tumbleweed

-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by philm001** [comment] 2024-05-13 15:17
Hello guys thank you for feedback. I was able to get things working on the CLI (I would suggest some more up to date documentation on the CLI part). However, I think that having a good way to use X11 is beneficial. 

@aryoda 

Yes, I am using that. I can run the X11 apps like the clock and the eyes without issue. I only have a problem with BiT. I haven't tried using vnc or XRDP. I will give those a shot later and see if it might be an issue with Mobaxterm. I am pretty sure those are under a normal user and I actually have both. But will need to double check that

**Comment by buhtz** [comment] 2024-05-13 18:49
Thanks for your feedback.

> I would suggest some more up to date documentation on the CLI part).

Please be more specific here. Otherwise we are not able to improve it. Which part of the docu you are refer to? The manpage, the user manual, something else? What could be improved or what is hard to understand?

**Comment by buhtz** [comment] 2024-06-17 07:19
Hello Folks,
seems the problem was solved. But not sure how.
Can we learn something here? Can we somehow improve the documentation or the behavior of BIT to prevent situations like this in the future? We are open for feedback.

Thanks,
Christian

**Comment by buhtz** [comment] 2024-06-30 06:51
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,

**Closed as completed by buhtz** 2024-06-30 06:51 UTC
Labels: Qt, Bug, Feedback
