### ISSUE TITLE
Suggesting additional default exclusions

### ISSUE THREAD

**Issue by DonEdwards** [bit-team/backintime#1844] opened 2024-08-19 09:14 UTC
I unwittingly tried to back up my system while my backup drive was mounted in two places (no clue how or why) - and one of them was in the scope of the backup job.

As a result, I spent most of the day fighting with an overflowing btrfs partition. But finally got it straightened out.

And in the process thought it would be smart to, by default, NOT back up:
- /media/*
- backups made by various backup programs, e.g. */timeshift/*/backup or */backintime/*/*/*/*/backup
- (maybe) /mnt/*/* (or provide a checkbox for rsync's -x option)

**Comment by buhtz** [comment] 2024-08-19 09:22
Hello Don,

Thank you for taking the time to report the bug and providing the details. I appreciate your feedback, will investigate the issue.

> my backup drive was mounted in two places (no clue how or why) - and one of them was in the scope of the backup job.

Do you mean that the backup was backing up itself? I would like to investigate this further because BIT should be able to encounter such situations. Can you reproduce this somehow and give me more details?

About the suggested default exclude. Requests like this often come up by users from time to time. They might make sense in the use case and environment of that users but not in others. I can imagine good reasons why someone want to use "mnt" and "media" as a backup source and also foreign backup folders like "timeshift". There are really folks out there backing up backups their backups. 😄 

But I am interested in your use case, too. Can you give more more details about your snapshot path and include folders, please?

If you have any more details to share, feel free to reach out.

Best regards,

**Comment by buhtz** [comment] 2024-09-16 12:10
Hello Don,
would you like to add some more details to your report and answer the questions? Otherwise I am not able to go further on this issue and need to close it.

Best regards,
Christian

**Comment by buhtz** [comment] 2024-09-25 09:26
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,

**Closed as completed by buhtz** 2024-09-25 09:26 UTC
Labels: Feedback
