### ISSUE TITLE
Malformed config file makes BiT backuping the entire system

### ISSUE THREAD

**Issue by Yvan-Masson** [bit-team/backintime#752] opened 2017-04-28 08:16 UTC
Hi,

I use BiT on a headless server, so I manually created /etc/backintime/config from scratch. I noticed that small mistakes in this file makes BiT backup the whole "/".

Here is an example (the second "include" number should be "2" to be correct):
```
profiles=1
profile1.name=test
profile1.snapshots.mode=local
profile1.snapshots.include.1.value=/home/ymasson/Desktop
profile1.snapshots.include.1.value=/home/ymasson/Images
profile1.snapshots.include.size=2
profile1.snapshots.path=/home/ymasson/Bureau
profile1.snapshots.notify.enabled=false
```
The output:
```
$ backintime backup --profile test --config ~/foo --debug
DEBUG: [common/backintime.py:509 arg_parse] Arguments: {'profile': 'test', 'command': 'backup', 'config': '/home/ymasson/foo', 'func': <function backup at 0x7fa3c51f2488>, 'debug': True} | unknownArgs: []

Back In Time
Version: 1.1.12

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:576 getConfig] config file: /home/ymasson/foo
DEBUG: [common/backintime.py:577 getConfig] profiles: ['1']
DEBUG: [common/configfile.py:495 Config.set_current_profile_by_name] change current profile: test
DEBUG: [common/pluginmanager.py:88 PluginManager.load_plugins] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin userscriptsplugin.py
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin qt4plugin.py
DEBUG: [common/snapshots.py:947 Snapshots.has_old_snapshots] Found old snapshots: False
INFO: [common/snapshots.py:985 Snapshots.take_snapshot] Lock
INFO: [common/tools.py:803 inhibitSuspend] Inhibit Suspend started. Reason: take snapshot
DEBUG: [common/tools.py:611 keyring_supported] Found appropriate keyring 'keyring.backends.SecretService'
DEBUG: [common/mount.py:50 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:59 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
INFO: [common/snapshots.py:1018 Snapshots.take_snapshot] Take a new snapshot. Profile: 1 test
INFO: [common/snapshots.py:1187 Snapshots._take_snapshot] Found leftover 'new_snapshot' which can be continued.
DEBUG: [common/snapshots.py:1192 Snapshots._take_snapshot] Call command "find "/home/ymasson/Bureau/backintime/dell-e6400/ymasson/1/new_snapshot" -type d -exec chmod u+wx "{}" +"
DEBUG: [common/snapshots.py:1192 Snapshots._take_snapshot] Command "find "/home/ymas..." returns 0
INFO: [common/snapshots.py:1333 Snapshots._take_snapshot] Call rsync to take the snapshot
DEBUG: [common/snapshots.py:1351 Snapshots._take_snapshot] Call command "rsync -rtDHh --links --no-p --no-g --no-o --info=progress2 --no-i-r  --delete --delete-excluded  -v  --chmod=Du+wx  --exclude="/home/ymasson/Bureau" --exclude="/home/ymasson/.local/share/backintime" --exclude=".local/share/backintime/mnt" --include="/home/ymasson/Images/" --include="/home/ymasson/" --include="/home/" --include="/" --exclude=".gvfs" --exclude=".cache/*" --exclude=".thumbnails*" --exclude="[Tt]rash*" --exclude="*.backup*" --exclude="*~" --exclude=".dropbox*" --exclude="/proc/*" --exclude="/sys/*" --exclude="/dev/*" --exclude="/run/*" --exclude="/etc/mtab" --exclude="/var/cache/apt/archives/*.deb" --exclude="lost+found/*" --exclude="/tmp/*" --exclude="/var/tmp/*" --exclude="/var/backups/*" --exclude=".Private" --include="/home/ymasson/Images/**" --include="/**" --exclude="*" / "/home/ymasson/Bureau/backintime/dell-e6400/ymasson/1/new_snapshot/backup/" 2>&1"
notify-send  "Back In Time (ymasson) : test" "Error: rsync: opendir "/boot/lost+found" failed: Permission denied (13)"
notify-send  "Back In Time (ymasson) : test" "Error: rsync: opendir "/etc/lvm/backup" failed: Permission denied (13)"
notify-send  "Back In Time (ymasson) : test" "Error: rsync: opendir "/etc/ssl/private" failed: Permission denied (13)"
notify-send  "Back In Time (ymasson) : test" "Error: rsync: opendir "/etc/polkit-1/localauthority" failed: Permission denied (13)"
notify-send  "Back In Time (ymasson) : test" "Error: rsync: opendir "/etc/cups/ssl" failed: Permission denied (13)"
notify-send  "Back In Time (ymasson) : test" "Error: rsync: opendir "/var/lib/apt/lists/partial" failed: Permission denied (13)"
Gtk-Message: Failed to load module "canberra-gtk-module"
INFO: [qt4systrayicon] begin loop
^CTraceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 865, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 450, in start_app
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 626, in backup
    ret = take_snapshot(cfg, force)
  File "/usr/share/backintime/common/backintime.py", line 70, in take_snapshot
    ret = snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/usr/share/backintime/common/snapshots.py", line 1044, in take_snapshot
    ret_val, ret_error = self._take_snapshot( snapshot_id, now, include_folders )
  File "/usr/share/backintime/common/snapshots.py", line 1351, in _take_snapshot
    self._execute( cmd + ' 2>&1', self._exec_rsync_callback, params, filters = (self._filter_rsync_progress, ))
  File "/usr/share/backintime/common/snapshots.py", line 1799, in _execute
    line = tools.temp_failure_retry( pipe.readline )
  File "/usr/share/backintime/common/tools.py", line 494, in temp_failure_retry
    return func(*args, **kwargs)
KeyboardInterrupt
```
In my opinion, BiT should complain and return an error before trying to backup "/".

Many thanks for your work,
Yvan

**Comment by Germar** [comment] 2017-05-02 20:06
This is a duplicate of #521 an has been fixed in 1.2.0

**Closed by Germar** 2017-05-02 20:06 UTC
Labels: config, duplicate
