### ISSUE TITLE
"Delete new files" not deleting a newly created folder in source (Restore)

### ISSUE THREAD

**Issue by frank777777777** [bit-team/backintime#877] opened 2018-03-11 04:53 UTC
OS: openSUSE Tumbleweed.
In the GUI tool. I did an entire file system snapshot. 
And then I created a random folder "foo" under "/usr". After using option 6, Restore "/" and delete new files, the folder is still there. 
While I manually select all folders under "/", use option 5, restore and delete new files, the folder "foo" is deleted.
Is this a bug or intended?

**Comment by buhtzz** [comment] 2022-09-25 08:31
@frank777777777 There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback

**Comment by emtiu** [comment] 2022-10-22 16:24
Needs testing, could be a bug or unexpected behavior. Probably easiest to test with some directory lower in the tree than `/usr`.

**Comment by buhtz** [comment] 2023-12-07 13:16
We need more feedback and details here from @frank777777777 . The problem is not clear.
But it might be a duplicate of #1199 ?

**Comment by buhtz** [comment] 2024-01-09 09:11
Dear @frank777777777 ,
the Issues is quit old. Can you reproduce the problem with a newer version of BIT? Can you give us the steps to reproduce?

Otherwise I vote to close the Issue.

**Comment by emtiu** [comment] 2024-01-09 12:39
I've been unable to reproduce with the latest dev version.

Steps tried:
1. Have a source directory called `test/`, with files `test/a`, `test/a` and `test/c` as well as folder `test/foo/`.
2. Take a snapshot.
3. Create additional folder `test/foo/bar/`. The bug—as reported—should manifest as this folder **not** being deleted when restoring `test/`.
4. Restore `test/` from the snapshot from step 2. in two different ways:
    - by _"Restore `test/`"_ (3rd option in the Restore menu)
    - by manually selecting all files and folders in the source directory (`test/a`, `test/a`, `test/c`, `test/foo/`) and selecting _"Restore"_ (1st option in the Restore menu).

In all cases, `test/foo/bar/` is deleted, as expected. This is true even if `test/foo/bar/` contains additional files and folders.

Therefore, I am closing this issue. Feel free to re-open if new information emerges.

**Closed by emtiu** 2024-01-09 12:39 UTC
Labels: Bug, Feedback
