### ISSUE TITLE
backup operation modifies previous backup dir's permissions

### ISSUE THREAD

**Issue by quazgar** [bit-team/backintime#912] opened 2018-07-20 14:29 UTC
With current master (012b0783) and the following setting (all are necessary conditions for this behaviour):

- I have "always checksum" enabled.
- "Always take snapshot" disabled (it should only take a snapshot when there are changes).

 I see the following problem:

1. Create snapshot of a changed source, as usual.
2. Try to create another snapshot -> nothing seems to happen.
3. Try to create another snapshot again -> a full snapshot is taken, this also does not create any/all hard links (-> disk space is used up).

Further examination of duplicated files (although they should just be hard-linked via `--link-dest`) shows that they changed their permission during step 2. above.  Files that were not writable by anyone (`r--------`) become user-writeable (`rw-------`) in that step.  This probably also causes rsync to not hard-link the files (and see them as changed in the first place).

**Comment by quazgar** [comment] 2018-07-20 14:43
Small correction, `--checksum` is not necessary for this behaviour. So it seems to be a side effect of manually initiating a backup.

**Comment by quazgar** [comment] 2018-07-20 17:40
It seems to boil down to [line 1952 in tools.py](https://github.com/bit-team/backintime/blob/master/common/tools.py#L1952), where rsync is called (to delete the temporary directory?):

    In [2]: self.cmd
    Out[2]: 
    ['rsync',
     '-a',
     '--delete',
     '/tmp/tmpjlia2pw_/',
     '/PATH/TO/new_snapshot']

Mysteriously (and I thought I understood rsync), *before the `subprocess.open()` call, the permissions in the *last* backup directory were OK, but *afterwards* all files have write permissions for the user.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment] 2022-08-22 15:05
Can you reproduce this in the current main branch?

**Comment by buhtzz** [comment] 2022-09-26 08:58
@quazgar There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Bug, Feedback

Duplicate of #912 or #988 ?

**Comment by emtiu** [comment] 2022-10-07 22:51
Closing as likely duplicate of #988.

**Closed by emtiu** 2022-10-07 22:51 UTC
