### ISSUE TITLE
SNW_SERVICE error. Is BiT connecting to the Internet?

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#777] opened 2017-06-12 23:10 UTC
Ubuntu 14.04, Intel i5, 6GB, 256GB-SSD
Using terminal:
  sudo -i backintime backup --profile-id 1 --config /home/vest/.config/backintime/config

INFO: Lock
INFO: Take a new snapshot. Profile: 1 Main profile
INFO: Compare with old snapshot: 20170612-155527-189
"sni-qt/7313" WARN  16:03:54.769 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
INFO: [qt4systrayicon] begin loop
INFO: Create hard-links
INFO: Call rsync to take the snapshot
INFO: Save config file
INFO: Save permissions
INFO: Create info file
INFO: Remove backups older than: 20170123-000000
INFO: Unlock

NO Errors reported in the Log files

What does this mean and what can I do to stop it?

Which "factory" is being notified?

**Comment by Germar** [comment] 2017-06-13 20:57
Duplicate of #751

Just that you're paranoid don't mean they're not after you :wink:

**Closed by Germar** 2017-06-13 20:57 UTC
Labels: duplicate

**Comment by FlailAway** [comment] 2017-06-14 16:32
:) Have you been reading my emails?

I was more interested in anything I could do to prevent the error display. I AM paranoid about errors though.

**Comment by Germar** [comment] 2017-06-14 16:46
It's just a warning from Qt (the Framework used for GUI in BiT) about an incorrect init of a module which is not even in use with BiT.

All you could do is to update to current dev version 1.2
