### ISSUE TITLE
"Back In Time (root)" problem claimed in a blog post (lacking details)

### ISSUE THREAD

**Issue by ken-bell** [bit-team/backintime#819] opened 2017-10-06 21:44 UTC
Has anybody come across this issue as described in the blog URL below?

http://unix.cafe/wp/en/2017/09/restore-ownership-octal-permissions-backup

**Quoting here; this is not something I experienced myself**
I was able to see the /root contents. I mean my normal daily used user was able to read and write to /root, /boot, /usr …etc. WTH! I said! When I checked their permissions I found that they were really a mess. Some of them were even being owned by my user instead of the right owner.!

I ran to the older snapshots I have, that were taken by CrashPlan, and compared the permissions. Guess what? Yeah you’re right they were indeed different. Then I realized that, there must be a real nasty bug in the Back In Time. Fortunately, I was lucky enough to discover this issue before it was kinda too late.
**End Quote**

The blog post lacks all detail as to how this problem was triggered, so I'm just wondering.

Thanks.
Ken

**Comment by buhtz** [comment] 2017-10-09 07:52
I asked the blogger to add more informations to this issue here.

**Comment by DeaDSouL** [comment] 2017-10-09 17:16
Hello,
I don't know what exactly triggered it. All I remember I started the 'Back In Time' as a normal user, and tried to backup the 'home' and some of the system's directories. and I was getting some error that the some files couldn't be backed-up because of the permissions. I removed the snapshots, and closed the app. This time I opened the 'Back In Time (root)' it complained about something with the mounting.. I closed it, tried to `umount` the directory in /tmp/backintime if I recall it correctly. then removed the folder's contents manually from the remote location.
then I re-start the app and start taking the backups and snapshots.
And it was encrypted with encfs.

That's all I did.

those are the packages were installed: 'backintime-common' and 'backintime-kde4' 


here are some info of the packages:
0 ✓ root@workstation ~ $ urpmq -i backintime-kde4
Name        : backintime-kde4
Version     : 1.0.36
Release     : 3.mga5
Group       : Archiving/Backup
Size        : 288322                       Architecture: noarch
Source RPM  : backintime-1.0.36-3.mga5.src.rpm
URL         : http://backintime.le-web.org
Summary     : KDE Frontend for Back In Time
Description :
KDE Frontend for Back In Time.

Name        : backintime-kde4
Version     : 1.0.36
Release     : 3.2.mga5
Group       : Archiving/Backup
Size        : 288322                       Architecture: noarch
Source RPM  : backintime-1.0.36-3.2.mga5.src.rpm
URL         : http://backintime.le-web.org
Summary     : KDE Frontend for Back In Time
Description :
KDE Frontend for Back In Time.

Name        : backintime-kde4
Version     : 1.0.36
Release     : 3.mga5
Group       : Archiving/Backup
Size        : 288322                       Architecture: noarch
Source RPM  : backintime-1.0.36-3.mga5.src.rpm
URL         : http://backintime.le-web.org
Summary     : KDE Frontend for Back In Time
Description :
KDE Frontend for Back In Time.

Name        : backintime-kde4
Version     : 1.0.36
Release     : 3.2.mga5
Group       : Archiving/Backup
Size        : 288322                       Architecture: noarch
Source RPM  : backintime-1.0.36-3.2.mga5.src.rpm
URL         : http://backintime.le-web.org
Summary     : KDE Frontend for Back In Time
Description :
KDE Frontend for Back In Time.



0 ✓ root@workstation ~ $ urpmq -i backintime-common
Name        : backintime-common
Version     : 1.0.36
Release     : 3.mga5
Group       : Archiving/Backup
Size        : 1309443                      Architecture: noarch
Source RPM  : backintime-1.0.36-3.mga5.src.rpm
URL         : http://backintime.le-web.org
Summary     : Back Up Tool for Linux
Description :
Common files for Back In Time

Name        : backintime-common
Version     : 1.0.36
Release     : 3.2.mga5
Group       : Archiving/Backup
Size        : 1309443                      Architecture: noarch
Source RPM  : backintime-1.0.36-3.2.mga5.src.rpm
URL         : http://backintime.le-web.org
Summary     : Back Up Tool for Linux
Description :
Common files for Back In Time

Name        : backintime-common
Version     : 1.0.36
Release     : 3.mga5
Group       : Archiving/Backup
Size        : 1309443                      Architecture: noarch
Source RPM  : backintime-1.0.36-3.mga5.src.rpm
URL         : http://backintime.le-web.org
Summary     : Back Up Tool for Linux
Description :
Common files for Back In Time

Name        : backintime-common
Version     : 1.0.36
Release     : 3.2.mga5
Group       : Archiving/Backup
Size        : 1309443                      Architecture: noarch
Source RPM  : backintime-1.0.36-3.2.mga5.src.rpm
URL         : http://backintime.le-web.org
Summary     : Back Up Tool for Linux
Description :
Common files for Back In Time


And I'm using Mageia 5. Linux 4.4.88-desktop-1.mga5 #1 SMP Thu Sep 14 00:03:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


Thanks

**Comment by buhtz** [comment] 2017-10-09 19:13
Do you still use version `1.0.36` it is quite outdated.
Can you try to reproduce the problem with current development version?

Please feel free to ask if you need help to build/install the development version.

**Comment by buhtzz** [comment] 2022-09-25 07:57
@DeaDSouL and @ken-bell There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

**Comment by emtiu** [comment] 2022-10-22 14:20
Closed as outdated and not reproducable.

**Closed by emtiu** 2022-10-22 14:20 UTC
