### ISSUE TITLE
Backup on filesystem mount no longer working

### ISSUE THREAD

**Issue by bovender** [bit-team/backintime#674] opened 2016-12-03 09:51 UTC
Hi,

the backup schedule option "When drive get[s] connected (udev)" no longer works for me.

The udev rule seems to be ok; after issuing `sudo udevadm control -l debug` I get this in the syslog when connecting the drive:

    systemd-udevd[18966]: Process '/bin/su - 'daniel' -c '/usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime --profile-id 2 backup-job >/dev/null 2>&1'' succeeded.

But nothing happens, the backup is not triggered.

When I paste the command in the terminal, leaving out the redirection:

    /bin/su - 'daniel' -c '/usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime --profile-id 2 backup-job'

I get this output:

    Back In Time
    Version: 1.1.12.a
    
    Back In Time comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to redistribute it
    under certain conditions; type `backintime --license' for details.
    
    INFO: Lock
    INFO: Inhibit Suspend started. Reason: take snapshot
    INFO: Take a new snapshot. Profile: 2 Complete
    INFO: Call rsync to take the snapshot
    INFO: [qt4systrayicon] begin loop

So it appears it's working ok.

I'm puzzled because it used to work automatically, too.

Evidently the udev rule triggers, and evidently the command, when copied and pasted into the terminal, works as well. Why does it no longer work automatically?

I'm on Ubuntu 16.10.

**Comment by Germar** [comment] 2016-12-03 21:39
This is a known bug in earlier versions. Please update to 1.2.0~alpha from our testing PPA:

```
sudo add-apt-repository ppa:bit-team/testing
sudo apt-get update
sudo apt-get upgrade
```

Duplicate of #605

**Closed by Germar** 2016-12-03 21:39 UTC
Labels: duplicate

**Comment by bovender** [comment] 2016-12-05 05:01
Thanks for the swift response, and my apologies for having missed the duplicate. Works fine now.
