### ISSUE TITLE
[CentOS] Doesn't open after successful install

### ISSUE THREAD

**Issue by sbembenek18** [bit-team/backintime#1081] opened 2020-05-03 04:39 UTC
I follow the instructions and the install does work and it even includes the icon in applications menu, but when I try to fire it up, it just hangs.

**Comment by Klakurka** [comment] 2021-01-25 07:18
Likely the same issue as #1042. If you run `backintime-qt` in the terminal, it'll show you the error.

**Comment by aryoda** [comment] 2022-09-11 11:08
I also think it is a duplicate of #1042. Could you please check the proposed solution there and report back here (or close the issue if it is no longer relevant for you). THX :-)

**Comment by aryoda** [comment] 2022-09-11 11:09
@emtiu Could you please add the "Distro-specific" and "Discussion" label to (or whatever is missing). THX!

**Comment by emtiu** [comment] 2022-10-22 16:58
Closing, because the reporter is not responding.

**Closed by emtiu** 2022-10-22 16:58 UTC
Labels: Distro-Specific, Feedback
