### ISSUE TITLE
Crashes while trying to do a diff of two snapshots.

### ISSUE THREAD

**Issue by paulstewartis** [bit-team/backintime#1197] opened 2021-11-23 00:53 UTC
I selected a snapshot.  Then chose a snapshot from the day before and clicked diff.  The UI froze a for a long time and then the application crashed.  I repeated this several times with different snapshots.  

Backup target is ssh.  Snapshots are ~1.2 GB in size.  It's been a while but, I have successfully diffed snapshots on this system in the past. Diff tool is Meld.  OS is opensuse Leap 15.3 (fully updated).

[i noticed a growing folder in /tmp that eventually filled the space (tmpfs at 25% ram ~974mb).  I increased ram (vm) to 6GB and increased /tmp to 50% (~3GB).  I attempted the diff again and the application still crashed.  The temp folder was only a little over 1GB.  Plenty of free ram too.]

**Comment by paulstewartis** [comment] 2021-11-23 16:28
Maybe a dupe of [(https://github.com/bit-team/backintime/issues/1083)]

**Comment by buhtzz** [comment] 2022-09-25 11:59
Tag: Qt

**Comment by zbigniewfr** [comment] 2022-10-13 19:19
I'm experiencing the same problem.

**Comment by buhtzz** [comment] 2022-10-14 08:11
Dear @paulstewartis and @zbigniewfr ,

I have a guess what it could be but can you show us the debug output please?
Start BIT in a terminal window via `backintime-qt --debug`.

**Comment by zbigniewfr** [comment] 2022-10-14 08:57
@buhtzz log from debug:
`DEBUG: [common/backintime.py:583 argParse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.3.2

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:670 getConfig] config file: /home/zygi/.config/backintime/config
DEBUG: [common/backintime.py:671 getConfig] share path: /home/zygi/.local/share/backintime
DEBUG: [common/backintime.py:672 getConfig] profiles: 1=Main profile
DEBUG: [common/pluginmanager.py:90 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin qt4plugin.py
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin notifyplugin.py
DEBUG: [common/tools.py:829 keyringSupported] No appropriate keyring found. 'keyring.backends.chainer' can't be used with BackInTime
DEBUG: [common/mount.py:73 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:81 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
DEBUG: [common/tools.py:1237 readCrontab] Read 2 lines from users crontab
DEBUG: [common/config.py:1466 Config.removeOldCrontab] Clearing system Back In Time entries
DEBUG: [common/config.py:1500 Config.cronLine] Profile: Main profile | Automatic backup: Every 6 hours
DEBUG: [common/tools.py:1274 writeCrontab] Wrote 2 lines to users crontab
Killed
`

**Comment by emtiu** [comment] 2022-10-14 11:07
There's a traceback in #1083, which might be the same problem here. I'm not closing it as a duplicate yet, because we haven't seen identical error messages so far.

**Comment by buhtz** [comment] 2023-06-29 08:15
I have seen this with 1.3.4-dev but wasn't able to reproduce it for sure. 😄 
The trigger seems to be the diff dialog but the output provided and I've seen myself indicates something around `writeCrontab()`.

**Comment by buhtz** [comment] 2024-09-10 14:20
The reason for the error is still unknown. But the code around `writeContrab()` was refactored a lot.

I will close this issue because of that. Please feel free to reopen it if the problem happens with the latest version of BIT.

**Closed by buhtz** 2024-09-10 14:20 UTC
Labels: Medium, Bug, Heisenbug
