### ISSUE TITLE
backintime with fcron

### ISSUE THREAD

**Issue by jerome-diver** [bit-team/backintime#874] opened 2018-02-24 10:59 UTC
Hi,
I'm just installed backintime on archlinux from aur repo.
I no have (and don't want to have) cron, instead, i use fcron.
How to make backintime works with fcron instead of cron ?
May i try to modify the source code for that ? 
And then what i should do for get source code from aur ? then i will find how/where to modify it, and then i should have to re-compil maybe...
Informations around this are welcome.
Also, a dialog box open at first config time (at the end when click "OK") who said that i have no crontab and that i would desactivate automatic saved... ok, but i have no automatic saved configured, and then, it looks like users who has no cron are locked at this point. 
How to use backintime without cron jobs ?

**Comment by emtiu** [comment] 2022-09-14 22:07
Hi, thanks for the report, I'm closing this Issue as a duplicate of #610.

**Closed by emtiu** 2022-09-14 22:07 UTC
