### ISSUE TITLE
Using a bastion host with ssh alternative in BIT?

### ISSUE THREAD

**Issue by ersv** [bit-team/backintime#655] opened 2016-10-28 12:28 UTC
Hello,
Is it possible somehow to use a bastion host with the ssh alternative in BIT?

I use a bastion host to connect to many different servers on an internal network. In this way I can leave just one port open (the bastion host) on the external ip address. 

Right now I can access my BIT server via a dedicated port on the external ip address, but I would prefer to close this port and reach the BIT server via the bastion host as well. Is it possible?

Thanks

**Comment by Germar** [comment] 2016-10-28 21:47
Duplicate of #647

Actually it does work since a week :grin:. Just install current master or from `ppa:bit-team/testing`, deactivate `Check if remote host is online` in `Expert Options` and create a `~/.ssh/config` like [this tutorial](http://sshmenu.sourceforge.net/articles/transparent-mulithop.html)

**Closed by Germar** 2016-10-28 21:47 UTC
Labels: duplicate
