### ISSUE TITLE
Feature Request: Show files taking up the most space

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#242] opened 2015-10-11 16:41 UTC
Would only make sense together with https://bugs.launchpad.net/backintime/+bug/1171170

When the backup partition is full, it would be nice to have an overview of the files taking up most space (and one mode showing the space of all the file’s versions added up).

---

Imported from Launchpad using lp2gh.
- date created: 2013-04-21T14:29:16Z
- owner: profpatsch
- the launchpad url was https://bugs.launchpad.net/bugs/1171173

**Comment by emtiu** [comment] 2022-09-24 21:37
Closing as duplicate of #406.

**Closed by emtiu** 2022-09-24 21:37 UTC
Labels: wishlist
