### ISSUE TITLE
Snapshots are taking much more space since 09/2021?.:

### ISSUE THREAD

**Issue by m2c2lure67** [bit-team/backintime#1189] opened 2021-10-19 19:22 UTC
Has something changed in BiT that might replace links with the files they point to?  I backup my G-Drive which is stored on an NTFS drive, and my HOME folder which contains "shortcuts" to most of the files on said G-Drive.  Browsing these folders in "**_/media/mgm/Storage/backintime/backintime/McClureFamilyHTPC/mgm/1/last_snapshot/backup/home/mgm/_**" seems to indicate them as "Links" via their icon, but I'm not sure why I lost nearly 500GB of space in September, and deleting previous snapshots seems to only free up a few GB per deletion.

**Comment by emtiu** [comment] 2022-09-09 09:35
Thank your for your report! You are probably running into the problem reported in #988.

I'm closing this Issue as a duplicate of #988, but feel free to re-open it if you have further information.

**Closed by emtiu** 2022-09-09 09:35 UTC
