### ISSUE TITLE
glitch when encountering filenames with spaces 

### ISSUE THREAD

**Issue by OBedford** [bit-team/backintime#709] opened 2017-02-21 20:38 UTC
When clicking on a file in a snapshot which contains spaces in the filename I get a disturbing error message. E.g. 

»/media/ojo/Buffalo/Backups/backintime/apollo/ojo/1/20170216-182047-694/backup/home/ojo/Musik/MP3s/Raitt,Bonnie/The_Best_Of_Bonnie_Raitt/The%20Best%20Of%20Bonnie%20Raitt.m3u« konnte nicht geöffnet werden.
Fehler beim Holen der Informationen für Datei »/media/ojo/Buffalo/Backups/backintime/apollo/ojo/1/20170216-182047-694/backup/home/ojo/Musik/MP3s/Raitt,Bonnie/The_Best_Of_Bonnie_Raitt/The%20Best%20Of%20Bonnie%20Raitt.m3u«: Datei oder Verzeichnis nicht gefunden.

In English: file not found. The file itself is there and can also be restored.

Back In Time 1.1.12, Ubuntu 16.04.2

Regards,
Oliver

**Comment by Germar** [comment] 2017-02-21 21:27
This is fixed in next version 1.2.0
Duplicate of #552

**Closed by Germar** 2017-02-21 21:27 UTC
Labels: duplicate
