### ISSUE TITLE
Unchanged files are marked as changed

### ISSUE THREAD

**Issue by sebastian9er** [bit-team/backintime#1028] opened 2019-08-05 15:47 UTC
I ran two backups within one day: One initial backup overnight and one in the morning, without touching any of the backup'ed files.
However, in the Snapshot Log View I see many changed files, like the following line:
[C] hf...p..... home/user/arduino-1.8.5/hardware/tools/avr/avr/bin/ld.bfd

When calculating the MD5 sum over that file and also the "same" file from the previous snapshot they are equal.
Is this a bug or WAI?

Thanks!

**Comment by habiloid** [comment] 2019-10-06 19:00
I am getting a simllar problem. Running a backup onto a USB hard drive from one of my internal drives.
Everytime I rum it every file gets a log entry something like:

[C] cf...p..... home/habiloid/pictures/2003/photo0001.tif

Even though virtually none of the thousands of files and tens of directories have changed. The backup takes hours where under previous versions it took minutes.

I expected something like this on the first time I ran a new backup with a 1.2 version but the continuation of this behaviour is becoming a real problem.

Is there a solution?

Ta

**Comment by colinl** [comment] 2019-10-06 19:25
What are the permissions on those files?  If they are r--r--r-- then this is a dup of #994

**Comment by sebastian9er** [comment] 2019-10-06 19:28
In my case the permissions on this file are -rwxr-xr-x

**Comment by habiloid** [comment] 2019-10-06 19:50
They are all r--r--r-- (at least as far as I can tell). Sorry for the duplication

**Comment by colinl** [comment] 2019-10-06 20:56
Don't be sorry, it is good to get confirmation that I am not the only one seeing it. I reported it in May but this is the first confirmation that anyone else is seeing the problem.

**Comment by colinl** [comment] 2019-10-06 20:59
@sebastian9er if there is a particular file or file that it is happening with then check the permissions on the file and on that file in the backup.

**Comment by sebastian9er** [comment] 2019-10-07 17:36
Thanks @colinl , but neither the initial files nor the backup'ed files are r--r--r--
(in my case they are -rwxrwxrwx locally and in the backup).

Today I ran another backup and now _every_ file gets marked as changed. This bug is probably related to the BiT update I did recently: I updated from 1.1.12 to 1.2.1.

**Comment by sebastian9er** [comment] 2019-10-07 17:40
Actually, I just found out that this is indeed a known bug (not my initial problem, but my current one) in https://github.com/bit-team/backintime/issues/989

**Comment by colinl** [comment] 2019-10-07 20:08
Also see #988

**Comment by habiloid** [comment] 2019-10-08 05:00
The hack suggested by Cyber1000 in  #988; adding 

profile1.snapshots.rsync_options.value=--no-perms --no-group --no-owner

works for me. It's OK for the profile that was causing me the most problems where I know the permissions on all the files is r--r--r-- (and will stay like that). Not a good solution for my more general backups where permissions are important and can change.

**Comment by buhtzz** [comment] 2022-09-25 13:06
Tag: Bug

Seems to be a duplicate of #988 and/or #994.

**Comment by emtiu** [comment] 2022-10-21 23:28
Closing as duplicate of #988 and/or #994.

**Closed by emtiu** 2022-10-21 23:28 UTC
