### ISSUE TITLE
Very slow operation - Manjaro Linux (XFCE)

### ISSUE THREAD

**Issue by leebut** [bit-team/backintime#1055] opened 2020-01-10 13:08 UTC
Hello,

Back in Time has been running very slowly, sometimes slower than 100kB/s.
I am running version 1.2.1 on Manjaro Linux.

SYSTEM:
Ryzen 5 2600 CPU
16GB Ram
ASUS Prime B450-k M'board

**Comment by timbo-lino** [comment] 2020-01-19 08:21
Same here (manjaro KDE)
On Fedora I needed to go back to 1.1.24 to get it working

**Comment by agmartin2** [comment] 2020-02-13 10:44
This may be the same as #988 (Version 1.2.0 works very slow). Seems caused by a change in the way BiT deals with permissions, groups and ownerships.

**Comment by timbo-lino** [comment] 2020-02-13 13:28
Right now automatic backups seem to work normally. 

They are in a good size and are finished in a good time. Not that fast as 1.1.24 but I can live with it.

**Comment by emtiu** [comment] 2022-09-06 21:47
Closing as duplicate of #988.

**Closed by emtiu** 2022-09-06 21:47 UTC
