### ISSUE TITLE
shedule "When drive get connected (udev)" doesn't wait 30 seconds as it says

### ISSUE THREAD

**Issue by Albertc** [bit-team/backintime#663] opened 2016-11-20 16:02 UTC
When I connect the external drive via usb appears this message (extracted from log)

```
[E] Can't find snapshots folder.
If it is on a removable drive, please plug it in.
Waiting 30 seconds.
```

And that's all, nothing happens after 30 seconds. 

If I want to make the backup I have to do it manually

Thanks

**Comment by Germar** [comment] 2016-11-20 20:24
Are you using KDE? Then please make sure, your drive mounts automatically after plugin.

`System Settings` > `Removeable Storage` > `Removeable Devices`

enable both `Enable automatic mounting of removeable media` and `Automatically mount removeable media when attached`

**Comment by Albertc** [comment] 2016-11-21 07:54
I'm using Ubuntu Mate, las release, and the drive mounts automatically after plugin **IF** backintime is not configured to run "when drive gets connected"... If I shedulde backinteim tu run every day or never (disabled) , the drive mounts very well automatically in 2 seconds.

Is that possible?

Thanks

**Comment by Germar** [comment] 2016-11-21 10:24
Ah, okay. There was a bug in older Releases which made BiT to not fork correctly into background and so `udev` didn't proceed to handle events for the new drive.

Please install current testing version from PPA:
```
sudo add-apt-repository ppa:bit-team/testing
sudo apt-get update
sudo apt-get upgrade
```

This is a duplicate of #605

**Closed by Germar** 2016-11-21 10:24 UTC
Labels: duplicate

**Comment by Albertc** [comment] 2016-11-21 17:06
All right now, thanks
