### ISSUE TITLE
Backintime "Value Error"

### ISSUE THREAD

**Issue by Salkin1995** [bit-team/backintime#514] opened 2016-01-10 00:47 UTC
Hey, it would be nice if you could help me.
Since last week I get this type of error message when I start back in time.

ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/app.py", line 644, in update_take_snapshot
    busy = self.snapshots.is_busy()
  File "/usr/share/backintime/common/snapshots.py", line 410, in is_busy
    return not instance.check()
  File "/usr/share/backintime/common/applicationinstance.py", line 59, in check
    pid = int(data[0])

I use back in time 1.1.8 from the ppa:bit-team/stable on ubuntu 15.10.
Many thanks in advance.

**Comment by Germar** [comment] 2016-01-10 01:10
Please update to `1.1.10` from `ppa:bit-team/stable`. Just released two hours ago :grin:

This is fixed in there!

Duplicate of #505

**Closed by Germar** 2016-01-10 01:10 UTC
Labels: duplicate

**Comment by Salkin1995** [comment] 2016-01-12 20:13
Thank you. :D
