### ISSUE TITLE
No clear warning when copy fails

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#395] opened 2015-10-11 17:17 UTC
I just solved a problem on my BiT setup, wherein each backup was a full copy of the source data (no incremental backups).

I had the following error at the beginning of the backup process, using CIFS on a NTFS-based consumer-grade NAS (notice how these lines are marked "[i]", as in "information", and do not appear in the "errors" log viewer window.)

```
    [I] Création des liens physiques
    [I] cp -aRl "/salon/_BACKUP/backintime/ubuntu-air/thomas/3/20111128-145324-949/backup/"* "/salon/_BACKUP/backintime/ubuntu-air/thomas/3/new_snapshot/backup/"
    [I] returns: 256
```

The answer lies here :

```
    https://answers.launchpad.net/backintime/+question/93336
    "the solution is to modify your CIFS mount options and include nosetuids,noperm"
```

After adding mount options nosetuids,noperm to my backup partition, I managed to solve my problem. However, it took me hours to figure out, partly because the warning message was not obvious.

I am suggesting testing for this error condition, and reporting it to the user, along with a short informative message or link.

---

Imported from Launchpad using lp2gh.
- date created: 2011-11-28T07:28:54Z
- owner: thomas-tempe
- the launchpad url was https://bugs.launchpad.net/bugs/897093

**Comment by emtiu** [comment] 2022-09-24 22:01
Closing as duplicate of #478.

**Closed by emtiu** 2022-09-24 22:01 UTC
Labels: discuss
