### ISSUE TITLE
Support for fcrontab

### ISSUE THREAD

**Issue by willemw12** [bit-team/backintime#610] opened 2016-08-02 09:06 UTC
Please add support for fcrontab, one of the cron alternatives.

One issue when fcrontab is installed is that you cannot create configuration file ~/.config/backintime/config from the GUI. BIT fails with a dialog message: "Can\'t find crontab.\nAre you sure cron is installed ?\nIf not you should disable all automatic backups."

A solution is to try to call fcrontab if crontab cannot be found.

I have tested this by changing files:
- common/config.py
- common/test/test_tools.py
- common/tools.py

1) Changed calls to crontab into calls to fcrontab 

2) Ignored stderr output in common/tools.py by changing:

```
         out, err = proc.communicate()
         if proc.returncode or err:
```

into:

```
         out, err = proc.communicate()
         if proc.returncode:
```

**Comment by wschlich** [comment] 2016-08-24 15:29
Please fix this.

Here's the `backintime` output when trying to use `fcrontab`:

`ERROR: Failed to get crontab lines: 0, 2016-08-24 17:24:22  INFO listing wschlich's fcrontab`
`2016-08-24 17:24:22  INFO user wschlich has no fcrontab.`

`ERROR: Failed to write lines to crontab: 0, 2016-08-24 17:24:22  INFO installing file /tmp/tmp1nql0kvx for user wschlich`
`2016-08-24 17:24:22  INFO wschlich's fcrontab contains no entries : removed.`
`Modifications will be taken into account at 17:25.`

Afterwards, my user crontab looks like this:

`[wschlich@zephyr(pts/3):~]$ crontab -l`
`2016-08-24 17:25:17  INFO listing wschlich's fcrontab`
`#Back In Time system entry, this will be edited by the gui:`
`#Please don't delete these two lines, or all custom backintime entries are going to be deleted next time you call the gui options!`
`[wschlich@zephyr(pts/3):~]$`

**Comment by kokoko3k** [comment] 2017-09-28 09:07
Yes please, without crontab i can't even save the configured profile.
I'm trying to link /bin/true to /bin/crontab to trick it...

**Comment by kokoko3k** [comment] 2022-01-13 13:39
To anybody having problems to upgrade to 1.3.0 and used my bad hack, remove it and try again or the install will fail in the tests.

**Comment by emtiu** [comment] 2022-09-07 21:27
fcrontab seems to be rather common, so this should have some priority.

**Comment by buhtz** [comment] 2023-12-07 11:58
The code need to be re-designed to better encapsulate the used scheduling technic.
After that we can have modules for Vixie Cron, fcron, cronie (Debian will migrate to it in the future), systemd based scheduling, etc.

So it is a big job.

**Comment by xelvinc** [comment] 2024-01-02 21:03
I have also issues with fcron. I'm on gentoo with BiT 1.3.3. The symlink /usr/bin/crontab -> fcrontab is automaticly created when installing BiT.
I run BiT as root (backintime-qt_polkit)

The output from crontab looks like this:

    gentoo ~ # crontab -l
    2024-01-02 21:36:05  INFO listing root's fcrontab
    15 * * * * touch ~/cron_hourly

Running BiT, I get the same error as wschlich when opening the settings dialog:
`ERROR: [common/tools.py:1403 readCrontab] Failed to get crontab lines: 0, 2024-01-01 17:54:33  INFO listing root's fcrontab`

Note that the returncode is 0, but the err contains "2024-01-02 20:35:02  INFO listing root's fcrontab".
So for some reason fcron is directing the INFO line to stderr:

    gentoo ~ # crontab -l > crontab.stdout 2> crontab.stderr
    gentoo ~ # cat crontab.stdout
    15 * * * * touch ~/cron_hourly
    gentoo ~ # cat crontab.stderr
    2024-01-02 21:39:33  INFO listing root's fcrontab

This causes BiT to handle it as an error and the actual line from stdout is not returned from readCrontab().

Then when you close the settings dialog by clicking OK, the writeCrontab(lines) function writes the new crontab without anything in lines, and thus the complete crontab is wiped out and only the new lines from BiT are written.
Then it also gives the same error because again the INFO directed to stderr, and you can't save your settings:
`ERROR: [common/tools.py:1443 writeCrontab] Failed to write lines to crontab: 0, 2024-01-01 17:54:33  INFO installing file /tmp/tmpanrocdpp for user root`

As a work around I removed the "or err" from the readCrontab() and writeCrontab(lines) function:

    gentoo ~ # diff /usr/share/backintime/common/tools.py tmp/backintime-1.3.3/common/tools.py 
    1402c1402
    <         if proc.returncode:
    ---
    >         if proc.returncode or err:
    1442c1442
    <     if proc.returncode:
    ---
    >     if proc.returncode or err:

But maybe there is a better way to handle this.
It would be nice to get a confirmation before writing the new crontab, because now everything is wiped out without warning.
Also when the schedule is disabled, it could be completely skipped.

**Comment by buhtz** [comment] 2024-06-04 14:16
Can someone please explain the difference between "crontab" and "fcrontab".
To my knowledge cron(tab) and frcrontab can exist on the same system at the same time. So why does BIT need fcrontab support?

What is fcrontab support? It is not clear to me what need to be implemented. Please clearly describe the feature.

**Comment by willemw12** [comment] 2024-06-04 17:41
Fcrontab is useful for machines that are not switched on 24 hours a day (laptops, ...).

At least on Arch Linux, you can only install one cron program at a time. "cronie" and "fcron" are cron packages that are in the official repository and there more in the AUR.

The fcron package has executable "fcrontab". The (standard) cronie package has executable "crontab". Fcrontab support means running "fcrontab" if it is installed.

**Comment by xelvinc** [comment] 2024-06-04 18:13
As far as I understand, there are different implementations of cron that all use crontab as command line tool and/or as list of cron-jobs. fcron is one of the implementations. When installing fcron on gentoo, their is a symlink created /usr/bin/crontab -> fcrontab.

Apparently the output from fcron is different from other cron implementions, in the sense that some info is directed to stderr instead of stdout.
Therefor this should be handled differently by BIT.

Hope this helps.

**Comment by buhtz** [comment] 2024-06-04 18:19
So fcron does understand a regular cron-like crontab syntax. But cron doesn't understand the extended fcron syntax.

The question is if you just want to have cron-like crontab syntax run by fcron? Or do you want to have extended fcron timing features represented in the BIT GUI?

**Comment by xelvinc** [comment] 2024-06-04 18:28
The problem is not the crontab syntax. The problem is that fcron is directing the INFO line to stderr:
```
gentoo ~ # crontab -l > crontab.stdout 2> crontab.stderr
gentoo ~ # cat crontab.stdout
15 * * * * touch ~/cron_hourly
gentoo ~ # cat crontab.stderr
2024-01-02 21:39:33  INFO listing root's fcrontab
```
This causes BiT to handle it as an error.

**Comment by willemw12** [comment] 2024-06-04 18:35
I have updated my previous comment: Arch has packages cronie/fcron and executables crontab/fcrontab respectively.
There is no symlink from /usr/bin/crontab to /usr/bin/fcrontab on Arch.

**Comment by buhtz** [comment] 2024-06-04 19:57
> The problem is not the crontab syntax. The problem is that fcron is directing the INFO line to stderr:

I don't understand your example. Where does this "INFO line" comes from?

**Comment by xelvinc** [comment] 2024-06-04 20:19
It is the output from the command fcrontab -l
```
gentoo ~ # fcrontab -l
2024-01-02 21:36:05  INFO listing root's fcrontab
15 * * * * touch ~/cron_hourly
```

In tools.py, crontab -l is invoked in the function readCrontab. Since I have the symlink crontab -> fcrontab, the output comes from fcrontab.
```
def readCrontab():
    """
    Read users crontab.

    Returns:
        list:   crontab lines
    """
    cmd = ['crontab', '-l']
    if not checkCommand(cmd[0]):
``

**Comment by buhtz** [comment] 2024-06-05 07:21
Thank you. I get it know.
So for a first step it would be enough if `readCrontab()` and `writeCrontab()` could handle fcron, too?

There is an open PR #1747 refactoring the existing crontab code in BIT. After that maybe someone want to jump in and try to implement a solution? Doesn't need to be perfect or full functional. We can work together on it.

**Comment by willemw12** [comment] 2024-06-05 07:48
The purpose of this issue is to include fcron in BIT, because some machines only have fcron installed. And use the current BIT cron features with fcron,

Any additional fcron specific functionality to add to BIT should, I think, be a separate feature request. No need to start on it, if there is no such request.

**Comment by willemw12** [comment] 2024-06-05 07:52
I suppose (most of) the cron and fcron commands+arguments used in BIT would be the same, except for the command name, of course.

**Comment by buhtz** [comment] 2024-08-01 11:24
Can you name me a distro where only fcron is used by default? I don't want to setup a vanilla Arch, cost me to much time because it feels like Linux from scratch. ;)

**Comment by willemw12** [comment] 2024-08-01 15:18
You could install EndeavourOS or use the "archinstall" script (TUI menu) that comes with the Arch Linux live ISO.

EndeavourOS has a separate tab (not the default tab) in the GUI welcome/startup program for upgrading the system. It also comes with an AUR helper preinstalled.

Won't take you much time installing the OS and a desktop. Then install fcrontab and enable its service.

**Comment by buhtz** [comment] 2024-09-02 14:38
> Then install fcrontab and enable its service.

That is not what I meant. I want to have a system where fcron is installed and configured out of the box. I need to minimize the risk that something is wrong with my configuration. Installing and configuring fcron can also be done in my Debian GNU/Linux.

OK, it seems there is no system in the wild offering fcron out of the box. So let me ask the other way.

Can you tell me short and step by step how to replace cron with fcron, and most important how to verify that fcron is running instead of something else?

**Comment by willemw12** [comment] 2024-09-03 05:39
On Arch:
When a package is installed/uninstalled, services are not automatically enabled/disabled or started/stopped.
And when either cronie or fcrontab is installed, the other one gets uninstalled.

To replace cronie with fcron (as root):

    # systemctl stop cronie
    # pacman -Syu                    Note: usually, choose "yes" to replace or delete packages, if asked
    # pacman -S fcron
    # systemctl enable --now fcron

To check (as non-root here):

    $ pacman -Qi cronie fcron
    $ systemctl status cronie fcron

**Comment by buhtz** [comment] 2024-09-03 07:01
And editing the (f)crontab file is then with `$ fcrontab -e` instead of `$ crontab -e`? Mhm... Why not creating a bash alias like `$ alias crontab=fcrontab`?
But OK, I get it. I will have a look at it.

**Comment by buhtz** [comment] 2024-09-03 08:43
I need to put my efforts on hold.

- Fcron upstream has extrem low health and [seems to be dead](https://github.com/yo8192/fcron/issues/34).
- Last upstream release was 3 years ago (2021).
- Fcron is not in Debian for years and the upstream maintainer agreed to that.

On the other hand I do see 4 BIT users asking for fcron. So I don't say know. I just lower the priority again and being open for extern contributions.

**Comment by willemw12** [comment] 2024-09-03 10:03
Cronie itself has "anacron" functionality: support for systems that are not running 24/7. This is/was one of the main reasons to use fcron, on laptops for example.

A quick look at Debian/Ubuntu shows that "anacron" is disabled ("./rules:19:CONFIG_OPTIONS += --disable-anacron" https://packages.ubuntu.com/noble/cronie). But that may get enabled in the future (https://wiki.debian.org/cron).

Supporting fcron may need more work than originally proposed: "These crontabs are stored in a binary format ... Any scripts which ... edit user crontabs may need to be adjusted" (https://wiki.archlinux.org/title/Cron#Fcron). EDIT: not if BIT uses `fcron/cron -e` to change the crontab, instead of changing the crontab file directly.

Issue https://github.com/bit-team/backintime/issues/1255 mentions "Repeatedly (anacron)". Does that not solve this issue here? Some fcron users would have to do a `sudo ln -s /usr/bin/fcron /usr/bin/cron` as a workaround then.

**Comment by buhtz** [comment] 2024-09-03 10:23
Do I understand you correct that "fcron" isn't needed anymore because BIT does offer an anacron-like behavior?

**Comment by willemw12** [comment] 2024-09-03 11:33
> Do I understand you correct that "fcron" isn't needed anymore because BIT does offer an anacron-like behavior?

Doesn't it? It looked like maybe that could be the case. Something that BIT could perhaps check and evaluate? In my previous comment I just raised some points.

There are two main issues:

1) fcron support. The fcron/cron symlink workaround, that the user has to create, might be an alternative solution.
2) support for machines that don't run 24/7 (laptop, ...), Does "Repeatedly (anacron)" guarantee backups when you switch the machine back on (with and without the symlink workaround)?

**Comment by buhtz** [comment] 2024-09-03 12:22
> > Do I understand you correct that "fcron" isn't needed anymore because BIT does offer an anacron-like behavior?
> 
> Doesn't it?

I don't know. I am not into all details and never used fcron. I just need to decide if we can close the issue or need to work on it. 😄 

> 1. fcron support. The fcron/cron symlink workaround, that the user has to create, might be an alternative solution.

I don't see how the symlink thing could work. 

> 2. support for machines that don't run 24/7 (laptop, ...), Does "Repeatedly (anacron)" guarantee backups when you switch the machine back on (with and without the symlink workaround)?

If cron is used, yes it is guaranteed. The "Repeatedly (anacron)" is implemented not with anacron but with cron just starting BIT all 15 minutes. BIT then itself determine if it is time to start the new snapshot or not.

**Comment by willemw12** [comment] 2024-09-03 13:08
The "anacron" functionality is basically covered by "Repeatedly (anacron)".

Doesn't that 15 minute cronjob not keep the laptop from going in suspend/sleep/hibernate mode? So maybe that's not always useful on a laptop.

The symlink workaround should work, but does not cover point 2. in the original proposal (ignore the stderr output).

**Comment by buhtz** [comment] 2024-09-03 13:38
Sorry, I might be bit dump here? 😆 
Did I understand it correct that someone want to use fcron because they need an anacron-like behavior?
But BIT does offer an anacron-like behavior. So fcron is not needed anymore.

Or do I make it to easy?

**Comment by willemw12** [comment] 2024-09-03 15:52
At least on Arch, as you already have seen, you cannot have both fcron and cronie installed at the same time. For example, laptop users, on Arch, may already have fcron installed (mainly for the "anacron" functionality for their whole system, not just for BIT).

In that case, what are the options for those users to have automated BIT backups? A custom systemd timer+service, a background daemon or fcron support in BIT.

**Comment by buhtz** [comment] 2024-09-03 16:39
Thank you for your patience with me. :smiley: 

> For example, laptop users, on Arch, may already have fcron installed (mainly for the "anacron" functionality for their whole system, not just for BIT).

"anacron" doesn't work with Laptops well? Because of the suspend problem?
Laptop users with Arch: That would be a huge user group and increase the importance of that issue.

OK, I have a PR working in progress...

**Comment by xelvinc** [comment] 2024-09-04 06:39
I have also fcron installed because my system is not continuously running and for other extra features beyond the standard cron.

**Comment by buhtz** [comment] 2024-09-05 05:37
Can please someone test PR #1862 and give me feedback. Thanks in advance.

**Comment by willemw12** [comment] 2024-09-05 08:08
Tested it on Arch. Fcron works in BIT.

Fcron complains about missing `sendmail` program, but that is expected because fcron was not fully configured in the test environment.

Note that if a job exits with a return status other than 0, then the job with the exit status is logged (by journald):

    Job '...; return 1' started for user ... (pid ...)

So BIT should try to make sure that it returns with exit status 0 if there was no error. The default generated job did return with exit status 0:

    #Back In Time system entry, this will be edited by the gui:
    */5 * * * * /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job >/dev/null

**Comment by buhtz** [comment] 2024-09-05 08:12
Thank you for testing. [Will merge it in some days if no new restrictions coming up](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#what-happens-after-you-opened-a-pull-request-PR).

**Comment by xelvinc** [comment] 2024-09-05 09:07
Is there an easy way to test it? I'm not familiar with testing. I'm currently using version 1.3.3, there is no schedule.py. On my system, the readCrontab function is in tools.py.

**Comment by buhtz** [comment] 2024-09-05 10:26
> Is there an easy way to test it?

It is never easy. 🤣 I wouldn't recommend it to test it on your productive system if you are not familiar with the procedures of testing development versions. In your case you could install a virtual machine (via Virtual Box) and test it there). Because it is not yet merged you have to clone my fork and the related branch: https://github.com/buhtz/backintime/tree/feat/610fcron and installing it using the [install instructions](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#build--install).

But you don't have to of course. If you want to learn I can provide you more details and step by step instructions.

**Comment by xelvinc** [comment] 2024-09-05 11:33
Ok, that would be a bit too much hassle for the moment.

**Closed** 2024-09-13 06:49 UTC
Labels: Scheduling, Feature, HELP-WANTED
