### ISSUE TITLE
Error notifications when backup disk is make gnome shell unresponsive

### ISSUE THREAD

**Issue by Coshibu** [bit-team/backintime#1039] opened 2019-11-01 08:32 UTC
When a large backup will run out of space on the backup disks, BIT sends 'copy' and 'write' errors to the shell. On ubuntu 18.04 this  makes the shell slow down and almost unresponsive after a while.

This may not really be a BIT problem, but i am posting it anyway.

**Comment by artnaseef** [comment] 2021-09-09 17:03
I have this problem - as commented on another issue requesting a rate limit to the notifications.  I assert that spamming the system with endless notifications is an anti-pattern and request a rate-limit, or similar, solution.

**Comment by buhtzz** [comment] 2022-09-25 13:02
Tag: Feature, Bug, Medium, External

There are some other relevant issues around. This is about the two topics disk size limits and notifications.

**Comment by emtiu** [comment] 2022-10-08 22:49
Closing as duplicate of #1125.

**Closed by emtiu** 2022-10-08 22:49 UTC
