### ISSUE TITLE
crashes, when trying to diff

### ISSUE THREAD

**Issue by freder** [bit-team/backintime#1083] opened 2020-05-03 19:05 UTC
version 1.2.1

every time I do either of these, the program crashes:
- view → snapshots → diff
- view → snapshots → diff options → ok

```
5/3/20 8:57 PM	python	Traceback (most recent call last):
File "/usr/share/backintime/qt/snapshotsdialog.py", line 339, in btnDiffClicked
	path1 = self.parent.tmpCopy(path1, sid1)
File "/usr/share/backintime/qt/app.py", line 1266, in tmpCopy
	shutil.copytree(full_path, tmp_file)
File "/usr/lib/python3.8/shutil.py", line 554, in copytree
	return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
File "/usr/lib/python3.8/shutil.py", line 455, in _copytree
	os.makedirs(dst, exist_ok=dirs_exist_ok)
File "/usr/lib/python3.8/os.py", line 223, in makedirs
	mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/tmp/tmpkt7c6arq_20200503-191846-429/'
```

**Comment by frithrah** [comment] 2021-10-17 17:46
For the record, I have the same consistent crash but a different error...

```
Traceback (most recent call last):
  File "/usr/share/backintime/qt/snapshotsdialog.py", line 76, in accept
    diffCmd = str(self.editCmd.text().toUtf8())
AttributeError: 'str' object has no attribute 'toUtf8'
```

**Comment by buhtzz** [comment] 2022-09-25 11:59
Tag: Qt

**Comment by buhtzz** [comment] 2022-09-25 12:40
> For the record, I have the same consistent crash but a different error...
> 
> ```
> Traceback (most recent call last):
>   File "/usr/share/backintime/qt/snapshotsdialog.py", line 76, in accept
>     diffCmd = str(self.editCmd.text().toUtf8())
> AttributeError: 'str' object has no attribute 'toUtf8'
> ```

This is different from the opening report. Your problem is fixed in the current upstream version. That version is not released yet.

**Comment by emtiu** [comment] 2022-10-14 11:07
Possible duplicate of #1197?

**Comment by buhtz** [comment] 2023-03-19 08:59
Dear @freder ,
can you report back please if you are still able to reproduce your problem with the latest version (1.3.3) of BIT?

**Comment by buhtz** [comment] 2023-06-29 08:21
I've seen this, too in 1.3.4-dev. But again I can't reproduce it for sure.

But I do see a trail and need to further investigate the code.

https://github.com/bit-team/backintime/blob/72ced78a5ee3c7803e0cba16e11698af4d883535/qt/snapshotsdialog.py#L342-L347

There are two situations / variants of calls to `tmpCopy()`. But they are not exclusive to each other. It might happen in rare cases that `tmpCopy()` is called twice. But there is also high evidence that I'm wrong here. I travled _Back In Time_ to version 1.2.1 (the Issue opener used) and had a look at [line 339](https://github.com/bit-team/backintime/blob/27fa0c5d4db7da3757f3f5e6afa4cc0a7214b010/qt/snapshotsdialog.py#L339) which was reported in his traceback. This line number refers to the first call of `tmpCopy()` not the second.

**Comment by buhtz** [comment] 2024-04-17 08:05
Frederic we are currently working (#1682) on the snapshots dialog and its compare feature. Can you somehow reproduce the problem with a newer version of BIT and can you provide us the steps to reproduce?

**Comment by buhtz** [comment] 2024-09-10 14:22
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,

**Closed by buhtz** 2024-09-10 14:22 UTC
Labels: Bug, Feedback, Heisenbug
