### ISSUE TITLE
Exclude files not belonging to me?

### ISSUE THREAD

**Issue by fujisan43** [bit-team/backintime#975] opened 2019-02-21 16:49 UTC
Would it be possible to exclude files that do not belong to me?
I sometimes store files belonging to root in my home directory and would like not to back them up, otherwise I gel plenty of error messages.

Fuji

**Comment by bentolor** [comment] 2019-02-22 07:54
@fujisan43 AFAIK not generally, only excluding them individually / by folder. Just right-click in the file view and chose "Exclude".

I stumble over sometimes, too esp. after I faulty missed to run a `sudo` command without the `-H´ option and fix it via `sudo chown -R $USER:$USER ~`. Generally its rather [common opinion,  that root-own files should be placed rather somewhere else](https://superuser.com/q/495937).

**Comment by buhtzz** [comment] 2022-09-26 09:04
@fujisan43 There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feature, Support, Discussion

Not sure if such advanced filtering is possible on rsync level. If so we could keep that as a far away feature request.

**Comment by emtiu** [comment] 2022-10-09 10:46
Closing, because the question was answered.

**Closed by emtiu** 2022-10-09 10:46 UTC

**Comment by fujisan43** [comment] 2022-10-11 08:59
Sorry. I'm not use backintime anymore.
