### ISSUE TITLE
[Usage question] Backup files I don't want to keep in original location?

### ISSUE THREAD

**Issue by frontierpsycho** [bit-team/backintime#1147] opened 2021-03-28 13:48 UTC
Hello,

I would like to get some confirmation from other users or any devs of BiT that this is a solid strategy, to avoid losing files down the line. I think there's no BiT feature to do this automatically, if there is one, let me know. 

### The issue

I have a folder with files and subfolders that are used in varying degrees. Here's a diagram to make it easy to understand: 

```
tobackup/
       |- frequently/
       |- infrequently/
```

Let's say I have a folder called `tobackup/`, that contains subfolder `frequent/` that I use frequently and subfolder  `infrequently/` which I rarely touch, but want to keep for those few cases when I use it, or for the possibility that I will start using it more frequently. 

I'd like to keep `infrequently/` only in backup (on an external disk), and restore it when needed.

### My current solution

My impression was that BiT is not suitable to back up `tobackup/`, since it keeps the live copy and the backup in sync. For this reason, my strategy so far has been to manually copy `tobackup/` to an external drive. This does not keep history, but it allows me to delete `infreqntly/` from the source directory and only keep it on my external drive, which has a lot more space.

### A possible solution involving BiT

My question then is this: I thought of a strategy to do this with BiT, and I wonder whether there's any problems that I don't see.

The strategy is: make a BiT profile for `tobackup/`, take a snapshot and name it "Complete". Instruct BiT to never delete named snapshots. Then delete `infrequently/` from the source.

The next time I add things to `tobackup/` and want to back it up, the next snapshot will of course also delete `infrequently/` from the new snapshot, as it's not present in the source. It will have the new files, though, so my updates will be somewhat spread out amongst snapshots.

Every now and then, I can restore `infrequently/` (and any other files I've deleted for the same reason) to source, and then make a new snapshot and name it "Complete". This will be a bit more manual than just taking a snapshot every now and then, but it's also more practical and organized than periodically copying the entire `tobackup/` folder to my external drive. 

Thoughts?

**Comment by plgruener** [comment] 2021-06-30 13:57
> My impression was that BiT is not suitable to back up tobackup/, since it keeps the live copy and the backup in sync.

No, BackInTime is for *backup*, not for synchronisation. That means while your most current backup is identical to your "working copy"/hard drive, BiT does not alter past backups (if you have not set one of the delete options, that is).

Meaning: If you backup your whole `tobackup` (with both `frequently` and `infrequently`) into `backup_date1`, then delete `infrequently` from your main hard drive, then backup again `tobackup` (which is now only `frequently`) into `backup_date2`, then your second backup will only contain `frequently`, but `infrequently` will still be in the first backup. (Again, you have to be careful to not set options to auto-delete backups after a certain time period.)

Instead of the manual copying or renaming you could just have two BiT profiles, one which includes only `infrequently` and one which excludes it, both with different backup intervals and auto-deletion options.

BUT: a backup is only a real backup if it is the second (or third) copy of data. By deleting `infrequently` from your harddrive, you make your external hard drive your single point of failure, and it's not a question of if, but *when* hard drives will eventually fail. If you haven't done so, consider at least getting a second ext. HDD as backup medium.

**Comment by frontierpsycho** [comment] 2021-06-30 21:09
The problem is that I actually tried it with some test files, it seemed to work, and then I created a real profile and ended up losing some files :-/ I'm not sure what I did wrong, but I can perhaps try it again more carefully.

**Comment by emtiu** [comment] 2022-09-22 22:19
Hi, thanks for sharing your thoughts, it was an interesting read. I agree with @plgruener that this would be a _very_ non-intended use of backintime, and therefore asking for trouble.

At first glance, you plan seems sound, because the named snapshot will stay, containing the `infrequently` data you want it to hold.

But then, do you really want your only copy of these files under the (semi-)automatic control of a tool that was designed to work differently? Probably not :)

I'm closing this issue, but feel free to continue the discussion.

**Closed by emtiu** 2022-09-22 22:19 UTC

**Comment by frontierpsycho** [comment] 2022-09-23 00:16
Right, sorry for now following up here. I ended up using LuckyBackup for this use case after all, which has a relevant option. It doesn't have a great UI but it supports my use case just fine. I am using backintime for my main backup, so I can have snapshots and a clean UI, and LuckyBackup for everything I only need one copy of and to be able to delete files from the source. Good that you closed the issue, it's essentially been solved.
