### ISSUE TITLE
Failed to write new crontab

### ISSUE THREAD

**Issue by dx486** [bit-team/backintime#560] opened 2016-03-26 12:04 UTC
I get "Failed to write new crontab" error when saving new profiles or changing schedules of existing ones.

(BIT 1.1.12 on debian 8.3 with Gnome)

Update: I have just managed to add a new profile. I don't know what has changed.

**Comment by Germar** [comment] 2016-03-26 17:56
Could you please run `backintime-qt4` from commandline, change schedules again and post the output?

**Comment by dx486** [comment] 2016-03-28 07:06
I don't get the same message now. I will do this when it starts again.

**Comment by bitpick** [comment] 2016-06-13 08:21
Had the same problem and found at least one possible solution:
This might be a permission problem in the system. Take a shell and try `crontab -l`
If you get something like this 
`
cannot chdir(/var/spool/cron), bailing out.
/var/spool/cron: Permission denied
`
then add yourself (username) to the cron group. On some systems you are not automatically member of this group. This change will take effect after new login...

**Comment by Germar** [comment] 2016-06-14 12:21
Thanks @bitpick. I'll close this as it is not a bug in BackInTime

**Closed by Germar** 2016-06-14 12:21 UTC
Labels: question
