### ISSUE TITLE
SSH fail connecting to a Sftp only port

### ISSUE THREAD

**Issue by feint9** [bit-team/backintime#1194] opened 2021-11-10 13:07 UTC
Hi,

Ubuntu 20.04 LTS full updated
BackinTime 1.3.1 from ppa_bit_team_stable-focal-main

My storage has sftp on port that accepts sftp only, does not accept ssh.

From bash i can "sftp -P 7777 user@ip" and accpets the public key from my user added to the storage, it does not ask for a password for the user, nor a passfrase for the key i have setup the ssh key without passfrase.

But from BackinTIme, after i select SSH mode i fill the ip, port, user with the user from the storage, path, priv key from my local user, ssh private key i leave it in blank, click on ok.

After that i get a popup "Would you like to copy your public ssh key to the remote host to enable password-less login?" and it does no dif if i say yes or no. 

Just nothing happens and no backup is done.

Also i cannot save my profile, the bottons area grayed out.

**Comment by buhtz** [comment] 2023-05-30 14:31
Dear @feint9 ,
is this issue is still relevant for you?

I don't understand why `sftp` is involved here. BIT doesn't use it. BIT do use `rsync` over `ssh`.

Are you able to do `ssh user@ip` without being asked for a password?

**Comment by buhtz** [comment] 2023-08-01 11:00
Dear feint9 ,
can you provide us some more information please and answer my latest question.
Can you reproduce the problem with the latest BIT version 1.3.3?

Without feedback I need to close the issue in the near future because we can not reproduce it.

**Comment by buhtz** [comment] 2023-09-26 17:56
Feel free to re-open if you have new information.

**Closed by buhtz** 2023-09-26 17:56 UTC
Labels: Bug
