### ISSUE TITLE
New name Icon?

### ISSUE THREAD

**Issue by ElvisPresly** [bit-team/backintime#568] opened 2016-04-11 07:31 UTC
Hi. You can change an icon name to another for example on "backintime". With a real name difficulties for creation of icon of pak appear. Thanks

https://github.com/numixproject/numix-icon-theme-circle/issues/2956

**Comment by Germar** [comment] 2016-04-12 20:17
BackInTime has no Icon yet. As soon as we have one, it will have a unique name, of course.

This is a duplicate of #215

**Closed by Germar** 2016-04-12 20:17 UTC
Labels: duplicate
