### ISSUE TITLE
[bug] Backs up `.git/objects` file even if there is no change

### ISSUE THREAD

**Issue by lamyergeier** [bit-team/backintime#1950] opened 2024-11-28 06:26 UTC
# `backintime --diagnostics`

``` json
{
    "backintime": {
        "name": "Back In Time",
        "version": "1.5.3",
        "running-as-root": false,
        "latest-config-version": 6,
        "local-config-file": "/home/UsernameReplaced/.config/backintime/config",
        "local-config-file-found": true,
        "global-config-file": "/etc/backintime/config",
        "global-config-file-found": false,
        "started-from": "/usr/share/backintime/common",
        "user-callback": "/home/UsernameReplaced/.config/backintime/user-callback",
        "keyring-supported": true
    },
    "host-setup": {
        "OS": {
            "/etc/os-release": "Fedora Linux 41 (Workstation Edition)",
            "/etc/system-release-cpe": "cpe:/o:fedoraproject:fedora:41\n",
            "/etc/redhat-release": "Fedora release 41 (Forty One)\n",
            "/etc/fedora-release": "Fedora release 41 (Forty One)\n",
            "/etc/system-release": "Fedora release 41 (Forty One)\n"
        },
        "platform": "Linux-6.11.8-300.fc41.x86_64-x86_64-with-glibc2.40",
        "system": "Linux #1 SMP PREEMPT_DYNAMIC Thu Nov 14 20:37:39 UTC 2024",
        "display-system": "wayland",
        "locale": "en_GB, UTF-8",
        "PATH": "/home/UsernameReplaced/opt/bin:/home/UsernameReplaced/.local/bin:/home/UsernameReplaced/opt/.nvm/versions/node/v22.11.0/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/UsernameReplaced/.cargo/bin:/home/UsernameReplaced/.cabal/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/UsernameReplaced/go/bin:/home/UsernameReplaced/.ruby/bin:/home/UsernameReplaced/opt/Git/fzf/bin",
        "RSYNC_OLD_ARGS": "(not set)",
        "RSYNC_PROTECT_ARGS": "(not set)"
    },
    "python-setup": {
        "python": "3.13.0 main Oct  8 2024 00:00:00 CPython GCC 14.2.1 20240912 (Red Hat 14.2.1-3)",
        "python-executable": "/usr/bin/python3",
        "python-executable-symlink": true,
        "python-executable-resolved": "/usr/bin/python3.13",
        "sys.path": [
            "/usr/share/backintime/qt/plugins",
            "/usr/share/backintime/common/plugins",
            "/usr/share/backintime/plugins",
            "/usr/share/backintime/common",
            "/usr/lib64/python313.zip",
            "/usr/lib64/python3.13",
            "/usr/lib64/python3.13/lib-dynload",
            "/usr/lib64/python3.13/site-packages",
            "/usr/lib/python3.13/site-packages"
        ],
        "qt": {
            "Version": "PyQt 6.8.0.dev2410141303 / Qt 6.8.0",
            "Theme": "Papirus",
            "Theme Search Paths": [
                "/home/UsernameReplaced/.icons",
                "/home/UsernameReplaced/.local/share/icons",
                "/home/linuxbrew/.linuxbrew/share/icons",
                "/home/UsernameReplaced/.local/share/flatpak/exports/share/icons",
                "/var/lib/flatpak/exports/share/icons",
                "/usr/local/share/icons",
                "/usr/share/icons",
                ":/icons"
            ],
            "Fallback Theme": "",
            "Fallback Search Paths": []
        }
    },
    "external-programs": {
        "rsync": {
            "version": "3.3.0",
            "protocol": "31.0",
            "capabilities": "file_bits: 64; inum_bits: 64; timestamp_bits: 64; long_int_bits: 64; socketpairs: True; symlinks: True; symtimes: True; hardlinks: True; hardlink_specials: True; hardlink_symlinks: True; IPv6: True; atimes: True; batchfiles: True; inplace: True; append: True; ACLs: True; xattrs: True; secluded_args: optional; iconv: True; prealloc: True; stop_at: True; crtimes: False",
            "optimizations": "SIMD_roll: True; asm_roll: False; openssl_crypto: True; asm_MD5: False",
            "checksum_list": "xxh128, xxh3, xxh64, md5, md4, sha1, none",
            "compress_list": "zstd, lz4, zlibx, zlib, none",
            "daemon_auth_list": "sha512, sha256, sha1, md5, md4"
        },
        "ssh": "OpenSSH_9.8p1, OpenSSL 3.2.2 4 Jun 2024",
        "sshfs": "3.7.3",
        "encfs": "1.9.5",
        "shell": "/bin/bash",
        "shell-version": "GNU bash, version 5.2.32(1)-release (x86_64-redhat-linux-gnu)"
    }
}
```

# ~/.config/backintime/config

```txt
config.version=6
global.use_flock=true
internal.manual_starts_countdown=-1
profile1.qt.last_path=/mnt/Documents/Git
profile1.qt.places.SortColumn=1
profile1.qt.places.SortOrder=SortOrder.AscendingOrder
profile1.qt.settingsdialog.exclude.SortColumn=1
profile1.qt.settingsdialog.exclude.SortOrder=SortOrder.AscendingOrder
profile1.qt.settingsdialog.include.SortColumn=1
profile1.qt.settingsdialog.include.SortOrder=SortOrder.AscendingOrder
profile1.schedule.custom_time=8,12,18,23
profile1.schedule.day=1
profile1.schedule.debug=false
profile1.schedule.mode=4
profile1.schedule.repeatedly.period=1
profile1.schedule.repeatedly.unit=20
profile1.schedule.time=0
profile1.schedule.weekday=7
profile1.snapshots.backup_on_restore.enabled=true
profile1.snapshots.bwlimit.enabled=false
profile1.snapshots.bwlimit.value=3000
profile1.snapshots.continue_on_errors=true
profile1.snapshots.copy_links=false
profile1.snapshots.copy_unsafe_links=false
profile1.snapshots.cron.ionice=true
profile1.snapshots.cron.nice=true
profile1.snapshots.cron.redirect_stderr=false
profile1.snapshots.cron.redirect_stdout=true
profile1.snapshots.dont_remove_named_snapshots=true
profile1.snapshots.exclude.1.value=.gvfs
profile1.snapshots.exclude.2.value=.cache/*
profile1.snapshots.exclude.3.value=.thumbnails*
profile1.snapshots.exclude.4.value=.local/share/[Tt]rash*
profile1.snapshots.exclude.5.value=*.backup*
profile1.snapshots.exclude.6.value=*~
profile1.snapshots.exclude.7.value=.dropbox*
profile1.snapshots.exclude.8.value=/proc/*
profile1.snapshots.exclude.9.value=/sys/*
profile1.snapshots.exclude.10.value=/dev/*
profile1.snapshots.exclude.11.value=/run/*
profile1.snapshots.exclude.12.value=/etc/mtab
profile1.snapshots.exclude.13.value=/var/cache/apt/archives/*.deb
profile1.snapshots.exclude.14.value=lost+found/*
profile1.snapshots.exclude.15.value=/tmp/*
profile1.snapshots.exclude.16.value=/var/tmp/*
profile1.snapshots.exclude.17.value=/var/backups/*
profile1.snapshots.exclude.18.value=.Private
profile1.snapshots.exclude.19.value=/swapfile
profile1.snapshots.exclude.20.value=SingletonLock
profile1.snapshots.exclude.21.value=SingletonCookie
profile1.snapshots.exclude.22.value=lock
profile1.snapshots.exclude.23.value=.[Tt]rash
profile1.snapshots.exclude.24.value=.Backup
profile1.snapshots.exclude.25.value=.Commit
profile1.snapshots.exclude.26.value=.Rendered
profile1.snapshots.exclude.27.value=*.gen.*
profile1.snapshots.exclude.28.value=node_modules
profile1.snapshots.exclude.bysize.enabled=false
profile1.snapshots.exclude.bysize.value=500
profile1.snapshots.exclude.size=28
profile1.snapshots.include.1.type=0
profile1.snapshots.include.1.value=/mnt/Documents/Git
profile1.snapshots.include.2.type=0
profile1.snapshots.include.2.value=/mnt/Documents/Mobile/Git
profile1.snapshots.include.size=2
profile1.snapshots.local.nocache=false
profile1.snapshots.local.password.save=false
profile1.snapshots.local.password.use_cache=true
profile1.snapshots.local_encfs.path=/mnt/Backup
profile1.snapshots.log_level=3
profile1.snapshots.min_free_inodes.enabled=true
profile1.snapshots.min_free_inodes.value=2
profile1.snapshots.min_free_space.enabled=true
profile1.snapshots.min_free_space.unit=20
profile1.snapshots.min_free_space.value=1
profile1.snapshots.mode=local
profile1.snapshots.no_on_battery=false
profile1.snapshots.notify.enabled=true
profile1.snapshots.one_file_system=false
profile1.snapshots.path=/mnt/Backup
profile1.snapshots.path.host=lamyer
profile1.snapshots.path.profile=Local
profile1.snapshots.path.user=lamy
profile1.snapshots.preserve_acl=false
profile1.snapshots.preserve_xattr=false
profile1.snapshots.remove_old_snapshots.enabled=true
profile1.snapshots.remove_old_snapshots.unit=80
profile1.snapshots.remove_old_snapshots.value=10
profile1.snapshots.rsync_options.enabled=false
profile1.snapshots.rsync_options.value=
profile1.snapshots.smart_remove=false
profile1.snapshots.smart_remove.keep_all=2
profile1.snapshots.smart_remove.keep_one_per_day=7
profile1.snapshots.smart_remove.keep_one_per_month=24
profile1.snapshots.smart_remove.keep_one_per_week=4
profile1.snapshots.smart_remove.run_remote_in_background=false
profile1.snapshots.ssh.check_commands=true
profile1.snapshots.ssh.check_ping=true
profile1.snapshots.ssh.cipher=default
profile1.snapshots.ssh.host=
profile1.snapshots.ssh.ionice=false
profile1.snapshots.ssh.nice=false
profile1.snapshots.ssh.nocache=false
profile1.snapshots.ssh.path=
profile1.snapshots.ssh.port=22
profile1.snapshots.ssh.prefix.enabled=false
profile1.snapshots.ssh.prefix.value=PATH=/opt/bin:/opt/sbin:\$PATH
profile1.snapshots.ssh.private_key_file=/home/lamy/.ssh/id_rsa
profile1.snapshots.ssh.proxy_host=
profile1.snapshots.ssh.proxy_host_port=
profile1.snapshots.ssh.proxy_user=
profile1.snapshots.ssh.user=lamy
profile1.snapshots.take_snapshot_regardless_of_changes=false
profile1.snapshots.use_checksum=false
profile1.snapshots.user_backup.ionice=false
profile2.name=Media
profile2.qt.last_path=/mnt/Media/Pictures
profile2.qt.places.SortColumn=1
profile2.qt.places.SortOrder=SortOrder.AscendingOrder
profile2.qt.settingsdialog.exclude.SortColumn=1
profile2.qt.settingsdialog.exclude.SortOrder=SortOrder.AscendingOrder
profile2.qt.settingsdialog.include.SortColumn=1
profile2.qt.settingsdialog.include.SortOrder=SortOrder.AscendingOrder
profile2.schedule.custom_time=8,12,18,23
profile2.schedule.day=1
profile2.schedule.debug=false
profile2.schedule.mode=27
profile2.schedule.repeatedly.period=1
profile2.schedule.repeatedly.unit=20
profile2.schedule.time=0
profile2.schedule.weekday=7
profile2.snapshots.backup_on_restore.enabled=true
profile2.snapshots.bwlimit.enabled=false
profile2.snapshots.bwlimit.value=3000
profile2.snapshots.continue_on_errors=true
profile2.snapshots.copy_links=false
profile2.snapshots.copy_unsafe_links=false
profile2.snapshots.cron.ionice=true
profile2.snapshots.cron.nice=true
profile2.snapshots.cron.redirect_stderr=false
profile2.snapshots.cron.redirect_stdout=true
profile2.snapshots.dont_remove_named_snapshots=true
profile2.snapshots.exclude.1.value=.gvfs
profile2.snapshots.exclude.2.value=.cache/*
profile2.snapshots.exclude.3.value=.thumbnails*
profile2.snapshots.exclude.4.value=.local/share/[Tt]rash*
profile2.snapshots.exclude.5.value=*.backup*
profile2.snapshots.exclude.6.value=*~
profile2.snapshots.exclude.7.value=.dropbox*
profile2.snapshots.exclude.8.value=/proc/*
profile2.snapshots.exclude.9.value=/sys/*
profile2.snapshots.exclude.10.value=/dev/*
profile2.snapshots.exclude.11.value=/run/*
profile2.snapshots.exclude.12.value=/etc/mtab
profile2.snapshots.exclude.13.value=/var/cache/apt/archives/*.deb
profile2.snapshots.exclude.14.value=lost+found/*
profile2.snapshots.exclude.15.value=/tmp/*
profile2.snapshots.exclude.16.value=/var/tmp/*
profile2.snapshots.exclude.17.value=/var/backups/*
profile2.snapshots.exclude.18.value=.Private
profile2.snapshots.exclude.19.value=/swapfile
profile2.snapshots.exclude.20.value=SingletonLock
profile2.snapshots.exclude.21.value=SingletonCookie
profile2.snapshots.exclude.22.value=lock
profile2.snapshots.exclude.23.value=.stversions
profile2.snapshots.exclude.24.value=.[Tt]rash
profile2.snapshots.exclude.25.value=.Backup
profile2.snapshots.exclude.26.value=.Commit
profile2.snapshots.exclude.27.value=.Rendered
profile2.snapshots.exclude.28.value=*.gen.*
profile2.snapshots.exclude.bysize.enabled=false
profile2.snapshots.exclude.bysize.value=500
profile2.snapshots.exclude.size=28
profile2.snapshots.include.1.type=0
profile2.snapshots.include.1.value=/mnt/Media/Music
profile2.snapshots.include.2.type=0
profile2.snapshots.include.2.value=/mnt/Media/Pictures
profile2.snapshots.include.size=2
profile2.snapshots.local.nocache=false
profile2.snapshots.local.password.save=false
profile2.snapshots.local.password.use_cache=true
profile2.snapshots.local_encfs.path=/run/media/lamy/Crucial/Backup
profile2.snapshots.log_level=3
profile2.snapshots.min_free_inodes.enabled=true
profile2.snapshots.min_free_inodes.value=2
profile2.snapshots.min_free_space.enabled=true
profile2.snapshots.min_free_space.unit=20
profile2.snapshots.min_free_space.value=1
profile2.snapshots.mode=local
profile2.snapshots.no_on_battery=false
profile2.snapshots.notify.enabled=true
profile2.snapshots.one_file_system=false
profile2.snapshots.path=/run/media/lamy/Crucial/Backup
profile2.snapshots.path.host=lamyer
profile2.snapshots.path.profile=Media
profile2.snapshots.path.user=lamy
profile2.snapshots.path.uuid=a25390fa-d3ae-4466-8086-f8e39ad8c0cf
profile2.snapshots.preserve_acl=false
profile2.snapshots.preserve_xattr=false
profile2.snapshots.remove_old_snapshots.enabled=true
profile2.snapshots.remove_old_snapshots.unit=80
profile2.snapshots.remove_old_snapshots.value=10
profile2.snapshots.rsync_options.enabled=false
profile2.snapshots.rsync_options.value=
profile2.snapshots.smart_remove=false
profile2.snapshots.smart_remove.keep_all=2
profile2.snapshots.smart_remove.keep_one_per_day=7
profile2.snapshots.smart_remove.keep_one_per_month=24
profile2.snapshots.smart_remove.keep_one_per_week=4
profile2.snapshots.smart_remove.run_remote_in_background=false
profile2.snapshots.ssh.check_commands=true
profile2.snapshots.ssh.check_ping=true
profile2.snapshots.ssh.cipher=default
profile2.snapshots.ssh.host=
profile2.snapshots.ssh.ionice=false
profile2.snapshots.ssh.nice=false
profile2.snapshots.ssh.nocache=false
profile2.snapshots.ssh.path=
profile2.snapshots.ssh.port=22
profile2.snapshots.ssh.prefix.enabled=false
profile2.snapshots.ssh.prefix.value=PATH=/opt/bin:/opt/sbin:\$PATH
profile2.snapshots.ssh.private_key_file=/home/lamy/.ssh/id_rsa
profile2.snapshots.ssh.proxy_host=
profile2.snapshots.ssh.proxy_host_port=
profile2.snapshots.ssh.proxy_user=
profile2.snapshots.ssh.user=lamy
profile2.snapshots.take_snapshot_regardless_of_changes=false
profile2.snapshots.use_checksum=true
profile2.snapshots.user_backup.ionice=false
profile3.name=Data_document
profile3.qt.last_path=/home/lamy
profile3.qt.places.SortColumn=1
profile3.qt.places.SortOrder=SortOrder.AscendingOrder
profile3.qt.settingsdialog.exclude.SortColumn=1
profile3.qt.settingsdialog.exclude.SortOrder=SortOrder.AscendingOrder
profile3.qt.settingsdialog.include.SortColumn=1
profile3.qt.settingsdialog.include.SortOrder=SortOrder.AscendingOrder
profile3.schedule.custom_time=8,12,18,23
profile3.schedule.day=1
profile3.schedule.debug=false
profile3.schedule.mode=27
profile3.schedule.repeatedly.period=1
profile3.schedule.repeatedly.unit=20
profile3.schedule.time=0
profile3.schedule.weekday=7
profile3.snapshots.backup_on_restore.enabled=true
profile3.snapshots.bwlimit.enabled=false
profile3.snapshots.bwlimit.value=3000
profile3.snapshots.continue_on_errors=true
profile3.snapshots.copy_links=false
profile3.snapshots.copy_unsafe_links=false
profile3.snapshots.cron.ionice=true
profile3.snapshots.cron.nice=true
profile3.snapshots.cron.redirect_stderr=false
profile3.snapshots.cron.redirect_stdout=true
profile3.snapshots.dont_remove_named_snapshots=true
profile3.snapshots.exclude.1.value=.gvfs
profile3.snapshots.exclude.2.value=.cache/*
profile3.snapshots.exclude.3.value=.thumbnails*
profile3.snapshots.exclude.4.value=.local/share/[Tt]rash*
profile3.snapshots.exclude.5.value=*.backup*
profile3.snapshots.exclude.6.value=*~
profile3.snapshots.exclude.7.value=.dropbox*
profile3.snapshots.exclude.8.value=/proc/*
profile3.snapshots.exclude.9.value=/sys/*
profile3.snapshots.exclude.10.value=/dev/*
profile3.snapshots.exclude.11.value=/run/*
profile3.snapshots.exclude.12.value=/etc/mtab
profile3.snapshots.exclude.13.value=/var/cache/apt/archives/*.deb
profile3.snapshots.exclude.14.value=lost+found/*
profile3.snapshots.exclude.15.value=/tmp/*
profile3.snapshots.exclude.16.value=/var/tmp/*
profile3.snapshots.exclude.17.value=/var/backups/*
profile3.snapshots.exclude.18.value=.Private
profile3.snapshots.exclude.19.value=/swapfile
profile3.snapshots.exclude.20.value=SingletonLock
profile3.snapshots.exclude.21.value=SingletonCookie
profile3.snapshots.exclude.22.value=lock
profile3.snapshots.exclude.23.value=.Backup
profile3.snapshots.exclude.24.value=.Commit
profile3.snapshots.exclude.25.value=.Rendered
profile3.snapshots.exclude.26.value=.[Tt]rash
profile3.snapshots.exclude.27.value=*.gen.*
profile3.snapshots.exclude.28.value=lost+found
profile3.snapshots.exclude.bysize.enabled=false
profile3.snapshots.exclude.bysize.value=500
profile3.snapshots.exclude.size=28
profile3.snapshots.include.1.type=0
profile3.snapshots.include.1.value=/mnt/Data
profile3.snapshots.include.2.type=0
profile3.snapshots.include.2.value=/mnt/Documents
profile3.snapshots.include.3.type=0
profile3.snapshots.include.3.value=/home/lamy
profile3.snapshots.include.size=3
profile3.snapshots.local.nocache=false
profile3.snapshots.local.password.save=false
profile3.snapshots.local.password.use_cache=true
profile3.snapshots.local_encfs.path=/run/media/lamy/Crucial/Backup
profile3.snapshots.log_level=3
profile3.snapshots.min_free_inodes.enabled=true
profile3.snapshots.min_free_inodes.value=2
profile3.snapshots.min_free_space.enabled=true
profile3.snapshots.min_free_space.unit=20
profile3.snapshots.min_free_space.value=1
profile3.snapshots.mode=local
profile3.snapshots.no_on_battery=false
profile3.snapshots.notify.enabled=true
profile3.snapshots.one_file_system=false
profile3.snapshots.path=/run/media/lamy/Crucial/Backup
profile3.snapshots.path.host=lamyer
profile3.snapshots.path.profile=Data_document
profile3.snapshots.path.user=lamy
profile3.snapshots.path.uuid=a25390fa-d3ae-4466-8086-f8e39ad8c0cf
profile3.snapshots.preserve_acl=false
profile3.snapshots.preserve_xattr=false
profile3.snapshots.remove_old_snapshots.enabled=true
profile3.snapshots.remove_old_snapshots.unit=80
profile3.snapshots.remove_old_snapshots.value=10
profile3.snapshots.rsync_options.enabled=false
profile3.snapshots.rsync_options.value=
profile3.snapshots.smart_remove=false
profile3.snapshots.smart_remove.keep_all=2
profile3.snapshots.smart_remove.keep_one_per_day=7
profile3.snapshots.smart_remove.keep_one_per_month=24
profile3.snapshots.smart_remove.keep_one_per_week=4
profile3.snapshots.smart_remove.run_remote_in_background=false
profile3.snapshots.ssh.check_commands=true
profile3.snapshots.ssh.check_ping=true
profile3.snapshots.ssh.cipher=default
profile3.snapshots.ssh.host=
profile3.snapshots.ssh.ionice=false
profile3.snapshots.ssh.nice=false
profile3.snapshots.ssh.nocache=false
profile3.snapshots.ssh.path=
profile3.snapshots.ssh.port=22
profile3.snapshots.ssh.prefix.enabled=false
profile3.snapshots.ssh.prefix.value=PATH=/opt/bin:/opt/sbin:\$PATH
profile3.snapshots.ssh.private_key_file=/home/lamy/.ssh/id_rsa
profile3.snapshots.ssh.proxy_host=
profile3.snapshots.ssh.proxy_host_port=
profile3.snapshots.ssh.proxy_user=
profile3.snapshots.ssh.user=lamy
profile3.snapshots.take_snapshot_regardless_of_changes=false
profile3.snapshots.use_checksum=false
profile3.snapshots.user_backup.ionice=false
profiles=1:2:3
profiles.version=1
qt.last_path=/mnt/Documents/Git
qt.logview.height=1431
qt.logview.width=2256
qt.main_window.files_view.date_width=100
qt.main_window.files_view.name_width=100
qt.main_window.files_view.size_width=100
qt.main_window.files_view.sort.ascending=true
qt.main_window.files_view.sort.column=0
qt.main_window.height=1058
qt.main_window.main_splitter_left_w=354
qt.main_window.main_splitter_right_w=1063
qt.main_window.second_splitter_left_w=349
qt.main_window.second_splitter_right_w=695
qt.main_window.width=1421
qt.main_window.x=-11
qt.main_window.y=-49
```
# `backintime check-config` 

```
Back In Time
Version: 1.5.3

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.


 +--------------------------------+
 |  Check/prepare snapshot path   |
 +--------------------------------+
Check/prepare snapshot path: done

 +--------------------------------+
 |          Check config          |
 +--------------------------------+
Check config: done

 +--------------------------------+
 |        Install crontab         |
 +--------------------------------+
Install crontab: done

Config /home/lamy/.config/backintime/config profile 'Main profile' is fine.
```

# Issue

- I backup `/mnt/Documents/Git`, every 10 minutes. Even if I don't touch any file in `.git/objects/`   folder, it gets backed up every 10 minutes. 
- See complete snapshot log: https://0x0.st/XRSb.log
- a snippet of snapshot log

```
[C] cf...p..... mnt/Documents/Git/Data/Video/YouTube/.git/objects/00/4d95d4faf6c602491e91ae646d4a0d0ebb126d
[C] cf...p..... mnt/Documents/Git/Data/Video/YouTube/.git/objects/00/5a6d04e1eab8486f7785524cac741570814b36
[C] cf...p..... mnt/Documents/Git/Data/Video/YouTube/.git/objects/02/0e3025221272e3fd2f8eb8e279475543c47603
[C] cf...p..... mnt/Documents/Git/Data/Video/YouTube/.git/objects/02/a7a8d6b7ec0bd0516b526e85f25ef16bbf1d85
[C] cf...p..... mnt/Documents/Git/Data/Video/YouTube/.git/objects/02/dfd2c01e12eb6810527cff8481116019c2333b
[C] cf...p..... mnt/Documents/Git/Data/Video/YouTube/.git/objects/03/02e7df65a28b7bbec0dc82266709c6c4b73285
[C] cf...p..... mnt/Documents/Git/Data/Video/YouTube/.git/objects/03/0526aa0c59637f76fcd83d449b99a3f1c46f89
[C] cf...p..... mnt/Documents/Git/Data/Video/YouTube/.git/objects/03/056e624e07ad3adb96fac0a8986328d6677304
[C] cf...p..... mnt/Documents/Git/Data/Video/YouTube/.git/objects/03/20aa667e519b8547eb393fb7bda3ab9a298fc4
[C] cf...p..... mnt/Documents/Git/Data/Video/YouTube/.git/objects/03/2788c2ef1ebdecfd473864738dc4191a626703
```

**Comment by buhtz** [comment] 2024-11-28 08:13
Hello Lamyergeier,
thank your for reporting the bug.

This is an old and well known problem. See #988 for details. Currently there is no fix available.

Closing this as a duplicate of #988. Feel free to re-open and don't hesiate to ask further.

Regards,
Christian

**Closed as completed by buhtz** 2024-11-28 08:13 UTC
Labels: Bug
