### ISSUE TITLE
Backup speed not reported correctly

### ISSUE THREAD

**Issue by dinoboy197** [bit-team/backintime#512] opened 2016-01-02 18:29 UTC
Here is a screenshot of the backup status bar, showing incorrect transfer speed (network manager shows network activity maxing out just about 1 MB/s, but BIT reports speed 2.86 GB/s. This is a first time backup, so rsync shouldn't be showing a faster speed for matching bits already transferred.

![image](https://cloud.githubusercontent.com/assets/631178/12075662/71b8071e-b13b-11e5-9ef2-150931f19fdc.png)

Any chance I am misinterpreting the "speed" reported? (if not, I'll write a bug patch)

**Comment by Germar** [comment] 2016-01-02 19:00
Duplicate of #476

**Closed by Germar** 2016-01-02 19:00 UTC
Labels: duplicate

**Comment by dinoboy197** [comment] 2016-01-02 19:02
Whoops, I searched the issues for speed and that other issue didn't show up. Weird! Thanks for closing this dupe.

**Comment by dinoboy197** [comment] 2016-01-02 19:02
Oh, I get it - it didn't show up because the other issue was closed. I understand now!

**Comment by Germar** [comment] 2016-01-03 00:30
Sorry, my fault. Shouldn't have closed the other issue as it's not fixed. Even if there is not much I can do about it.

I'll reopen it.
