### ISSUE TITLE
Program hangs at "Working: Remove leftover 'new snapshot' folder from last run"

### ISSUE THREAD

**Issue by CombatTentacles** [bit-team/backintime#1019] opened 2019-07-16 18:02 UTC
For context, this is after it failed with a "cannot remove leftover 'new snapshot' folder" error that was probably related to a power outage, which I attempted to rectify by deleting said folder manually.

Back In Time
```
Version: 1.1.24

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.


(python3:26094): GLib-GIO-CRITICAL **: 18:50:33.846: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python3:26094): GLib-GIO-CRITICAL **: 18:50:33.846: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(python3:26094): GLib-GIO-CRITICAL **: 18:50:33.846: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
```

**Comment by buhtzz** [comment] 2022-09-26 08:51
@CombatTentacles There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback, Bug

**Comment by CombatTentacles** [comment] 2022-09-27 04:46
Thanks for getting in touch. I have some new information. This may have been related to an issue with my SSD, which for some reason spontaneously stopped accepting new writes for several days before equally spontaneously returning to normal. Snapshots are still failing, but I now have an actual error message: [E] Error: rsync: [sender] write error: Broken pipe (32)

I will attempt to reproduce the bug after cloning my current OS to a replacement SSD.

    On Monday, 26 September 2022 at 09:51:27 BST, buhtzz ***@***.***> wrote:  
 
 


@CombatTentacles There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback, Bug

**Comment by emtiu** [comment] 2022-09-27 10:22
Thanks for your report. When disks or filesystems fail, those errors can cause strange behavior in backintime. Let us know if the problem persists for you.

**Comment by buhtz** [comment] 2023-03-16 13:09
Closing because of no new relevant information. Please feel free to re-open the issue.

**Closed** 2023-03-16 13:08 UTC
Labels: Feedback
