### ISSUE TITLE
The user sould know if real hardlinks are not possible

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#635] opened 2016-09-17 21:46 UTC
I had that case.
I am using samba shares as backup medium. When the `unix extensions` or not activated on the samba server there is no way to make hardlinks. __But__ the system (_Linux_) doesn't give you a message about it.

`ln x y ` work well. It falls back to a simple `copy()` when the file system (the samba share) doesn't support hard links.

So BIT use `rsync` to create incremental backups. `rsync` use hardlinks for that. It doesn't take care about if there are real hardlinks or just copied files. Because of that the backup medium run out of space very soon.

**Comment by buhtz** [comment] 2016-09-18 05:39
There is still such an issue: Issue #478

**Comment by Germar** [comment] 2016-09-18 16:40
I'll mark this as duplicate of #478

**Closed by Germar** 2016-09-18 16:40 UTC
Labels: duplicate
