### ISSUE TITLE
Calculated speed unreasonable

### ISSUE THREAD

**Issue by TinkyWonky** [bit-team/backintime#897] opened 2018-06-10 19:57 UTC
My worker.progress (and the status in backintime-qt4) file claims that the backup speed is approx. 170 GB/s. I doubt it. Real harddisk transfer is approx. 40 MByte/s.
(Headless) Ubuntu Linux (backup started from remote), backintime-qt4 package version 1.1.24~trusty. Any suggestions?

**Comment by mauromol** [comment] 2018-06-21 09:02
I think this is due to the "speedup" factor computed by rsync, thanks to the delta-transfer algorithm.

**Comment by buhtzz** [comment] 2022-09-26 08:19
@TinkyWonky There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

I assume @mauromol is right.

Tag: Feedback, Support, External

**Comment by buhtz** [comment] 2023-06-29 07:44
The problem described depends on rsync itself. I see no possibility to work around that or fix it in BIT.

If no one else has a fresh idea here or additional information the issue will be closed in the near future.

**Comment by buhtz** [comment] 2023-08-01 11:09
Please feel free to re-open this issue, add new information or ask further questions.

**Closed by buhtz** 2023-08-01 11:09 UTC
Labels: Feature, Discussion, Low, Notifications
