### ISSUE TITLE
Recent rsync update from 3.2.3 to 3.2.7 breaks ssh backup to synology

### ISSUE THREAD

**Issue by edschindler** [bit-team/backintime#1417] opened 2023-03-09 16:35 UTC
rsync recently updated to version 3.2.7-0ubuntu0.22.04.2 from version 3.2.3-8ubuntu3 on my source system, and my backup began to fail after working properly daily for several years. I confirmed the source of the problem by downgrading rsync, which restored operation.

Source system: backintime 1.2.1 on Linux Mint 21.1 cinnamon 64 bit. Destination system: Synology DS215j running DSM 7.1.1-42962 Update 4. Connection using using ssh keys. Synology is running rsync version 3.1.2  protocol version 31.

An error message was logged very early in the snapshot process that a directory could not be created (...new_snapshot/backup) with no hint of rsync involvement. But...

What was wrong became clearer when I attempted to modify the configuration (backintime's settings), which resulted in the big ugly "incompatible rsync" error message, and the changes could not be saved.

I don't have the technical skills to tell whether this something backintime should accommodate,  or is something that needs to be fixed on the rsync side, but I thought I'd start here.

**Comment by buhtz** [comment] 2023-03-09 21:06
Dear @edschindler ,
thanks for reporting this.

This bug is fixed in latest upstream release of BIT. It happens with rsync 3.2.4 and later because its default behavior ("argument protection") changed and old BIT versions are not prepared for that. See #1247.

Also see this for some background information
https://github.com/bit-team/backintime#incompatibility-with-rsync-324-or-newer

Your special situation depends on Ubuntu and a security update they have done on rsync. See the bug their
https://bugs.launchpad.net/ubuntu/+source/backintime/+bug/2009756

They still prepare an Ubuntu related patch over there security channel.

Closing this as a duplicate of #1247 and not-upstream related.

Please feel free to ask further questions.

**Closed by buhtz** 2023-03-09 21:06 UTC
Labels: Distro-Specific, Reproduced, Bug, External, NAS Vendor

**Comment by edschindler** [comment] 2023-03-09 21:24
Thank you, @buhtz for such a kind and complete reply. I did not see either of the reports you provided links for, which tells me I need to look harder before raising an issue.
