### ISSUE TITLE
Spurious "Done, no backup needed" message on errors

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#84] opened 2015-10-11 16:32 UTC
System: 10.04
BiT: 0.9.99.35~karmic (from PPA)

I created a ~/tstdir and a profile "tst" to back just that up to a directory on an external harddisk (original ext4, external ext3). No scheduled backups.
When I hit "Take snapshot" for the first time, a snapshot was created, I can see the directory in the snapshot.
Now I created a file ~/tstdir/tstfile.
Hitting "Take snapshot" again yields "Done, no backup needed", and no tstfile is present in the backup. BiT does, however, show the file on the "Now" pane (propably a direct view of the filesystem).

So I removed the backintime destination directory, as well as ~/.local/share/backintime and ~/.config/backintime and started over - same behaviour.

When started from the terminal (backintime-gnome), pressing "Take snapshot" for profile "tst" (in the GUI, obviously), I get on the terminal:

INFO: The application needs to change the backup format. Start the GUI to proceed. (As long as you do not you will not be able to make new snapshots!)
WARNING: Backup not performed

---

Imported from Launchpad using lp2gh.
- date created: 2010-05-13T15:14:14Z
- owner: kamome
- the launchpad url was https://bugs.launchpad.net/bugs/580020

**Comment by Germar** [comment] 2015-10-11 18:43
(by kamome)
When started from the terminal (backintime-gnome), pressing "Take snapshot" for profile "tst" (in the GUI, obviously), I get on the terminal:

INFO: The application needs to change the backup format. Start the GUI to proceed. (As long as you do not you will not be able to make new snapshots!)
WARNING: Backup not performed

I removed the backintime destination directory, as well as ~/.local/share/backintime and ~/.config/backintime

**Comment by Germar** [comment] 2015-10-11 18:43
(by dave2010)
Try 0.9.99.37 - sounds like bug 575022

**Comment by Germar** [comment] 2015-10-11 18:43
(by kamome)
Thanks Dave, but it won't even run for me:

ii  backintime-com 0.9.99.37      Simple backup system (common)
ii  backintime-gno 0.9.99.37      Simple backup system for GNOME Desktop

$ backintime-gnome 
Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 41, in <module>
    import backintime
ImportError: No module named backintime

I used
"bzr checkout lp:backintime"
(how about adding a note for this on the project's Download-page, I had to look around the launchpad site, but even this left me guessing how to get the up2date version)
"makedeb.sh"
"dpkg -i backintime-common backintime-gnome"

How does one install this?

**Comment by Germar** [comment] 2015-10-11 18:43
(by danleweb)
You can use testing repository. You get informations here: http://backintime.le-web.org/download_page/

**Comment by Germar** [comment] 2015-10-11 18:43
(by ivar-forss)
im using Back In Time 1.0.10, backup works on one external drive but dosent anymore on the other. "Done, No backup needed"
"WARNING: Backup not performed". Files have changed.

**Comment by Germar** [comment] 2015-10-11 18:43
(by rupert-sakanastudio)
I had this problem on Ubuntu 14.04 with BackInTime 1.1.2 and upon restart SSH+Encrypt worked.
I believe it is to do with the mount file system that BackInTime holds open. At some point it fails to diff I think and hence does not run the backup. Logging off and back on again kills the mount and the "re-attach" allows diff to work.
I can't confirm this is the case but it is my "best guess".

**Comment by Germar** [comment] 2015-10-11 18:43
(by germar)
By now this 'Done, No backup needed' message is more like an educated guess which will most likely fail if there was an other problem somewhere in the chain. I'm already thinking about introducing a proper interprocess communication between GUI, running snapshot and systray icon. That should eliminate those false positive messages. But nothing done yet.

BTW there is no diff anymore ;-) It's done by 'rsync --dry-run'

**Comment by Germar** [comment] 2015-10-11 18:43
(by cassou)
I think I have the same problem. In the GUI, when clicking "Take snapshot", I get a "no backup needed". In the terminal, I get "The application needs to change the backup format. Start the GUI to proceed."

What can I do please?

**Comment by Germar** [comment] 2015-10-11 18:43
(by cassou)
Arghh, this affects all my backups. I can't backup anything anymore

**Comment by Germar** [comment] 2015-10-11 18:43
(by germar)
Did you empty the Host/User/Profile-ID lines in Settings? This will also cause 'No backup needed' (I added a test to prevent this in next version)

Run 'backintime --backup' from command-line and post the output in a new question please.

**Comment by Germar** [comment] 2015-10-11 18:43
(by cassou)
You are right. I put Host/User/Profile-ID back and my backups seem to work again. Thank you.

**Comment by buhtz** [comment] 2017-10-03 10:03
Because this is related to "introducing a proper interprocess communication between GUI, running snapshot and systray icon" this Issue could be collected into kind of a meta-Issue describing the new interprocess-thing as a more detailed wish.

**Comment by emtiu** [comment] 2022-11-04 10:34
Related Issues or possible duplicates:
* #907
* #1121

**Comment by buhtz** [comment] 2024-03-20 08:20
I vote to close because this Issue is way outdated and we also have two neighbor Issues open.

The issue is related to the topic about improving the interprocess communication in BIT but shouldn't kept open until that topic is solved.

**Comment by buhtz** [comment] 2024-06-17 07:14
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,
Christian

**Closed by buhtz** 2024-06-17 07:14 UTC
Labels: Discussion, Bug, Feedback
