### ISSUE TITLE
Quitting Backintime causes segfault

### ISSUE THREAD

**Issue by petaramesh** [bit-team/backintime#1325] opened 2022-10-07 14:31 UTC
Hi,

I have noticed that everytime I quit the Backintime interface by just “closing the Window”, it ends with a segfault and causes a coredump.

❯ backintime-qt --version
backintime-qt 1.3.2

❯ python --version
Python 3.10.7

Debug log when I close the window says :

DEBUG: [common/mount.py:680 SSH.mountProcessLockAcquire] Acquire mountprocess lock ~/.local/share/backintime/mnt/12164.lock
INFO: [common/mount.py:461 SSH.umount] unmount ssh: myself@remote-host:./ from ~/.local/share/backintime/mnt/D8B27EE3/mountpoint
DEBUG: [common/mount.py:732 SSH.mountLockRelease] Remove mount lock ~/.local/share/backintime/mnt/D8B27EE3/locks/12164.lock
DEBUG: [common/mount.py:692 SSH.mountProcessLockRelease] Release mountprocess lock ~/.local/share/backintime/mnt/12164.lock
/bin/backintime-qt : ligne 31 : 12164 Erreur de segmentation  (core dumped)python -Es ${APP_PATH}/app.py "$@"

TIA for taking a look :)

**Comment by emtiu** [comment] 2022-10-07 19:56
Thanks for the report, @petaramesh! I'm closing this as a duplicate of #1095, we're aware and hope to be able to fix this soon.

**Closed by emtiu** 2022-10-07 19:56 UTC

**Comment by aryoda** [comment] 2022-10-10 14:36
I am not sure if this really is duplicate since the linked #1095 crashes in `PyCFunction_Type`
while I cannot see the full traceback here.

@petaramesh Could you please add the traceback of the segfault here so that we can be sure it is a duplicate? THX!

**Comment by aryoda** [comment] 2022-10-10 14:38
May be related to a similar observation at Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=985256

**Comment by petaramesh** [comment] 2022-10-10 20:52
Well I had no further message than the one I gave in the bug report, and if I load the coredump with gdb and then “backtrace”, I just get : « No stack »...
