### ISSUE TITLE
[Mint, MX] New system tray icons appear with every snapshot, many icons accumulate

### ISSUE THREAD

**Issue by DonEdwards** [bit-team/backintime#1087] opened 2020-05-08 03:24 UTC
Icon appears in system tray when a backup job is running, does NOT disappear when the job is done. Stuck on "Finalizing".

As a result, I often get several such icons lined up side by side.

Backintime 1.1.12 running on Linux Mint 18.1

**Comment by dave62020** [comment] 2020-05-27 16:04
The same happens on MX Linux 19

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment] 2020-12-07 23:24
I can not reproduce this with current Debian 10 and XFCE.

Which desktop enviroments do you use?

**Comment by dave62020** [comment] 2020-12-23 15:58
This happens on MX Linux 19 XFCE and also happened on Linux Mint 18 Cinnamon

**Comment by emtiu** [comment] 2022-09-09 09:52
Thanks for the report, @dave62020. This Issue is probably a duplicate of #1002. Does the problem still happen?

**Comment by dave62020** [comment] 2022-09-09 13:52
Yes this is still happening

**Comment by emtiu** [comment] 2022-09-09 19:10
> Yes this is still happening

Thanks for your feedback! We're in the middle of sorting old tickets, and we'll hopefully get to this in due time.

**Comment by aryoda** [comment] 2022-11-20 23:10
This must be a bug in [`qtsystrayicon.py`](https://github.com/bit-team/backintime/blob/88d19d42e9128f60b8952a64ed1fff23bd28108f/qt/qtsystrayicon.py) or the "busy" indicator file:

https://github.com/bit-team/backintime/blob/88d19d42e9128f60b8952a64ed1fff23bd28108f/qt/qtsystrayicon.py#L145-L149

Could you please show me the existing files in `~/.local/share/backintime` when this error occurs?

`ls -l ~/.local/share/backintime/`

I would expect to see a `worker*.lock` file even though the backup seems to have finished.

If true I need to know more about the configuration (profile)...

**Comment by aryoda** [comment] 2024-01-09 08:54
@DonEdwards @dave62020

Could you please
- install the most recent release of BiT and check if the problem still occurs
- show me the output of `backintime --diagnostics`
- execute two BiT backup jobs
- show me the output of `journalctl -since "10 minutes ago" | grep -i backintime` (adjust the "minutes" part to catch the full the log of both backup job executions and anonymize the output by replacing sensitive strings like your user name before uploading the log here

**Comment by buhtz** [comment] 2024-02-16 07:13
Dear @DonEdwards @dave62020 ,
we would like to work on that issue.
Can you please give us some feedback and the required information aryoda was asking for.

**Comment by dave62020** [comment] 2024-02-16 15:30
Apologies for lack of reply. Since switching to MX Linux some time ago I have no longer had any issues.

**Comment by emtiu** [comment] 2024-02-16 15:44
Thanks for reporting back :) Closing the issue, as there is nobody left to reproduce. Anyone still seeing this: feel free to re-open.

**Closed by emtiu** 2024-02-16 15:44 UTC
Labels: Distro-Specific, Medium, Bug, Feedback
