### ISSUE TITLE
Issue installing via AUR package repository

### ISSUE THREAD

**Issue by jamesray1** [bit-team/backintime#947] opened 2018-11-09 11:18 UTC
https://gist.github.com/jamesray1/0d84130bb5c3f1a7f0aed10063f6ef83

[Left a comment on the AUR package](https://aur.archlinux.org/pkgbase/backintime/#news).

**Comment by coderkun** [comment] 2018-11-09 11:44
This is neither an application issue nor an issue with the AUR package. It builds fine using `makepkg`. AUR helpers are not supported neither are other distributions.

However you can also use my pre-built packages from [[coderkun-aur]](https://suruatoel.xyz/arch), if you like.

**Comment by buhtzz** [comment] 2022-09-26 08:36
@jamesray1 There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback, Distro

Close because distro maintainers responsibility

**Comment by emtiu** [comment] 2022-10-09 22:15
Closing as outdated.

**Closed by emtiu** 2022-10-09 22:15 UTC
