### ISSUE TITLE
Recommended partition type

### ISSUE THREAD

**Issue by scr255** [bit-team/backintime#1754] opened 2024-06-06 07:29 UTC
Hi, I'm using Back In Time on Ubuntu 24.04, installed using `sudo apt install backintime-qt`.

I was rendering videos on the primary (OS) NVMe SSD while performing a backup with Back In Time from an internal SATA SSD (NTFS) to an external NVMe SSD (NTFS). This was a mistake, as I should not have been multitasking during the backup process.

At a certain point, I encountered a bad block error, and the OS failed to boot. Long story short, both the primary NVMe SSD and the internal SATA SSD experienced bad blocks. I replaced both drives to be safe, and I plan to use Back In Time again.

I am interested in understanding if it's better to use Back In Time with disks using a different filesystem, such as a Linux filesystem instead of NTFS. Thanks.

**Comment by buhtz** [comment] 2024-06-06 07:57
Hello Patrick,

Thank you for taking the time to report the bug and providing the details. I appreciate your feedback.

The situation you describe sounds a bit wired. I wouldn't be so sure that the "bad blocks" are caused by BIT. I can not imagine how this can be.

But what I also wonder is how BIT allows you to take a snapshot from and to an NTFS drive. Didn't you mean NFS or really the Windows Filesystem NTFS? Do you use Ubuntu with NTFS?

I know that NTFS support hardlinks but I am not sure if the NTFS driver you use for Ubuntu is able to map that correctly. Rsync (used by BIT in the back) make heavy use of hardlinks and if this doesn't work correct.

The bad blocks might be caused by the NTFS driver for Ubuntu. They are quit fresh. You should contact your distro community to be sure about it.

If you have any more details to share, feel free to reach out.

Best regards,

**Comment by scr255** [comment] 2024-06-06 09:18
The Ubuntu OS was on an NVMe SSD with the Linux filesystem Ext4 (version 1.0).

The internal SATA SSD is a disk I used to store video files, and I didn't change its filesystem when migrating from Windows to Ubuntu, so it remained NTFS. I was able to access it on Ubuntu without issues.

Additionally, I ran a pilot backup using Back In Time from external drive A to external drive B, both being NTFS and separate from the disks mentioned earlier, without any errors or issues.

So, I'm really looking for the safest route, which I understand may be to use the Linux filesystem Ext4 on all my disks.

**Comment by buhtz** [comment] 2024-06-06 09:27
Thank you for your reply. I do get better picture now.
I don't have a concrete answer to you because I also don't know what was going on or what caused the bad blocks.

But I would recommend to use a "regular" GNU Linux file system.

Please see also the discussion at #1339 about NTFS support in Back In Time.

**Comment by buhtz** [comment] 2024-06-26 09:30
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,

**Closed as completed by buhtz** 2024-06-26 09:30 UTC
Labels: NTFS
