### ISSUE TITLE
BUG: Zombie/defunct processes

### ISSUE THREAD

**Issue by Piiit** [bit-team/backintime#765] opened 2017-05-15 07:21 UTC
During backup on a external USB-ntfs-drive I get many defunct zombie processes. The backup compares against the older snapshot, and starts to create hard links. However, the latter never stops.

Using BIT 1.1.20 on LM18.1

**Comment by colinl** [comment] 2017-05-15 07:33
Are you sure you left it long enough? Creating the links can take a long
time.

**Comment by Piiit** [comment] 2017-05-15 07:39
@colinl I left it for 8 hours. I have to turn my laptop off, when I go home. I will try to let it run over night, that would be some hours more. Is it possible to resume backup processes? Or split backups per folder?

```
/var/log/syslog:May 13 10:12:08 fuchur backintime (pemoser/1): WARNING: Command "rsync -rtDHh --links -A -X -pEgo --info=progress2 --no-i-r  --delete --delete-excluded  -i --dry-run --out-format="BACKINTIME: %i %n%L" --chmod=Du+wx  --exclude="/media/pemoser/Volume/backupbit/peter" --exclude="/home/pemoser/.local/share/backintime" --exclude=".local/share/backintime/mnt" --include="/home/pemoser/Dokumente/" --include="/home/pemoser/" --include="/home/" --include="/home/pemoser/Bilder/" --include="/home/pemoser/Schreibtisch/" --include="/home/pemoser/Dropbox/" --include="/home/pemoser/ownCloud/" --include="/home/pemoser/Musik/" --include="/home/pemoser/projects/" --include="/home/pemoser/ownCloud2/" --include="/home/pemoser/Bibliothek/" --include="/home/pemoser/public_html/" --exclude=".gvfs" --exclude=".cache*" --exclude="[Cc]ache*" --exclude=".thumbnails*" --exclude="[Tt]rash*" --exclude="*.backup*" --exclude="*~" --exclude="/home/pemoser/Ubuntu One" --exclude=".dropbox*" --exclude="/proc/*"
/var/log/syslog:May 13 10:12:08 fuchur backintime (pemoser/1): WARNING: CONTINUE: --exclude="/sys/*" --exclude="/dev/*" --exclude="/run/*" --exclude="/home/pemoser/VirtualBox VMs" --exclude="/home/pemoser/Videos" --exclude="/home/pemoser/tmp" --exclude=".git" --exclude=".designerthumb" --include="/home/pemoser/Dokumente/**" --include="/home/pemoser/Bilder/**" --include="/home/pemoser/Schreibtisch/**" --include="/home/pemoser/Dropbox/**" --include="/home/pemoser/ownCloud/**" --include="/home/pemoser/Musik/**" --include="/home/pemoser/projects/**" --include="/home/pemoser/ownCloud2/**" --include="/home/pemoser/Bibliothek/**" --include="/home/pemoser/public_html/**" --exclude="*" / "/media/pemoser/Volume/backupbit/peter/backintime/fuchur/pemoser/1/20160607-102839-999/backup/"" returns 5888
```

The rsync command returns with 5888.

**Comment by Germar** [comment] 2017-05-20 20:58
Please check if the drive is healthy. For NTFS I'd recommend using a Windows machine for this...

**Comment by Piiit** [comment] 2017-05-22 07:42
@Germar There are some unreadable files on my NTFS usb drive... (I do not have a win-machine at hand, to ntfs-check at the moment, but I think some file or the partition table is broken)

I had to delete the old backup folders, and restart the backups from scratch, it finished the backup correctly in about 10 minutes. Fortunately, I still have all original files. However, unreadable files could trigger a warning...
This would help to debug... 

Instead, currently we get an endless loop with defunct processes.

**Comment by Germano0** [comment] 2017-07-14 18:24
I am experiencing a `backintime` zombie process + `backintime-qt4` hanged process in backintime 1.1.20. Could you please tell me how to retrieve useful debuginfos? I am still having the hanged process right now

**Comment by ixnewton** [comment] 2018-06-23 10:35
I'm happy now that with 1.2.0~alpha0 we have Backintime GUI working again under pyqt5. My backups have resumed since June 2017.

When closing there is always a python3, python3 (root), backintime and backintime zombie process abandoned and not cleaned up? 

KDE 5.47.0
Qt 5.9.6

**Comment by buhtzz** [comment] 2022-09-26 08:20
@colinl There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback

**Comment by Germano0** [comment] 2022-09-26 10:49
I am no longer using backintime, therefore I cannot test any patch.
Best regards

**Closed** 2022-10-07 21:37 UTC
