### ISSUE TITLE
"Save password to keyring" option is disabled

### ISSUE THREAD

**Issue by dx486** [bit-team/backintime#545] opened 2016-02-17 16:06 UTC
"Save password to keyring" option is disabled. What can be the reason?

Cache password option is enabled but I am asked to enter the password again on every backup.

I use debian 8.3. BackinTime 1.0.36-1. Seahorse 3.14.0 is installed.

**Comment by Germar** [comment] 2016-02-17 17:34
Please make sure `python3-secretstorage` or `python3-gnomekeyring` is installed

**Comment by dx486** [comment] 2016-02-19 12:16
python-secretstorage 2.1.1-1 and python-gnomekeyring 2.32.0+dfsg-3 are installed but it is still disabled.

**Comment by Germar** [comment] 2016-02-19 17:46
Please post the output of `python -c "import keyring; print keyring.get_keyring()"`

**Comment by dx486** [comment] 2016-02-19 18:15
```
$ python -c "import keyring; print keyring.get_keyring()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named keyring
```

**Comment by dx486** [comment] 2016-02-19 18:24
I am not sure if it is related but it looks related, so I will mention about this just in case.

Now when I run backintime I get two consecutive error messages:

First:

> Can't mount 'encfs --extpass=backintime-askpass /media/xxx/mountpoint':
> 
> Gtk-Message: Failed to load module "canberra-gtk-module"
> WARNING: import keyring failed
> Error decoding volume key, password incorrect

Second:

> Can't find snapshots folder.
> If it is on a removable drive please plug it and then press OK

Then I see first message again.

Then snapshots of backup set are not loaded. 

In this profile;

- Source files are located in an external drive, encrypted with dm-crypt but unlocked. Accessible. 
- Backup location is located in the external drive, not encrypted. I checked, drive is connected and backup folder is there, accessible by file manager.

**Comment by Germar** [comment] 2016-02-19 19:23
Please install `python-keyring` and `libcanberra-gtk-module`. Than run `backintime --pw-cache stop` and try again.

**Comment by dx486** [comment] 2016-02-19 19:44
Problem solved! Thank you very much. :)

**Comment by simgunz** [comment] 2016-02-25 09:50
I have the same problem on Manjaro linux KDE.

I've installed python2-secretstorage and python-secretstorage (python3)

The following command run fine:

    python -c "import keyring; print keyring.get_keyring()"

With this I have an error:

    python2 -c "import keyring; print keyring.get_keyring()"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named keyring

1) Is backinitme using python2 or python3?
2) Does python-secretstorage replace python-keyring? Or we need both?

How is libcanberra-gtk-module related to the keyring? Is it needed in KDE?

**Comment by dx486** [comment] 2016-02-25 16:44
Well, I keep getting the error messages mentioned by me [above](https://github.com/bit-team/backintime/issues/545#issuecomment-186348421) from time to time. `backintime --pw-cache stop` command solves this error after a BIT restart, however this workaround is not a solution, because despite I have set my  backup schedule as "every 6 hour", I don't see backups from last 2 days.

I got those errors 15 minutes ago and I used that command again, then I changed my backup schedule as "every 5 minutes", then I closed BIT. Now I check and see that BIT took backup according to new schedule.

My conclusion: BIT does not apply schedule when this problem (about pw-cache) occurs in background.

**Comment by Germar** [comment] 2016-02-25 21:21
@simgunz:

1. BIT version < 1.1.0 uses Python2. BIT version >= 1.1.0 uses Python3
2. `python-secretstorage` is a backend for `python-keyring`. It supports both Gnome-Keyring (aka Seahorse) and KDE Kwallet. You need both `python-secretstorage` and `python-keyring` in your case for Python3
3. `libcanberra-gtk-module` is an dependency of backintime-gnome in BIT < 1.1.0. You don't need it.
4. If it's not grayed out it should work. Please run `backintime-qt4 --debug` from command line and watch out for 'Warning: import keyring failed', `Debug: No keyring due to import errror`, `Debug: Found appropriate keyring` or `Debug: No appropriate keyring found` messages

@dx486 the schedule `every 6 hour` starts BIT on 0:00, 6:00, 12:00 and 18:00. If your machine wasn't turned on at that time it will never run. You could use schedule `Repeatedly (anacron)` with 6h frequency to start BIT every 6 hours when your machine is turned on.

**Comment by simgunz** [comment] 2016-02-26 08:52
If I run `backintime-qt4 --debug` I get the following:

`DEBUG: [common/tools.py:611 keyring_supported] Found appropriate keyring 'keyring.backends.kwallet'
DEBUG: [common/sshtools.py:192 SSH.unlock_ssh_agent] Add private key /home/simone/.ssh/backup_id_rsa to ssh agent
DEBUG: [common/sshtools.py:197 SSH.unlock_ssh_agent] Password available: True`

and right afterwards a dialog appears asking me the password for SSH (every time).

The backend seems to be present, still the checkbox is not clickable. Also if I position the cursor on the field "SSH private key" and I hit tab the next field focused is "Cache Password for Cron...".

It seems that the field "Save password to keyring" is somehow disabled or ignored.

**Comment by Germar** [comment] 2016-02-26 21:10
@simgunz could you please manually remove the password from Kwallet, stop pw-cache with `backintime pw-cache stop` and try again to add it in Settings? I guess the password in Kwallet is wrong.

**Comment by simgunz** [comment] 2016-02-27 08:41
I can't even find it in KWallet. Under which name/category should the password be stored?

**Comment by simgunz** [comment] 2016-02-27 09:04
I've also tried to create a new SSH profile, and also in that case the checkbox cannot be checked.

**Comment by Germar** [comment] 2016-02-28 00:14
@simgunz I'll make myself a Manjaro VM and test it. Sounds like a bigger problem.

**Comment by simgunz** [comment] 2016-02-28 14:49
Thanks to look into this.

**Comment by hefeweiz3n** [comment] 2016-02-28 15:46
Hi. Just wanted to add that the Problem appears in plain archlinux as well (Using latest KF5/Plasma5). My SSH Key is in the ssh-agent, connecting to the server from the terminal works like expected, no password for the key needed. Starting backintime-qt4 --debug in the same terminal gives me the above output (with password available: true).

**Comment by dx486** [comment] 2016-02-29 09:22
Just a note: I don't have any problem since I've upgraded BIT to v1.1.12 (on debian 8.3 stable).

**Comment by simgunz** [comment] 2016-02-29 09:46
I'm actually running v1.1.12

**Comment by Germar** [comment] 2016-03-01 01:22
Okay, there was a logic error with the `Found appropriate keyring ...` debug message. But the real problem is `python-keyring` and `KWallet` both changed and `python-keyring` has a bug with connecting to `KWallet`. I filled a [bug report](https://bugs.archlinux.org/task/48380) on Arch for `python-keyring`.

**Comment by simgunz** [comment] 2016-03-01 08:21
I'm glad you've already found the problem! Thanks

**Comment by hefeweiz3n** [comment] 2016-03-02 09:48
I can confirm that the patch works. I also mentioned it in the according bug in the python-keyring bugtracker: jaraco/keyring#168

**Comment by simgunz** [comment] 2016-03-25 16:03
The problem seems to be solved now, using python-keyring 8.5.1

**Comment by Germar** [comment] 2016-03-25 19:38
Thanks for the feedback. I'll close this bug as it was no bug in BIT.

**Closed by Germar** 2016-03-25 19:38 UTC
Labels: keyring, question

**Comment by simgunz** [comment] 2016-06-23 07:46
I need to ask your support again on this issue, because it's happening again.

The debug output I'm getting is the same as above, and the checkbox is disabled so that I cannot save the SSH password.

I'm using backintime 1.1.12 and python-keyring 9.0

`DEBUG: [common/tools.py:611 keyring_supported] Found appropriate keyring 'keyring.backends.kwallet'
DEBUG: [common/mount.py:50 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:59 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
DEBUG: [common/sshtools.py:192 SSH.unlock_ssh_agent] Add private key /home/simone/.ssh/backup_id_rsa to ssh agent
DEBUG: [common/sshtools.py:197 SSH.unlock_ssh_agent] Password available: True
ERROR: [common/sshtools.py:229 SSH.unlock_ssh_agent] Failed to unlock SSH private key /home/simone/.ssh/backup_id_rsa: 
DEBUG: [common/sshtools.py:239 SSH.unlock_ssh_agent] Was not able to unlock private key /home/simone/.ssh/backup_id_rsa`

**Comment by Germar** [comment] 2016-06-23 21:42
I [backported the patch](https://gist.github.com/Germar/13df87acef68a9e51d47c36675b7ed4c) for 1.1.12 and asked the package maintainer for the AUR package to include it. Should be fixed soon...

**Comment by graysky2** [comment] 2016-06-24 06:25
> I backported the patch for 1.1.12 and asked the package maintainer for the AUR package to include it. Should be fixed soon...

Updated in backintime 1.1.12-4

**Comment by simgunz** [comment] 2016-06-24 07:56
Ok. Sorry, I reported it again because I remember it was already fixed on my system, so I thought it broke again. While the patch was not yet there, so maybe I remember wrong.

In any case I've tested the AUR package today, and it works correctly.

Thanks again

**Comment by Germar** [comment] 2016-06-24 11:08
No worries, mate

**Comment by Azimoth** [comment] 2019-04-29 12:32
I'm having this issue using version 1.2.0~alpha0 on Gentoo. 
The thing is: It WAS working until I installed something else that required PyQt5. 

Then backintime stopped working properly by complaining about being unable to access the password, so I removed it manually from kwallet, expecting to be asked for it again.
Then the GUI didn't come up anymore, which I could fix by installing xdpyinfo.

Now Backintime is working again, but the "Save password to keyring" option is disabled.

I also tried re-installing Backintime (also removing ~/.config/backintime and ~/.local/share/backintime), but it still doesn't work.

> backintime --debug
doesn't show anything that seems to be out of the ordinary...

```
$ python -c "import keyring; print(keyring.get_keyring())"
keyring.backends.chainer.ChainerBackend (priority: 10)
```
```
$ backintime --pw-cache stop
INFO: Run command 'pw-cache' instead of argument '--pw-cache' due to backwards compatibility.

Back In Time
Version: 1.2.0~alpha0

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

WARNING: Failed to read PID and process name from /home/til/.local/share/backintime/password_cache/PID: [2] No such file or directory
ERROR: pidfile /home/user/.local/share/backintime/password_cache/PID does not exist. Daemon not running?
```
