### ISSUE TITLE
[enhancement] Option to check read permissions before taking snapshot

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#249] opened 2015-10-11 16:41 UTC
Whenever a backup fails, it is usually due to missing read permissions.
In my opinion, it would be helpful, especially for new users, to include (and activate by default) an option "check permissions before taking snapshot". It could display a warning if a missing permission is detected before a snapshot is taken and ask the user if he wants to continue anyway.

On the commandline, it should be possible to find non-readable files with something like

find <directory> ! -readable ! -type l ! -path <excludedirectory1/*> ! -path <excludedirectory2/*> ...

(The part "! -type l" is there because otherwise broken symbolic links would appear as non-readable.)

It would be nice to have something like that in BIT.

---

Imported from Launchpad using lp2gh.
- date created: 2014-03-13T10:08:55Z
- owner: rainerzufall
- the launchpad url was https://bugs.launchpad.net/bugs/1291897

**Comment by Germar** [comment] 2015-10-11 20:17
(by germar)
May be this could be combined with bug #1291710. Not sure about it yet. I've something in mind to ask if user wants to run a dry-run first time after set up a new profile (and optionally provide a dry-run button, too). Then we can scan rsync output for read errors.

**Comment by emtiu** [comment] 2022-09-24 21:34
Closing as duplicate of #248.

**Closed by emtiu** 2022-09-24 21:34 UTC
Labels: wishlist
