### ISSUE TITLE
Schedule odd/even days?

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#880] opened 2018-03-19 13:27 UTC
Hi, thanks for BiT.

I have two tiny-USB drives and I like to backup up to each one on odd/even days. The odd-day USB is in a dock that stays at home, the even-day USB stays in the laptop. Call me paranoid but I have been playing with computers for 30+ years and have well-learned backup philosophy. :)

Currently I have two profiles and just manually choose which one based on the day number, odd or even. Is there some way to auto-schedule that? I checked the schedule options and could not think of any way to use the set options.

Thanks

**Comment by FlailAway** [comment] 2018-04-04 17:33
That's a tough one to answer with Linux. Probably the best thing is to run a search (gnome-search-tool) on Last Modified Dates based from root.

From that you will get an idea of what is being changed daily and see what might be a good idea to backup.

However, to my thinking, my Home folder is probably the only real thing that I need to backup as a system reinstall back to your current level will have to be done via the "sudo apt-get install" process. 

So, as long as I (you) have the home folder backed up AND the new (after crash etc) installation uses the same user name then the folders like .config should still pretty much apply after the new installation is back to where I was.

**Comment by Germar** [comment] 2018-04-11 21:01
You'd need to deactivate the schedules and add your own schedules manually in crontab without removing the lines which BiT left in there

**Comment by FlailAway** [comment] 2018-04-12 15:32
Thanks, but I should have explained that better. I mainly mean this for using Arduino and dated Sketches. I have the backup Folder in BiT as "arduinoIDE" and in that I will have multiple iterations of the "xxxxx.ino" files.
GPS Folder:
  basic-2018-02-21a.ino <-- these "a", "b" etc, are often about hourly
  basic-2018-02-21b.ino
 ...
  basic-2018-04-10a.ino

On my working laptop I delete the "xxxxx.ino" files older than about three days. I am not so much concerned about freeing space, but if I have to restore, I get all the old stuff and I do not want to have to go through hundreds of selections to weed out the old stuff before the restore.

But, I think I have the answer that it is OK to manually delete the files from the Backup drives. I wasn't sure if that would mess up Incremental-backup management or something.

p.s.
I use the GUI version as the Command Line is a little out of my league.

**Comment by emtiu** [comment] 2022-09-12 14:54
Closing as a duplicate of #881.

**Closed by emtiu** 2022-09-12 14:54 UTC
Labels: question
