### ISSUE TITLE
backintime-qt fails to start

### ISSUE THREAD

**Issue by 00rob00** [bit-team/backintime#1245] opened 2022-04-09 16:21 UTC
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 35, in <module>
    import qttools
  File "/usr/share/backintime/qt/qttools.py", line 47, in <module>
    import snapshots
  File "/usr/share/backintime/common/snapshots.py", line 34, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 32, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 1802, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet

It stopped working 1st April 2022.  There was an update to python3 that day on my distribution, Devuan, python3 (3.9.8-1) to 3.10.4-1 if that is relevant

Thanks
rob

**Comment by candardo** [comment] 2022-04-09 17:21
It's a know bug related to python 3.10 and fixed in the newest version. Read the first comment on https://github.com/bit-team/backintime/issues/1232

**Comment by 00rob00** [comment] 2022-04-10 00:06
Thanks

**Comment by candardo** [comment] 2022-04-29 08:01
Bit 1.3.2 landed in debiaa so I guess it will be fixed in Ubuntu too soon.

**Comment by cfc-librarian** [comment] 2022-04-29 10:23
BIT 1.3.2 is only on (unstable) Debian Sid.  The current Debian 11 Bullseye is on 1.2.1.3 and the older Debian 10 Buster is on 1.1.24.0-1.  Not sure how long it takes or what the process is for it to move from unstable to stable Debian.

**Comment by gsker** [comment] 2022-04-29 15:44
@joolz I'm waiting for it to hit my repos too, but for now the "fix"  for me was one line. 
So if you are not backing up because of it you should just make the change manually.  
https://github.com/bit-team/backintime/pull/1174/files
In `common/tools.py`  change line 1805 (or thereabouts) from
`class OrderedSet(collections.MutableSet):`  
to 
`class OrderedSet(collections.abc.MutableSet):`

I'm just responding to you saying you are not backing up -- but if your only point was that it needs to hit the repos, then I apologize for any offense.

**Comment by joolz** [comment] 2022-04-29 17:00
@gsker this works for me too, thank you very much! Of course this needs to end up in the repos but for now at least I can backup again.

Makes me wonder... When a new release comes out (Ubuntu in this case), ideally there would be some automated build process that does at least a quick smoke test to see if all the applications in the repos will run. Then again if I think of how much software is in the repos, with all their interrelated dependencies, that would be quite a task. Probably not feasable.

**Comment by gsker** [comment] 2022-06-13 16:18
Duplicate of #1259

**Comment by emtiu** [comment] 2022-06-13 18:10
> @gsker Thanks for your reply on #1259. I hadn't realized `backintime` has its own repo now. I'll add it and update to the latest version. Hopefully that fixes things.

Ideally, this shouldn't be necessary, but at the moment, it's the best available fix. We're working to get the project back on track, and hopefully have a working version included with distributions in the near future. Thanks for your patience :)

**Comment by AlexSchr** [comment] 2022-07-02 17:59
As far as I understand
https://bugs.launchpad.net/ubuntu/+source/backintime/+bug/1976164
the packages in Ubuntu 22.04 LTS have been updated, so that back in time now starts successfully. Can anybody confirm that?

**Comment by joolz** [comment] 2022-07-02 18:59
Works for me on 22.04, thanks!

**Comment by jdrch** [comment] 2022-07-02 19:08
> As far as I understand https://bugs.launchpad.net/ubuntu/+source/backintime/+bug/1976164 the packages in Ubuntu 22.04 LTS have been updated, so that back in time now starts successfully. Can anybody confirm that?

I haven't seen the `cron` error that prompted me to come here in the 1st place since I applied the repo addition fix, so I assume all is well on this end too. Thanks!

**Comment by emtiu** [comment] 2022-07-06 08:16
Cool! It would be best to have the current release 1.3.2 in Ubuntu, but having this patch committed is also good. Closing the issue.

**Closed by emtiu** 2022-07-06 08:16 UTC
