### ISSUE TITLE
Display unshared size

### ISSUE THREAD

**Issue by jondo** [bit-team/backintime#1221] opened 2022-01-28 10:10 UTC
In the snapshots list, I would like to see a column displaying the 'unshared' size, i.e. the amount of snapshot data that is not shared with any other shapshot.
Is this feasible?
In case computing this takes too long, it could also only be available after manually triggering the computation via menu item.

I know this 'Unshared' column from Timeshift's btrfs filesystem snapshots:
![image](https://user-images.githubusercontent.com/21648/151528152-135c2123-b69f-4a2e-97d9-c5b71c03091d.png)

I am currently using Back In Time 1.2.1.

**Comment by emtiu** [comment] 2022-09-07 22:22
Thank you for this feature request, @jondo! I'm closing this Issue as a duplicate of #406, which is high on my personal wishlist :)

**Closed by emtiu** 2022-09-07 22:22 UTC
