### ISSUE TITLE
Can remote backups be pulled instead of pushed?

### ISSUE THREAD

**Issue by jwbrase** [bit-team/backintime#998] opened 2019-05-16 03:48 UTC
The fact that there is a "host" field under Setting > General > Advanced almost seems to suggest that backintime can pull backups from a remote system, but pretty much everything I can find in the documentation only covers pushing backups to a remote system. Is it possible to pull backups?

**Comment by glyndon** [comment] 2019-05-16 03:58
I have a cron job run a script to do that every week to a system that's in the DMZ (outside the firewall).
The script:
- ssh's to the target machine, including a port-forwarding command to allow the remote machine to reach rsync on the calling host.
- invokes the command-line version of backintime on the target, which is config'd to find rsync on a local port (the one that now forwards back to the caller).
- backup runs, BiT ends, the script then exits and logs the caller out, which closes the forwarded port.

**Comment by Germar** [comment] 2019-08-11 19:10
duplicate of #213

**Closed by Germar** 2019-08-11 19:10 UTC
