### ISSUE TITLE
View progress of snapshot in terminal ?

### ISSUE THREAD

**Issue by JPnux** [bit-team/backintime#1108] opened 2020-08-15 10:11 UTC
Hello,

Is it possible to view progress of the snapshot when executing "backintime backup" in a terminal ?

Actually, I don't have the progress.

I just see this :
-------------------------

Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Take a new snapshot. Profile: 1 Profil principal
INFO: Call rsync to take the snapshot
INFO: Save config file
INFO: Save permissions
INFO: Create info file
INFO: Unlock
-------------------------

Thank you

**Comment by daveTheOldCoder** [comment] 2020-10-12 16:53
This might provide more details:
`backintime --debug backup`

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment] 2020-12-07 23:16
Issue can be closed.

**Comment by emtiu** [comment] 2022-09-09 19:46
Closing as duplicate of #1131.

**Closed by emtiu** 2022-09-09 19:46 UTC
