### ISSUE TITLE
Backintime fails to open after installing PyQt5

### ISSUE THREAD

**Issue by adamfries92** [bit-team/backintime#758] opened 2017-05-10 12:36 UTC
Mostly free install of Ubuntu Gnome 16.04 (just ran a script that downloads a few programs and setups up a few directories/symlinks). Once everything was setup the way I wanted and backintime working fine, wanted to get PyQt5 up and running for dev work. 

Installed PyQt5 from the command line (believe I used sudo apt-get install python3-pyqt5*). Now, backintime wont open, and gets a sementation fault if I try to run it from the command line. 

I have another computer (Running Ubuntu 16.04) that I went through the same process of installing PyQt5. Backintime works fine on that computer.

Any help would be appreciated!

**Comment by Germar** [comment] 2017-05-10 21:00
Which BiT version did you install? Current stable 1.1.20 from official repository still uses Qt4. Only 1.2.0~alpha from ppa:bit-team/testing uses python3-pyqt5.
Please run `backintime-qt4 --debug` from Terminal and post the output (or if you're using BiT 1.2.0 the command is `backintime-qt --debug`)

**Comment by jdm12989** [comment] 2017-05-12 18:03
I am running Linux Mint 18.1 and I recall having something similar, but don't quire recall how I fixed it now.
I believe I had to also install the package "python3-dbus.mainloop.pyqt5".
This is with 1.2.0~alpha.

**Comment by adamfries92** [comment] 2017-05-12 22:58
Sorry for the delayed response. 

I am running version 1.1.12 from the 16.04 official repo.

Running the debug I get a segmentation fault.

**Comment by Germar** [comment] 2017-05-20 20:29
Maybe related to #713? Please remove both `python3-pykde4` and `python3-pyqt4`

**Comment by Germar** [comment] 2017-05-20 20:31
Oh, just saw you are still on 1.1.12. So please remove python3-pyqt5 or upgrade to BiT 1.2.0 from testing PPA

**Comment by adamfries92** [comment] 2017-05-22 15:27
I updated to BiT 1.2.0 from the PPA. Running it from the command line, I get below:
adam@ubuntu-desktop:~$ backintime --version 
backintime 1.2.0~alpha16
adam@ubuntu-desktop:~$ sudo -i backintime

Back In Time
Version: 1.2.0~alpha16

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1164, in <module>
    startApp()
  File "/usr/share/backintime/common/backintime.py", line 520, in startApp
    return getConfig(args, False)
  File "/usr/share/backintime/common/backintime.py", line 668, in getConfig
    cfg = config.Config(config_path = args.config, data_path = args.share_path)
  File "/usr/share/backintime/common/config.py", line 280, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1696, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1

**Comment by jdm12989** [comment] 2017-05-22 20:18
What is the output of 'systemctl status dbus.service'?

**Comment by adamfries92** [comment] 2017-05-26 02:08
adam@ubuntu-desktop:~$ systemctl status dbus.service 
● dbus.service - D-Bus System Message Bus
   Loaded: loaded (/lib/systemd/system/dbus.service; static; vendor preset: enabled)
   Active: active (running) since Thu 2017-05-25 19:53:49 EDT; 2h 14min ago
     Docs: man:dbus-daemon(1)
 Main PID: 851 (dbus-daemon)
   CGroup: /system.slice/dbus.service
           ├─ 851 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
           └─1918 /usr/lib/x86_64-linux-gnu/fwupd/fwupd

May 25 19:55:14 ubuntu-desktop AptDaemon.Worker[1831]: INFO: Finished transaction /org/debian/apt/transaction/af53d869e8f34964b06d09e38aeef1a0
May 25 19:55:14 ubuntu-desktop org.freedesktop.PackageKit[851]: 19:55:14 AptDaemon.Worker [INFO]: Finished transaction /org/debian/apt/transaction/af53d869e8f34964b06d09e38aeef1a0
May 25 20:06:06 ubuntu-desktop AptDaemon[1831]: INFO: Quitting due to inactivity
May 25 20:06:06 ubuntu-desktop AptDaemon[1831]: INFO: Quitting was requested
May 25 20:06:06 ubuntu-desktop org.freedesktop.PackageKit[851]: 20:06:06 AptDaemon [INFO]: Quitting due to inactivity
May 25 20:06:06 ubuntu-desktop org.freedesktop.PackageKit[851]: 20:06:06 AptDaemon [INFO]: Quitting was requested
May 25 22:06:49 ubuntu-desktop dbus[851]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service'
May 25 22:06:50 ubuntu-desktop dbus[851]: [system] Successfully activated service 'org.freedesktop.hostname1'
May 25 22:07:04 ubuntu-desktop dbus[851]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service'
May 25 22:07:29 ubuntu-desktop dbus[851]: [system] Failed to activate service 'org.bluez': timed out

**Comment by diogo-gomes** [comment] 2017-09-03 02:27
I have same issue and after try`sudo -H pip3 uninstall sip` I get `Cannot uninstall requirement sip, not installed`.

I think it's not related with **sip**.

**Comment by iainrs** [comment] 2017-10-03 22:51
I haven't been able to run backintime for some weeks. If I run 
backintime-qt4    (with or without --debug) 
I get "segmentation fault"
I have removed all pyrthon3-ptqt5 packages but still get the same result.
I'm afraid I am not well up on the technicalities so I do not have much idea on further action.
Is there any further information I can provide ?

I reported the problem on the Mint xfce forum
https://forums.linuxmint.com/viewtopic.php?f=57&t=253316&p=1363579&hilit=backintime#p1363579
and didn't get very far.

I've got about a Gb of backups (which I can just about access) but haven't done a Bit backup for some months


System:    Host: Dylan-II Kernel: 4.4.0-34-generic x86_64 (64 bit)
           Desktop: Xfce 4.12.3 Distro: Linux Mint 18.2 Sonya
Machine:   Mobo: ASUSTeK model: P7P55D LE v: Rev 1.xx
           Bios: American Megatrends v: 2003 date: 12/16/2010
CPU:       Quad core Intel Core i5 750 (-MCP-) cache: 8192 KB
           clock speeds: max: 2668 MHz 1: 1333 MHz 2: 1200 MHz 3: 1467 MHz
           4: 1333 MHz
Graphics:  Card: NVIDIA G94 [GeForce 9600 GT]
           Display Server: X.Org 1.18.3 drivers: nouveau (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz, 1680x1050@59.95hz
           GLX Renderer: Gallium 0.4 on NV94 GLX Version: 3.0 Mesa 11.2.0

**Comment by malypetu** [comment] 2018-02-16 02:59
Guys,
I have a similar issue, after installing PyQt5 all went up in smoke, BackinTime (BIT) stop working all together and refuses to start throwing the following error:
backintime traceback
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 27, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 32, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 51, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'

I've tried to install all the libraries suggested to no avail.  I am at lost as to what to do. This doesn't seem to be a particular issue, I've seen it in a few places with no solutions or not a clear specific solution for BIT.
I'm appealing to anybody clue enough to tell us, step by step how to check (please provide commands if possible) and then what are the corrective steps (again include commands).

Regards

**Comment by malypetu** [comment] 2018-02-16 03:03
Just to add a bit of information, I've run as suggested by Germar:
 
sudo python3 /usr/share/backintime/qt/serviceHelper.py
sudo python3 /usr/share/backintime/qt/serviceHelper.py
Segmentation fault (core dumped)

Hope this helps a bit to isolate the issue.

Cheers

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment] 2020-12-08 11:42
Because the Issue is quit old: Can anyone reproduce the problem with the current version of bit and operating system?

**Comment by aryoda** [comment] 2022-08-24 16:26
May be related to #871.

Try to install the mentioned packages (where pyqt5 is already installed causing the problem ;-)

`pip install dbus-python and pip install pyqt5`

**Comment by emtiu** [comment] 2022-10-08 21:57
Closing as duplicate of #921.

**Closed by emtiu** 2022-10-08 21:57 UTC
Labels: Distro-Specific, Bug, Python-Specific
