### ISSUE TITLE
No icons as root ("no supported theme installed")

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1524] opened 2023-09-07 15:00 UTC
I never used BIT as root. I'm not sure if this is an Issue or I made something wrong.
I wonder if this is an old known issue or if I broke something when refactoring parts of the mainwindow.

There are no icons when I run bit as root.

![bit_root_ohne_icons](https://github.com/bit-team/backintime/assets/11861496/a3922e74-825e-429f-82b5-4830b12235ac)

The debug output tells me to "consult the project website". 😃 
But I can't find a hint about the error "no supported theme installed". I checked known errors in README and FAQ.

## Diagnostic output

It is Debian 11 on a RaspberryPi 4 with an nearly unmodified/unconfigured Xfce running on an RDP server.

```
 /usr/bin/backintime-qt_polkit --diagnostics
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
{
    "backintime": {
        "name": "Back In Time",
        "version": "1.3.4-dev",
        "latest-config-version": 6,
        "local-config-file": "/root/.config/backintime/config",
        "local-config-file-found": true,
        "global-config-file": "/etc/backintime/config",
        "global-config-file-found": false,
        "started-from": "/usr/share/backintime/common",
        "running-as-root": true,
        "user-callback": "/root/.config/backintime/user-callback",
        "keyring-supported": false
    },
    "host-setup": {
        "platform": "Linux-5.10.0-25-arm64-aarch64-with-glibc2.31",
        "system": "Linux #1 SMP Debian 5.10.191-1 (2023-08-16)",
        "OS": {
            "/etc/os-release": "Debian GNU/Linux 11 (bullseye)",
            "/etc/xf-release": "Foo\nBar\n",
            "/etc/release": "Very\nGood\n",
            "/etc/debian_version": "11.7\n"
        },
        "display-system": "($XDG_SESSION_TYPE not set)",
        "locale": "de_DE, UTF-8",
        "PATH": "/usr/sbin:/usr/bin:/sbin:/bin:/root/bin",
        "RSYNC_OLD_ARGS": "(not set)",
        "RSYNC_PROTECT_ARGS": "(not set)"
    },
    "python-setup": {
        "python": "3.9.2 default Feb 28 2021 17:03:44 CPython GCC 10.2.1 20210110",
        "python-executable": "/usr/bin/python3",
        "python-executable-symlink": true,
        "python-executable-resolved": "/usr/bin/python3.9",
        "sys.path": [
            "/usr/share/backintime/qt/plugins",
            "/usr/share/backintime/common/plugins",
            "/usr/share/backintime/plugins",
            "/usr/share/backintime/common",
            "/usr/share/backintime/qt",
            "/usr/lib/python39.zip",
            "/usr/lib/python3.9",
            "/usr/lib/python3.9/lib-dynload",
            "/usr/local/lib/python3.9/dist-packages",
            "/usr/lib/python3/dist-packages",
            "/usr/lib/python3.9/dist-packages"
        ],
        "qt": {
            "Version": "PyQt 5.15.2 / Qt 5.15.2",
            "Theme": "hicolor",
            "Theme Search Paths": [
                "/usr/local/share/icons",
                "/usr/share/icons",
                ":/icons"
            ],
            "Fallback Theme": "hicolor",
            "Fallback Search Paths": [
                "/usr/share/pixmaps"
            ]
        }
    },
    "external-programs": {
        "rsync": "3.2.3",
        "ssh": "OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022",
        "sshfs": "3.7.1",
        "encfs": "1.9.5",
        "shell": "/bin/bash",
        "shell-version": "GNU bash, version 5.1.4(1)-release (aarch64-unknown-linux-gnu)"
    }
}
```

## Debug output
```
/usr/bin/backintime-qt_polkit --debug
DEBUG: [common/backintime.py:589 argParse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.3.4-dev

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/configfile.py:591 Config.setCurrentProfile] Change current profile: 1=Hauptprofil
DEBUG: [common/tools.py:172 initiate_translation] Language code "en".
DEBUG: [common/backintime.py:677 getConfig] config file: /root/.config/backintime/config
DEBUG: [common/backintime.py:678 getConfig] share path: /root/.local/share/backintime
DEBUG: [common/backintime.py:679 getConfig] profiles: 1=Main profile
DEBUG: [common/pluginmanager.py:245 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/tools.py:719 is_Qt5_working] Qt5 probing result: exit code 2
DEBUG: [plugins/systrayiconplugin.py:76 init] System tray is available to show the BiT system tray icon
DEBUG: [common/pluginmanager.py:262 PluginManager.load] Add plugin systrayiconplugin.py
DEBUG: [common/pluginmanager.py:262 PluginManager.load] Add plugin notifyplugin.py
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
DEBUG: [qt/qttools.py:229 createQApplication] QT QPA platform plugin: xcb
DEBUG: [qt/qttools.py:230 createQApplication] QT_QPA_PLATFORMTHEME=<not set>
DEBUG: [qt/qttools.py:235 createQApplication] QT_STYLE_OVERRIDE=<not set>
DEBUG: [qt/qttools.py:238 createQApplication] QT active style: fusion
DEBUG: [qt/qttools.py:239 createQApplication] QT fallback style: hicolor
DEBUG: [qt/qttools.py:240 createQApplication] QT supported styles: ['Windows', 'Fusion']
DEBUG: [qt/qttools.py:241 createQApplication] themeSearchPaths: ['/usr/local/share/icons', '/usr/share/icons', ':/icons']
DEBUG: [qt/qttools.py:242 createQApplication] fallbackSearchPaths: ['/usr/share/pixmaps']
DEBUG: [qt/qttools.py:247 createQApplication] Is SystemTray available: True
DEBUG: [qt/qttools.py:260 createQApplication] Trying to set App ID for root user
DEBUG: [qt/qttools.py:302 initiate_translator] Language code "en".
DEBUG: [qt/icon.py:20 <module>] Checking if the current theme contains the BiT icon...
DEBUG: [qt/icon.py:36 <module>] Probing theme: ubuntu-mono-dark (activated as ubuntu-mono-dark)
DEBUG: [qt/icon.py:36 <module>] Probing theme: gnome (activated as gnome)
DEBUG: [qt/icon.py:36 <module>] Probing theme: breeze (activated as breeze)
DEBUG: [qt/icon.py:36 <module>] Probing theme: breeze dark (activated as breeze dark)
DEBUG: [qt/icon.py:36 <module>] Probing theme: hicolor (activated as hicolor)
DEBUG: [qt/icon.py:36 <module>] Probing theme: adwaita (activated as adwaita)
DEBUG: [qt/icon.py:36 <module>] Probing theme: adwaita-dark (activated as adwaita-dark)
DEBUG: [qt/icon.py:36 <module>] Probing theme: yaru (activated as yaru)
DEBUG: [qt/icon.py:36 <module>] Probing theme: oxygen (activated as oxygen)
ERROR: [qt/icon.py:39 <module>] No supported theme installed (missing icons). Please consult the project web site for instructions how to fix this.
DEBUG: [common/tools.py:1103 keyringSupported] No keyring due to import error.
DEBUG: [common/mount.py:161 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:169 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
DEBUG: [common/tools.py:1674 readCrontab] Read 2 lines from user crontab
DEBUG: [common/config.py:1618 Config.removeOldCrontab] Clearing system Back In Time entries
DEBUG: [common/config.py:1653 Config.cronLine] Profile: Main profile | Automatic backup: 27
DEBUG: [common/config.py:1575 Config.setupCron] Udev rules added successfully
DEBUG: [common/config.py:1601 setupCron] Crontab didn't change. Skip writing.
DEBUG: [common/tools.py:1103 keyringSupported] No keyring due to import error.
DEBUG: [common/mount.py:161 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:169 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
```

**Comment by aryoda** [comment] 2023-09-07 18:39
On my machine with my dev version it does work.

- Do you see icons if running BiT as user
- Is it the most-recent dev branch version?

>             "Theme": "hicolor",
>             "Theme Search Paths": [
>                 "/usr/local/share/icons",
>                 "/usr/share/icons",

Could you please provide the installed theme names that contain the BiT app icon (`find . -name "document-save.*"`) for these folders:

- /usr/local/share/icons
- /usr/share/icons

**Comment by aryoda** [comment] 2023-09-07 18:47
> The debug output tells me to "consult the project website". 😃

Yes, I was deliberately unspecific since links may change and this could also mean to "check the issues".

Currently this is the most-specific link to a readme.md entry:

https://github.com/bit-team/backintime#tray-icon-or-other-icons-not-shown-correctly

**Comment by aryoda** [comment] 2023-09-07 18:48
Could you please also show me the active style (part of the "theme") and which styles are really supported on your computer:

```
# Show active and supported styles in Qt5
pkexec env DISPLAY=$DISPLAY XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR XAUTHORITY=$XAUTHORITY python3 -c "from PyQt5.QtGui import QIcon; from PyQt5.QtWidgets import QSystemTrayIcon,QApplication,QStyleFactory; app = QApplication(['']); print(f'QT style: {app.style().objectName()}'); print(f'QT supported styles: {QStyleFactory.keys()}')"
# On my Ubuntu 20.04 with Gnome3:
# QT style: fusion
# QT supported styles: ['Breeze', 'cleanlooks', 'gtk2', 'cde', 'motif', 'plastique', 'qt5ct-style', 'Windows', 'Fusion']

```
The thing is: Themes must be installed via a (distro) package to have all files available. Qt5 does check this and ignores non-available styles (part of a"theme").

You can enforce a different supported style with this command (to test if all icons are visible in BiT then):

```
# use a style name from QT supported styles (the name is case-insensitive)
pkexec env QT_STYLE_OVERRIDE=oxygen backintime-qt_polkit --debug
```

**Comment by buhtz** [comment] 2023-09-07 19:01
OK, I'll check all the details tomorrow when I have access to that machine again.

About the location of the missing-tray-icon-docu: It seems OK to me how it is. I'm just a good example of a very lazy user when it comes to looking for something specific in the docu. :laughing: My fault.

**Comment by aryoda** [comment] 2023-09-08 08:03
I think I should white-list the known supported themes in the README

**Comment by buhtz** [comment] 2023-09-08 08:24
OK...
First of all I had the idea that the RDP server could influence the situation because RDP-sessions are somehow different from regular local sessions. So I crawled under my desk and grabbed some cables and adapters from dusty boxes to connect my RaspberryPi4 as a local computer (Monitor, Keyboard, Mouse, Network). I can confirm that the problem occur also on a regular local session and not only via RDP.

> Do you see icons if running BiT as user

Yes. None of them are missing.

> Is it the most-recent dev branch version?

Yes it is.

> provide the installed theme names that contain the BiT app icon

```
cd /usr/local/share/icons
find . -name "document-save.*"

cd /usr/share/icons
find . -name "document-save.*"
./Tango/24x24/actions/document-save.png
./Tango/32x32/actions/document-save.png
./Tango/scalable/actions/document-save.svg
./Tango/22x22/actions/document-save.png
./Tango/16x16/actions/document-save.png
./HighContrast/24x24/actions/document-save.png
./HighContrast/32x32/actions/document-save.png
./HighContrast/256x256/actions/document-save.png
./HighContrast/scalable/actions/document-save.svg
./HighContrast/22x22/actions/document-save.png
./HighContrast/16x16/actions/document-save.png
./HighContrast/48x48/actions/document-save.png
./elementary-xfce/actions/48/document-save.png
./elementary-xfce/actions/22/document-save.png
./elementary-xfce/actions/24/document-save.png
./elementary-xfce/actions/16/document-save.png
./elementary-xfce/actions/128/document-save.png
./elementary-xfce-darker/actions/22/document-save.png
./elementary-xfce-darker/actions/24/document-save.png
./elementary-xfce-darker/actions/16/document-save.png
./Adwaita/24x24/legacy/document-save.png
./Adwaita/32x32/legacy/document-save.png
./Adwaita/22x22/legacy/document-save.png
./Adwaita/16x16/legacy/document-save.png
./Adwaita/512x512/legacy/document-save.png
./Adwaita/48x48/legacy/document-save.png
```

> Could you please also show me the active style (part of the "theme") and which styles are really supported on your computer:

OK, I run your pkexec command as user in an xfce terminal.
```
No protocol specified
qt.qpa.xcb: could not connect to display :10.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Abgebrochen
```

> You can enforce a different supported style with this command (to test if all icons are visible in BiT then):

```
pkexec env QT_STYLE_OVERRIDE=oxygen backintime-qt_polkit --debug
DEBUG: [common/backintime.py:589 argParse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.3.4-dev

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/configfile.py:591 Config.setCurrentProfile] Change current profile: 1=Hauptprofil
DEBUG: [common/tools.py:172 initiate_translation] Language code "en".
DEBUG: [common/backintime.py:677 getConfig] config file: /root/.config/backintime/config
DEBUG: [common/backintime.py:678 getConfig] share path: /root/.local/share/backintime
DEBUG: [common/backintime.py:679 getConfig] profiles: 1=Main profile
DEBUG: [common/pluginmanager.py:245 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/tools.py:719 is_Qt5_working] Qt5 probing result: exit code -6
DEBUG: [common/tools.py:722 is_Qt5_working] Qt5 probing stdout: 
DEBUG: [common/tools.py:723 is_Qt5_working] Qt5 probing errout: No protocol specified
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.


DEBUG: [plugins/systrayiconplugin.py:82 init] No system tray available to show the BiT system tray icon
DEBUG: [common/pluginmanager.py:262 PluginManager.load] Add plugin notifyplugin.py
No protocol specified
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted

```

This is how my "Erscheinungsbild" settings look in XFCE
![image](https://github.com/bit-team/backintime/assets/11861496/4a2b95c8-f81d-4939-901e-6c775054d74c)

**Comment by aryoda** [comment] 2023-09-11 08:02
> I wonder if this is an old known issue or if I broke something when refactoring parts of the mainwindow.

I don't think this is a regression but perhaps a "missing dependency" issue or more likely a settings issue with xfce.

- How did you install the dependencies?
- Did you install the original BiT package of Debian first to ensure all known dependencies are installed?
- What is the value of the `QT_QPA_PLATFORMTHEME` env var as root user?
- Could you please check if the `qt5-gtk-platformtheme` package is installed since xfce uses gtk...

But most likely the appearance (used theme) of the Desktop is bound to the user and needs to be setup only once for root too since it seems that Qt5 is not seeing the themes as root (you could compare this debug output when running as non-root on the same machine):

> DEBUG: [qt/qttools.py:240 createQApplication] QT supported styles: ['Windows', 'Fusion']

On my machine (with gnome) it is:
> DEBUG: [qt/qttools.py:236 createQApplication] QT supported styles: ['Breeze', 'cleanlooks', 'gtk2', 'cde', 'motif', 'plastique', 'qt5ct-style', 'Windows', 'Fusion']

BTW: Adwaita is possibly not supported by Qt5 for unknown reasons but it does work as user in your case (right?) so this may not be the reason in our case: https://bbs.archlinux.org/viewtopic.php?id=276345

**Comment by buhtz** [comment] 2023-09-11 08:26
> * How did you install the dependencies?
> * Did you install the original BiT package of Debian first to ensure all known dependencies are installed?

Very good question! I didn't. OK, I installed BIT from Debian (11) repo. But it is BIT 1.2.1 and I'm not able to upgrade that Debian currently. Not sure if this might be fixed in Debian 12 with BIT 1.3.3.

But with 1.2.1 the problem is still there.

Give me a drum roll please... I currently do upgrade from Debian 11 to 12. ⏳ 😨 

> * What is the value of the `QT_QPA_PLATFORMTHEME` env var as root user?

Seems to be not existing; as "sudo su" and as "sudo".

> * Could you please check if the `qt5-gtk-platformtheme` package is installed since xfce uses gtk...

Yes, it is installed (`5.15.2+dfsg-9`).

If this is just a rare case not relevant for most of the users I would say you can move that Issue to another milestone. Don't sound like a 1.4.0 issue to me.

**Comment by buhtz** [comment] 2023-09-11 11:30
"Zonk!". My Pi do not boot anymore. 😆 🚀 Something must went wrong while updating it.

**Comment by aryoda** [comment] 2023-09-11 20:44
> My Pi do not boot anymore

Oh, that's a "pi-lemma" ;-(

Anyhow I have tested the latest dev version on "Debian Trixie Testing" with xfce and Adwaita and BiT root does show the icons.

I have really no clue what is causing this.

Anyhow I am assigning this issue to a later milestone to prepare the upcoming release .

**Comment by emtiu** [comment] 2023-09-11 22:34
> Anyhow I have tested the latest dev version on "Debian Trixie Testing" with xfce and Adwaita and BiT root does show the icons.

Curiously, when trying to test this, I ran into the problem of pkexec complaning that there is "no authentication agent found". Do we have the dependency for this documented somewhere? Did you install something particular to run BiT as root on a Debian/XFCE system?

**Comment by aryoda** [comment] 2023-09-11 23:00
> pkexec complaining that there is "no authentication agent found"

I never had this and BiT did work OOTB (after installing the documented dependencies taking the shortcut to install the old 1.2.1 version of BiT + the missing dependencies).

It looks like there is no authentication agent running.

This is an ARCH doc but the description should be usable for Debian too on how to install and start an auth agent (look for `polkit-1-auth-agent`):

https://wiki.archlinux.org/title/Polkit

**Comment by emtiu** [comment] 2023-09-12 09:00
I fixed up my VM and confirmed with a fresh Debian 12 with xfce-desktop: "Back In Time (root)" runs correctly with icons (in the main window and the systray).

**Comment by buhtz** [comment] 2023-09-14 10:57
I really crashed my system with the upgrade from Debian 11 to 12. 😆 I'm still in it to fresh install and setup my RaspberryPi 4 with latest Debian (12).

I can confirm that (nearly) out-of-the-box the problem do not occur. I can see all icons as root and as user.

Must be a rare situation and setup we can not reproduce anymore. So I vote to close if no one else has new ideas about it.

**Closed as completed** 2023-10-26 04:12 UTC
Labels: Qt, Bug, GUI & Cosmetics
