### ISSUE TITLE
BU existing file during restore nulled file!

### ISSUE THREAD

**Issue by akovia** [bit-team/backintime#1407] opened 2023-02-16 14:38 UTC
Arch Linux: 6.1.12-arch1-1
BIT: backintime 1.3.3-2

I just had a need to restore a file from backup.

When selecting a the file to be restored, it gave the option to backup the existing file and add a timestamp.
"Backup local files before overwriting or removing with trailing .backup.xxxxxx"

I needed that existing file to merge with file I was restoring, but after restoring my file and trying to open the existing file that was backed up. I find it has been nulled!

This is an absolute disaster! How is this possible? I am absolutely gutted that when I actually had a need to use this safety net, it turns out to be cause of my data loss. 

I don't even know what to say.

**Comment by emtiu** [comment] 2023-02-16 20:01
Oh shit :( I'm really, truly sorry that this happened to you.

I've tested this feature, and it doesn't seem to occur in version 1.2.1. I don't have the latest release handy, but I'm sure someone will quickly be able to test and maybe confirm this.

**Comment by buhtz** [comment] 2023-02-16 21:55
Restoring is done by rsync itself. But I'm not sure if rsync or another component does create the backup.xxxxx file first.

I was on the way into my bed and saw your message then. So I did short session and tried to reproduce this but I wasn't able to reproduce. In all my tests the backup file was created and the desired file version was restored from the backup. I was using a SSH profile of course.

 - Debian 11 stable (old rsync 3.2.3)
 - Debian (12) testing (new rsync 3.2.7)
 - Manjaro

I don't have Arch on a VM yet.

Can you give us some more information please.

 - There could be a restore log file. Please look at `~/.local/share/backintime` and look for a file named `restore_.log`.
 - Did you installed BIT from this source? https://aur.archlinux.org/packages/backintime
 - Did you run BIT as user or did you run "BIT root"?
 - Please post the output of `backintime --diagnostics`

Please create some test files and try to reproduce the problem. *BUT* this time run BIT from terminal via `backintime-qt --debug` and show us the output from the terminal.

**Comment by akovia** [comment] 2023-02-16 22:01
Here is the output of the restore.log

```
rsync --recursive --times --devices --specials --hard-links --human-readable -s --links --perms --executability --group --owner --info=progress2 --no-inc-recursive -R -v --backup --suffix=.backup.20230216 /run/media/username/WDG_12TB/Backups/backintime/computername/username/1/20230115-170218-965/backup/./home/username/.bash_eternal_history /
building file list ... done
rsync: [generator] chgrp "/home" failed: Operation not permitted (1)
home/
home/akovia/.bash_eternal_history
sent 1.07M bytes  received 38 bytes  2.14M bytes/sec
total size is 1.07M  speedup is 1.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1336) [sender=3.2.7]
 
 
Restore permissions:
UID for '-' is not available on this system. Using UID 972 from snapshot.

Restore permissions: Done
```

What I don't understand is that it restored the file I needed from backup, but screwed up the existing file it was basically supposed to just rename.

The real kicker is that I had already just renamed that file by adding a `~' to the end, but changed it back in favor of getting the timestamped version that I saw when restoring my file. *sigh*

**Comment by akovia** [comment] 2023-02-16 22:07
Forgot to add diags.

```
 backintime --diagnostics
{
    "backintime": {
        "name": "Back In Time",
        "version": "1.3.3-dev",
        "latest-config-version": 6,
        "local-config-file": "/home/UsernameReplaced/.config/backintime/config",
        "local-config-file-found": true,
        "global-config-file": "/etc/backintime/config",
        "global-config-file-found": false,
        "started-from": "/usr/share/backintime/common",
        "running-as-root": false,
        "user-callback": "/home/UsernameReplaced/.config/backintime/user-callback",
        "keyring-supported": false
    },
    "host-setup": {
        "platform": "Linux-6.1.12-arch1-1-x86_64-with-glibc2.37",
        "system": "Linux #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000",
        "os-release": {
            "NAME": "Arch Linux",
            "ID": "arch",
            "PRETTY_NAME": "Arch Linux",
            "BUILD_ID": "rolling",
            "ANSI_COLOR": "38;2;23;147;209",
            "HOME_URL": "https://archlinux.org/",
            "DOCUMENTATION_URL": "https://wiki.archlinux.org/",
            "SUPPORT_URL": "https://bbs.archlinux.org/",
            "BUG_REPORT_URL": "https://bugs.archlinux.org/",
            "PRIVACY_POLICY_URL": "https://terms.archlinux.org/docs/privacy-policy/",
            "LOGO": "archlinux-logo"
        },
        "display-system": "tty",
        "locale": "en_US, UTF-8",
        "PATH": "/home/UsernameReplaced/.rbenv/shims:/home/UsernameReplaced/.bin:/home/UsernameReplaced/bin:/home/UsernameReplaced/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/UsernameReplaced/.local/.bin",
        "RSYNC_OLD_ARGS": "(not set)",
        "RSYNC_PROTECT_ARGS": "(not set)"
    },
    "python-setup": {
        "python": "3.10.9 main Dec 19 2022 17:35:49 CPython GCC 12.2.0",
        "python-executable": "/usr/bin/python",
        "python-executable-symlink": true,
        "python-executable-resolved": "/usr/bin/python3.10",
        "sys.path": [
            "/usr/share/backintime/qt/plugins",
            "/usr/share/backintime/common/plugins",
            "/usr/share/backintime/plugins",
            "/usr/share/backintime/common",
            "/usr/lib/python310.zip",
            "/usr/lib/python3.10",
            "/usr/lib/python3.10/lib-dynload",
            "/usr/lib/python3.10/site-packages"
        ],
        "qt": "PyQt 5.15.9 / Qt 5.15.8"
    },
    "external-programs": {
        "rsync": {
            "program": "rsync",
            "version": "3.2.7",
            "protocol": "31.0",
            "copyright": "(C) 1996-2022 by Andrew Tridgell, Wayne Davison, and others.",
            "url": "https://rsync.samba.org/",
            "capabilities": {
                "file_bits": 64,
                "inum_bits": 64,
                "timestamp_bits": 64,
                "long_int_bits": 64,
                "socketpairs": true,
                "symlinks": true,
                "symtimes": true,
                "hardlinks": true,
                "hardlink_specials": true,
                "hardlink_symlinks": true,
                "IPv6": true,
                "atimes": true,
                "batchfiles": true,
                "inplace": true,
                "append": true,
                "ACLs": true,
                "xattrs": true,
                "secluded_args": "optional",
                "iconv": true,
                "prealloc": true,
                "stop_at": true,
                "crtimes": false
            },
            "optimizations": {
                "SIMD_roll": true,
                "asm_roll": false,
                "openssl_crypto": true,
                "asm_MD5": false
            },
            "checksum_list": [
                "xxh128",
                "xxh3",
                "xxh64",
                "md5",
                "md4",
                "sha1",
                "none"
            ],
            "compress_list": [
                "zstd",
                "lz4",
                "zlibx",
                "zlib",
                "none"
            ],
            "daemon_auth_list": [
                "sha512",
                "sha256",
                "sha1",
                "md5",
                "md4"
            ],
            "license": "GPLv3",
            "caveat": "rsync comes with ABSOLUTELY NO WARRANTY"
        },
        "ssh": "OpenSSH_9.2p1, OpenSSL 3.0.8 7 Feb 2023",
        "sshfs": "3.7.3",
        "encfs": "(no encfs)",
        "shell": "/bin/bash",
        "shell-version": "GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)"
    }
}

```

**Comment by emtiu** [comment] 2023-02-16 22:41
The first line of your restore.log contains the `--suffix=.backup.20230216` as part of the rsync command that backintime triggered. This is what must have failed somehow, and it's what we should test for.

Maybe it has to do with the fact that you restored a hidden file? It shouldn't, but it makes your case somewhat special. You might want to check if your original file got copied or moved to some unexpected location/name at some point.

**Comment by akovia** [comment] 2023-02-16 23:09
I wouldn't think it would get backed up to some random location, but I did a `sudo updatedb`, and a `locate .bash_eternal_history` to be sure. No dice.

Also, I use rsync quite often and never had any special considerations for hidden files before. Maybe I should have?

Anyway, it's lost now so it doesn't really matter. I hope I won't have need to restore again anytime soon, but will consider this if I do and will backup before restoring with backup existing.

Thanks for the quick replies.
Go get some sleep.

**Comment by Germar** [comment] 2023-02-16 23:55
Backintime uses the rsync options `--backup --suffix=.backup.20230216` for this. If this was a bug than it would be in rsync.

Just shooting into the blue, did you maybe rename and/or reverse rename the file while the restore was already running? This could have confused rsync.

**Comment by akovia** [comment] 2023-02-17 00:10
As I recall it, I renamed manually, and then when I went to restore using BIT, I saw the option to create a timestamped backup so I went and reversed my rename, and then initiated the restore by selecting the `Yes` button.

If it was working in the background while the restore window was open, then maybe, but my file was renamed back to the original before selecting yes.

To backup the existing file, it would have had to identify the file had the same name as the file to be restored before backing it up, so I don't see how that could have happened. Not to say it's impossible, but to me it means the file had to have already been renamed back to the original filename before rsync could have backed it up.

What is strange though is if I look at the file using a hex editor, I can see at the very end of the file that there is still some of the original text. It's not something I want to paste here, but it amounts to about the size of a normal paragraph. Everything before that is zeros. The file size is 193k, so that's just a tiny bit of text that didn't get nulled.

Not sure if that's helpful or not.

**Comment by buhtz** [comment] 2023-02-17 07:32
I'm not able to test on Arch because of there time consuming "installation process". 😄 But I assume that Manjaro is also enough.

> The real kicker is that I had already just renamed that file by adding a `~' to the end, but changed it back in favor of getting the timestamped version that I saw when restoring my file. _sigh_

This sounds interesting. Can you please explain this and all the tiny steps in more details; like to a six year old.
Can you also explain us more about the content and nature of that file. Is it plain text or binary?

I'm not sure but I tend to assume that the root of the problem depends on that renaming and something different then BIT/rsync that was involved. But we are always interested in edge cases. No matter if BIT/rsync or something else is responsible for the data lose I see an opportunity to protect future users for cases like this. That is why I would like to investigate that in details.

Please try to reproduce the problem. I see no problem with using the same in-productive-use snapshot profile. Just create a dummy file with some content, do a snapshot, modify the file. Try to restore. And do your renaming thing also.

For myself screenrecordings (as GIF files, e.g. with [peek](https://github.com/phw/peek)) would also help to better understand what happens on your site.

**Comment by akovia** [comment] 2023-02-17 22:15
The file is my command history from my terminal. Basically, bash history. I will develop personal scripts and other commands right in my terminal, and I use [a small program](https://github.com/dvorka/hstr) that makes it easy to recall these commands. 

I've used this for years, then abruptly the other day I noticed most of my commands were missing. After investigating I realized that the 1mb file size I set so many years back was triggered and it wiped my history. So yes. it's just a plain text file.

I believe the sequence I detailed is accurate. I started by backing up the local file by adding the tilde, then opened BIT to restore from my most recent backup. When I initiated the backup I noticed the built in option to timestamp any existing files which I thought was a better idea than just a tilde. I then restored the original filename by removing the tilde, returned to BIT, enabled the timestamp feature and clicked "Yes".

I don't have time to troubleshoot right now, but will try to recreate what happened and let you know if I can replicate it.

**Comment by buhtz** [comment] 2023-03-03 10:08
Added "Heisenbug" because problem is not reproducible and quit confusing.
Also reduced priority from High to Medium because of that.

**Comment by buhtz** [comment] 2023-06-29 12:58
Hello @akovia ,
do you have tried to replicate the problem on your side?

**Comment by akovia** [comment] 2023-07-01 21:58
> Hello @akovia , do you have tried to replicate the problem on your side?
No

I have successfully used this since posting without issue, so I'm not really sure what happened that time. I've updated my system many times since then as well, so I have no idea if that changed anything, but it is working as expected now.

Thanks for checking back!

**Comment by buhtz** [comment] 2023-07-02 07:02
Thanks for reporting back. Still feeling a bit insecure about what was going on here and if it maybe is an BIT bug.
Germar offered the idea about renaming which might was the cause.

I will close the issue in the near future.

**Closed as completed** 2023-09-26 17:55 UTC
Labels: Medium, Bug, Heisenbug
