### ISSUE TITLE
Can't run backintime on Linux Mint

### ISSUE THREAD

**Issue by codesmaker** [bit-team/backintime#1013] opened 2019-07-04 11:10 UTC
Hi,

I've recently installed BIT on Linux mint but when I run it, I get the following error:

`Back In Time
Version: 1.2.0

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 1592, in <module>
    cfg = backintime.startApp('backintime-qt')
  File "/usr/share/backintime/common/backintime.py", line 521, in startApp
    return getConfig(args, False)
  File "/usr/share/backintime/common/backintime.py", line 669, in getConfig
    cfg = config.Config(config_path = args.config, data_path = args.share_path)
  File "/usr/share/backintime/common/config.py", line 279, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1715, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1`

I'm running Linux Mint 19.1 Tessa. Any idea?

**Comment by MostHated** [comment] 2019-07-08 22:59
Hey there, I found that if you uninstall it, then download the tar from here and go into it, into the qt folder and then run ./backintime-qt it loaded up just fine, but only when it was removed as a package. Not sure exactly what is up with that. I am not sure yet if it will still run on a schedule properly though when it is not installed. I will have to try and test it.

**Comment by MostHated** [comment] 2019-07-09 03:03
Looks like it did fire up and ran my backup, so looks like all is well I guess

**Comment by codesmaker** [comment] 2019-07-11 08:40
Hi,

Will give it a try. Thanks.

**Comment by buhtzz** [comment] 2022-09-26 08:45
@MostHated There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Bug

Duplicate. Maybe of #1052

**Comment by emtiu** [comment] 2022-10-08 21:59
Closing as duplicate of #921.

**Closed by emtiu** 2022-10-08 21:59 UTC
