### ISSUE TITLE
What is the purpose of errorcode == 2 in user-callback script?

### ISSUE THREAD

**Issue by klayman** [bit-team/backintime#786] opened 2017-06-29 03:18 UTC
I have set up a second backup profile recently and since then my user-callback script (based on the [default one](https://github.com/bit-team/user-callback/blob/master/user-callback.default)) regularly warns me that BackInTime is already running.

My main profile runs hourly local backup and my second profile is for daily backup over sshfs. Before I changed `global.use_flock=true` to `false` in the config file, I received double warnings when BIT tried to run both backup jobs simultaneously. But even with `global.use_flock` disabled I receive that warning every 15 minutes while remote backup is running.

Is it safe to suppress that warning? Is it ok that BackInTime tries to launch the anacron daily job every 15 minutes regardless of the current backup job status? Or, perhaps, BIT should issue an errorcode 2 only when user manually starts a backup job while scheduled backup is running?

**Comment by Germar** [comment] 2017-06-29 20:51
This shouldn't be related to additional profiles because the lock in question is used per profile. Please post the return of `crontab -l`

**Comment by klayman** [comment] 2017-06-30 01:28
Here is my crontab:
```
#Back In Time system entry, this will be edited by the gui:
0 7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job >/dev/null 2>&1
#Back In Time system entry, this will be edited by the gui:
*/15 * * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime --profile-id 2 backup-job >/dev/null
```
If `global.use_flock` is set to `true`, I get the double warnings at *:00 (when both backup jobs are running simultaneously).

**Comment by Germar** [comment] 2017-07-02 19:48
I can't reproduce this here, sorry. Please send me you `~/.config/backintime/config`

**Comment by klayman** [comment] 2017-07-03 03:55
Ok, here is my [config file](https://gist.github.com/klayman/5aad6cc00c2e348a2eb0765274042f38).

**Comment by Germar** [comment] 2017-07-03 20:05
Still no errors here, sorry. Please make a test with a simple user-callback which just returns all args
```
#!/bin/bash
echo $@
```
add `--debug` to both commands in crontab (run `crontab -e` for this) and post the relevant part of your `/var/log/syslog` after next *:00 run.

**Comment by klayman** [comment] 2017-07-05 02:54
Here are [backintime-related logs](https://gist.github.com/klayman/84f8a70355a2879b361816ac4185a79b) (I'm using fedora, so it's journalctl output) around 8:45, 9:00 and 9:15.

Besides `echo` I added the commands to mount and unmount the necessary drives to my `user-callback`.

I've set `global.use_flock=true` in my config, but don't see the double warnings around 9:00 that I've seen before. So, in the time frame of 8:45-9:16 `user-callback` was called 4 times in total with the following args:
```
2 secondprofile 7
2 secondprofile 1
2 secondprofile 4 2
2 secondprofile 4 2
```
and later, when it finished, backup for first profile was performed as usual:
```
2 secondprofile 3 snapshot-id /path/to/snapshot
2 secondprofile 2
2 secondprofile 8
1 firstprofile 7
1 firstprofile 1
1 firstprofile 3 snapshot-id /path/to/snapshot
1 firstprofile 2
1 firstprofile 8
```

**Comment by Germar** [comment] 2017-07-08 20:53
I just made myself a new Fedora 25 VM and tried to reproduce this. But I'm sorry to say that I can't reproduce your result. BiT just react like it should and does not call `user-callback` with error-code 2 here.

Maybe there is something wrong in your shares folder where the locks are located. Please remove `~/.local/share/backintime` (or move temporary) and test again.

**Comment by klayman** [comment] 2017-07-09 10:15
I appreciate your help, but unfortunately moving that folder didn't help. Does backintime rely on any external tools when setting the locks or when checking for the "already running" status?

I'll try to remove mount/unmount commands from the `user-callback` (leave `echo` only) and mount all drives manually.

**Comment by Germar** [comment] 2017-07-09 15:49
Nope. That's all pure python code.

Do you use any fancy filesystems for your /home or /tmp?

**Comment by klayman** [comment] 2017-07-10 03:00
Even when I mount all the drives manually the problem persists.

Nothing special for filesystems: /home is ext4 and /tmp is tmpfs.

**Comment by buhtz** [comment] 2017-10-14 06:56
Can you please post a minimal working and error-reproducing example of your user-callback script?

**Comment by klayman** [comment] 2017-10-15 17:05
I can reproduce the error with the user-callback script suggested by Germar:
```
#!/bin/bash
echo $@
```
I also was able to reproduce the error in a virtual machine with that script. Currently a crontab entry was set to run every 15 minutes, but I adjusted the config to set the custom backup time explicitly. I'll try to make it in a cleaner way and if the error persists, I'll share the VM later.

**Comment by klayman** [comment] 2017-10-16 05:47
Ok, here are the steps to reproduce this error:

1. import this file into VirtualBox: [https://yadi.sk/d/sTfvK4TZ3Nn9qo](https://yadi.sk/d/sTfvK4TZ3Nn9qo) (~1.2 GB)

2. login as `user`, password: `password`

3. mount a remote file system to `/media/sshfs/`. I used the following command line:
    ```
    sshfs -o follow_symlinks,reconnect,ServerAliveInterval=5,ServerAliveCountMax=3 myuser@remotehost:/some/dir/ /media/sshfs/
    ```
    to connect to my web server containing 9880 files in 912 folders totaling 907 MB - even with a fast connection the backup job takes more than 30 minutes to complete.

4. approximately an hour later check the
    ```
    journalctl | grep user-callback
    ```
    from `root` (password: `rootpassword`). There should be some lines like these:
    ```
    INFO: user-callback returned '2 sshfs 4 2'
    ```

**Comment by buhtzz** [comment] 2022-09-25 07:49
@klayman There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

**Comment by klayman** [comment] 2022-09-25 13:27
@buhtzz I can't say it's still relevant. I just commented out this case in my user callback script because I don't understand the purpose of this warning.

**Comment by buhtz** [comment] 2024-02-26 10:09
Dear klayman,
can you please do a new test with your setup please re-enabling the error code in your script?

I wonder if it is still reproducible on your site. I assume it is something about the lock-file handling. Which is quit complicate. We do our self some research about that files and how BIT handles them. The result can be found here in our developers documentation: https://github.com/bit-team/backintime/blob/dev/common/doc-dev/4_Control_files_usage_(locks_flocks_logs_and_others).md

Can you take a look there? This might help identifying the problem.

**Comment by klayman** [comment] 2024-02-27 02:26
Hello and thanks for following up!

That's been a while since my last message. Currently I'm on Fedora 36 and I can't reproduce the issue. I think it may be closed.

Thank you!

**Comment by buhtz** [comment] 2024-02-27 08:55
Thanks a lot for your reply. Please re-open if the issue comes up again.

I do assume the issue was rooted in a problem with the lock files.
If my team mates don't veto, we can close it.

**Comment by buhtz** [comment] 2024-03-28 08:48
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,

**Closed by buhtz** 2024-03-28 08:48 UTC
Labels: Bug, User-Callback, Close after cooling-off period
