### ISSUE TITLE
mountpoint permission denied

### ISSUE THREAD

**Issue by ghost** [bit-team/backintime#637] opened 2016-09-19 20:29 UTC
Hi, I'm trying to get backintime to work with a synology nas.
I have password less ssh login.

I followed 
https://github.com/bit-team/backintime/wiki/FAQ#how-to-use-synology-dsm-6-with-bit-over-ssh

However I get these 

INFO: mount ssh: backup@XXX.XXX.X.XX:./ on /home/XXXX/.local/share/backintime/mnt/85D16ECC/mountpoint
Traceback (most recent call last):
  File "/usr/share/backintime/common/tools.py", line 189, in make_dirs
    os.makedirs( path )
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/XXXXX/.local/share/backintime/mnt/tmp_2_8620/backintime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/qt4/settingsdialog.py", line 1698, in accept
    if self.validate():
  File "/usr/share/backintime/qt4/settingsdialog.py", line 1452, in validate
    if not self.save_profile():
  File "/usr/share/backintime/qt4/settingsdialog.py", line 1351, in save_profile
    ret = self.config.set_snapshots_path( snapshots_path, mode = mode )
  File "/usr/share/backintime/common/config.py", line 386, in set_snapshots_path
    tools.make_dirs( full_path )
  File "/usr/share/backintime/common/tools.py", line 192, in make_dirs
    %(path, str(e)), self, 1)
NameError: name 'self' is not defined
^CTraceback (most recent call last):
  File "/usr/share/backintime/qt4/app.py", line 647, in raise_application
    def raise_application( self ):

Any help?
I must say this is a second backup profile. The first is a local one.

**Comment by Germar** [comment] 2016-09-19 20:43
Please check write permissions for `backup` user in the remote folder.

The second exception is a bug which has been fixed in 2f11d66. Normally this should show a warning that it wasn't able to create those folders.

**Comment by ilpepe** [comment] 2016-09-20 06:44
That on the remote folder?
It is is the users home folder? backup user has 700 rights on that folder....

**Comment by Germar** [comment] 2016-09-20 12:36
Please download [this patch](https://gist.github.com/Germar/bd2eb052018f22cb55ec1dd82d32e6af) and apply it with
```
sudo patch /usr/share/backintime/common/tools.py < tools-1.1.12.patch
```

**Comment by ilpepe** [comment] 2016-09-20 18:35
applied it.
error now:
INFO: mount ssh: backup@192.168.1.98:./ on /home/XXXXX/.local/share/backintime/mnt/85D16ECC/mountpoint
ERROR: Failed to make dirs '/home/XXXXXX/.local/share/backintime/mnt/tmp_2_5395/backintime/laroebi/pieter/2': [Errno 13] Permission denied: '/home/XXXXX/.local/share/backintime/mnt/tmp_2_5395/backintime'

the permission of the mountpoint is user:root, so it makes sense BiT doesn't have the rights to create the necessary dirs.

Fix?
BiT doens't have to be run as root right?
 
More info maybe: using ubuntu-mate 16.04...

**Comment by Germar** [comment] 2016-09-20 20:05
No, you don't need to run BiT as root. Only if you want to backup system files which are only read/writeable by root.

Looks like you ran `sudo backintime` before. This makes BiT run as root but using your users home instead of `/root` which made your users files owned by root. `sudo` does not change `$HOME` by default. Only if you run `sudo -i`.

Please make sure, no instance of BiT is running and delete `/home/XXXXX/.local/share/backintime/mnt/` with `sudo`. BiT will recreate it next time.

**Comment by ilpepe** [comment] 2016-09-20 21:07
Thanks for the replies!
However this didn't solve it... Same situation....
other tips/hints of things I could/should check?

**Comment by Germar** [comment] 2016-09-21 23:59
Please try this:

```
mkdir /tmp/mnt
sshfs backup@XXX.XXX.X.XX:./ /tmp/mnt/   # replace X of course
mkdir /tmp/mnt/backintime/laroebi/pieter/2
fusermount -u /tmp/mnt
```

And double check on remote host if those folders have been created. Sorry, I'm out of ideas here...

**Comment by buhtzz** [comment] 2022-09-25 07:31
Close. Reporting account not exist anymore. Reproduction impossible.

**Closed** 2022-10-22 14:21 UTC
