### ISSUE TITLE
Python error when clicking on "Take Snapshot"

### ISSUE THREAD

**Issue by knochenhans** [bit-team/backintime#730] opened 2017-03-29 21:07 UTC
Hi, Back In Time does nothing for me when I click on "Take Snapshot". Running backintime-qt4 in the terminal I see the following Python error:
> Traceback (most recent call last):
>   File "/usr/share/backintime/qt4/app.py", line 873, in on_btn_take_snapshot_clicked
>     backintime.take_snapshot_now_async( self.config )
>   File "/usr/share/backintime/common/backintime.py", line 69, in take_snapshot_now_async
>     subprocess.Popen(cmd, env = env)
>   File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.6/subprocess.py", line 1326, in _execute_child
>     raise child_exception_type(errno_num, err_msg)
> FileNotFoundError: [Errno 2] No such file or directory: 'backintime backup &'

**Comment by Germar** [comment] 2017-03-29 21:57
Duplicate of #728 

Please upgrade to 1.1.18 from stable PPA. Sorry for the troubles

**Closed by Germar** 2017-03-29 21:57 UTC
Labels: duplicate
