### ISSUE TITLE
Remove Snapshots: Deleted backups do not disappear and back again after restart

### ISSUE THREAD

**Issue by ralmond** [bit-team/backintime#1170] opened 2021-06-23 16:42 UTC
I'm having issues with disk space on my backup drive (external USB drive) and constantly getting messages from the OS about 0 space left.
I know that BiT is supposed to autodelete old backups, but there are some really old backups (several months ago) on the list, which I can get it do delete.
So I try selecting them in the list and press the "Remove Snapshot" button.  I get a confirmation dialog, and then the selected backups are greyed out.  But they don't seem to disappear, and if I restart BiT they are back again.

Is there another step to this process I'm missing?
I'm running BiT 1.2.1 under Pop OS (Ubuntu fork) 20.10.

**Comment by hoehnp** [comment] 2022-04-02 15:09
I can confirm this with 1.3.1 and also wonder why the snapshots are not deleted.

**Comment by buhtz** [comment] 2023-12-07 12:05
We have not modified the remove snapshots code yet.
But might it be possible to check again with the latest BIT version and give us some more instructions to reproduce it.

Does the initially reported system still exists? Can you give details about the used file system and file permissions?
One shot into the blue by myself is that the file permission are not enough to delete that old snapshot. How old is old?

**Comment by ralmond** [comment] 2023-12-07 17:09
Unfortunately, the disk I was using for backups died.  This may have been a disk error, and not an internal BiT problem.  So I can't reproduce.

**Comment by aryoda** [comment] 2023-12-07 19:44
> Unfortunately, the disk I was using for backups died. This may have been a disk error, and not an internal BiT problem. 

Thanks for your feedback and sorry for your (hopefully "only") hardware loss.

> So I try selecting them in the list and press the "Remove Snapshot" button. I get a confirmation dialog, and then the selected backups are greyed out. But they don't seem to disappear, and if I restart BiT they are back again.

If have just tested this scenario with different workflows using BiT v1.4.2-dev:

1. Mark one snapshot and delete it with the "remove snapshot" button
2. Mark two snapshots and delete them with the button
3. Mark one snapshot and delete it with the `del` key

In all three scenarios the affected snapshots were grayed out shortly (= indicating that the deletion is in progress) and disappeared then from the snapshot list once the snapshot folder was completely deleted.

I have also checked that the snapshot folder was really deleted.

I think that "snapshot was grayed out but did not disappear" is a possible indicator that the snapshot folder could not be deleted (took forever eg. due to retrying it) due to the hardware failure.

I vote to close this issue after a grace period...

**Closed** 2024-02-16 07:12 UTC
Labels: Bug, Feedback, Heisenbug
