### ISSUE TITLE
Could not unlock ssh private key. Wrong password or password not available for cron.

### ISSUE THREAD

**Issue by patrickdrouin** [bit-team/backintime#1198] opened 2021-11-23 22:12 UTC
Hello,
I acquired a new machine and I'm trying to set up backintime as I previously used it before. I restored the previous config file. There seems to be some problems with the private keys. I poked around and saw a few things to check but I can figure it out. I get the "**Could not unlock ssh private key. Wrong password or password not available for cron.**" message when I start baackintime or when I try to save the config. 

**Settings**
![backintime1](https://user-images.githubusercontent.com/2301477/143136207-0511fe00-adc2-49a5-b22e-0fddd3e05850.jpeg)

**SSH keys check**
![backintime2](https://user-images.githubusercontent.com/2301477/143136217-f95346fe-fd17-4f91-b1ea-7a1ed0c8f05b.jpeg)

**Debug info from backintime**
![backintime3](https://user-images.githubusercontent.com/2301477/143136224-a3355598-3a85-40b5-a474-422d3f3538cc.jpeg)

I do see some problems in the logs but I don't know if it points to the local of the remote machine. 
**Logs**
![image](https://user-images.githubusercontent.com/2301477/143137114-87fa40da-a73a-4816-ac5e-5aadfdfbaf99.png)

Which leads me to believe it has a problem to access 
![image](https://user-images.githubusercontent.com/2301477/143137215-ce7aec68-730c-401d-aba0-1cddd3f60614.png)

But since ssh is working properly and the file is there, I am confused....  Any help will be appreciated. 
Thanks

**Comment by vvranjek** [comment] 2022-03-28 13:16
I have the same problem on Ubuntu 22.04.

**Comment by emtiu** [comment] 2022-09-24 12:35
Related to #1025.

**Comment by aryoda** [comment] 2022-10-19 11:44
@patrickdrouin Please try `ssh-add /home/drouinp/.ssh./id_rsa` in the console and report if it works (that is exactly what BiT is trying).

**Comment by aryoda** [comment] 2022-10-19 11:59
@patrickdrouin @vvranjek 

In order to use this mode the remote host need to be in your known_hosts file.
This requires a manual step before BiT can connect.

Please follow the steps documented here and report if it works:

https://backintime.readthedocs.io/en/latest/settings.html#ssh

**Comment by buhtz** [comment] 2023-10-09 12:31
Not sure but in my understanding the problem is solved and the issue can be closed?

**Comment by aryoda** [comment] 2023-10-09 13:23
@patrickdrouin @vvranjek Could you please give us feed back
- if and how you could solve the issue
- if the new release works (~though I am not aware of any special code change that would affect you since you are not using the `keyring` package~):
  https://github.com/bit-team/backintime/releases

**Comment by aryoda** [comment] 2023-10-09 23:09
The man page (`man backintime`) explains how the cache is working so I suppose this issue may have been caused by the new default `Chainer` keyring and is already fixed via https://github.com/bit-team/backintime/issues/1410:

>  A backup cronjob during the user isn't logged in can  not  collect  the
>  password  from keyring. Also if the homedir is encrypted the keyring is
>  not accessible from cronjobs (even if the user is logged in). For these
>  cases  the  password can be cached in RAM. If 'Cache Password for Cron'
>  is activated Back In Time will start a small daemon in user-space which
>  will  collect  the password from keyring and provide them for cronjobs.
>  They will never be written to the harddrive but a user with  root  per‐
>  missions could access the daemon and read the password.


There is another possible solution for this issue described here:

https://github.com/bit-team/backintime/issues/1025#issuecomment-517961838

**Comment by buhtz** [comment] 2024-01-09 08:50
@patrickdrouin Feel free to re-open the Issue if it is still relevant for you.

**Closed by buhtz** 2024-01-09 08:50 UTC
Labels: Bug, Feedback

**Comment by casimir7** [comment] 2024-12-28 14:18
Unfortunately, this bug seems to be reappearing.
In my configuration the target is a NAS on the local network that I access via ssh.

I tried `ssh-add /home/$USER/.ssh./id_rsa` and indeed `ssh-add -l` lists the key. Also direct connection to the NAS does work normally.
I also removed BiT completely (including all configuration files) and reinstalled freshly with the same result

`journalctl` only gives the following lines whenever I try to access the backup directory or start BiT:
```
Dec 28 15:06:56 $hostname backintime-qt[6578]: ERROR: Failed to unlock SSH private key /home/$user/.ssh/id_rsa:
Dec 28 15:06:56 $hostname backintime[6578]: Main profile(1) :: ERROR: Failed to unlock SSH private key /home/$user/.ssh/id_rsa:
Dec 28 15:06:57 $hostname backintime-qt[6578]: WARNING: Snapshot path does not exists: $snapshotdir
Dec 28 15:06:57 $hostname backintime[6578]: Main profile(1) :: WARNING: Snapshot path does not exists: $snapshotdir

```
(where I replaced the actual names and paths with the $variables)
No other suspicious errors are reported in connection with BiT.

My version is backintime 1.5.3 on fedora 40. I cannot clearly state when it worked last, as I used BiT only a few months ago (and years before that without problems).

Please advise if you need further info!

**Comment by buhtz** [comment] 2024-12-28 14:27
Please open a new issue.
Do you run bit in root Mode?
Show the file permission of the key file please via ls-l

**Comment by casimir7** [comment] 2024-12-29 14:15
Thank you @buhtz. I opened a new issue [#1985](https://github.com/bit-team/backintime/issues/1985) for this and added the requested information.
