### ISSUE TITLE
Current development version c65fc91 leaves dbus-launch.x11 instances

### ISSUE THREAD

**Issue by ptilopteri** [bit-team/backintime#1638] opened 2024-02-04 18:07 UTC
current development version c65f91 leaves instances of dbus-launch.x11 after finishing. each backup adds another instances of dbus-launch.x11 and I have seen these instances committing heavy CPU usage via "/usr/bin/Xorg.bin -nolisten tcp -background none -seat....."

**Comment by ptilopteri** [comment] 2024-02-04 18:11
current development version c65f91 leaves instances of dbus-launch.x11 after finishing.  each backup adds another instances of dbus-launch.x11 and I have seen these instances committing heavy CPU usage via "/usr/bin/Xorg.bin -nolisten tcp -background none -seat....."

**Comment by buhtz** [comment] 2024-02-05 08:29
Dear ptilopteri,
thanks for your report.

I like that idea. And we have this still implemented somehow. If BIT starts from a git repo then you will find the current git hash in the About dialog.

https://github.com/bit-team/backintime/blob/c65fc917a245bdf7dbedc7b12768bf51be39d2c9/qt/app.py#L1842-L1846

But I also support the idea to add the git hash (and branch name maybe) to the version string and also maybe in the window title.

Next time when reporting please consider the use of correct upper case letters (e.g. beginn of sentences, the word "I", ...). It is then more easier to read for us and others. Thanks in advance.

**Comment by ptilopteri** [comment] 2024-02-05 13:39
* buhtz ***@***.***> [02-05-24 03:31]:
> Dear ptilopteri,
> thanks for your report.
> 
> I like that idea. And we have this still implemented somehow. If BIT starts from a git repo then you will find the current git hash in the About dialog.
> 
> https://github.com/bit-team/backintime/blob/c65fc917a245bdf7dbedc7b12768bf51be39d2c9/qt/app.py#L1842-L1846
> 
> But I also support the idea to add the git hash (and branch name maybe) to the version string and also maybe in the window title.
> 
> Next time when reporting please consider the use of correct upper case letters (e.g. beginn of sentences, the word "I", ...). It is then more easier to read for us and others. Thanks in advance.
> Message ID: ***@***.***>

I'm lost.  This in some manner is applicable to BiT leaving instances of
"dbus-launch.x11" after finishing a root cron backup sessin?

and for the record, it only happens on instances started by a root cron
job.


-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by emtiu** [comment] 2024-02-05 14:02
> I'm lost. This in some manner is applicable to BiT leaving instances of "dbus-launch.x11" after finishing a root cron backup sessin?

@buhtz just posted in the wrong Issue by accident. I'm hiding these comments on GitHub for clarity.

Thank you for your report!

**Comment by aryoda** [comment] 2024-02-08 01:01
I think this is a duplicate of #1592 and does not add additional helpful information so I would close this as duplicate and pursue a fix via #1592

**Comment by buhtz** [comment] 2024-06-17 07:12
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,
Christian

**Closed as completed by buhtz** 2024-06-17 07:12 UTC
Labels: Discussion, Bug
