### ISSUE TITLE
AttributeError: 'module' object has no attribute 'warning'

### ISSUE THREAD

**Issue by rain0r** [bit-team/backintime#494] opened 2015-11-13 12:44 UTC
I got this message since upgrading to backintime-1.1.8 on Gentoo:

```
$ backintime-qt4 
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/app.py", line 31, in <module>
    import backintime
  File "/usr/share/backintime/common/backintime.py", line 23, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 31, in <module>
    import configfile
  File "/usr/share/backintime/common/configfile.py", line 19, in <module>
    import logger
  File "/usr/share/backintime/common/logger.py", line 23, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 1173, in <module>
    logger.warning('import keyring failed')
AttributeError: 'module' object has no attribute 'warning'
```

And also:
```
$ backintime
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 23, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 31, in <module>
    import configfile
  File "/usr/share/backintime/common/configfile.py", line 19, in <module>
    import logger
  File "/usr/share/backintime/common/logger.py", line 23, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 1173, in <module>
    logger.warning('import keyring failed')
AttributeError: 'module' object has no attribute 'warning'
```

I am using backintime with Python 3.4

**Comment by Germar** [comment] 2015-11-13 22:00
Duplicate of #473

**Closed by Germar** 2015-11-13 22:00 UTC
Labels: duplicate
