### ISSUE TITLE
App blocks for too long on quit

### ISSUE THREAD

**Issue by Suor** [bit-team/backintime#491] opened 2015-11-12 04:31 UTC
When I press cross to close app this happens:
- UI blocks for a few seconds
- UI greys out
- "Force Quit" dialog is shown
- app closes, dialog disappears

![backintime-closing](https://cloud.githubusercontent.com/assets/284103/11110597/2fb1ee10-8928-11e5-82ca-ee826a1c6711.png)

**Comment by Germar** [comment] 2015-11-22 23:38
I can't reproduce this here. You're using mode SSH, right? Could you please apply [this patch](https://gist.github.com/Germar/fd749a64374eea6bb463) and try again?

```
sudo patch /usr/share/backintime/qt4/app.py < app.diff
```

**Comment by Suor** [comment] 2015-11-23 04:42
I use luks-encoded external USB HDD. Root mode, about 20GB starting backup. About 10 backups now.
Backup In Time start is also slow - several seconds between launch from Unity Dash and window appearance.

**Comment by emtiu** [comment] 2022-09-12 10:01
Hi, we're sorting out old Issues with backintime. Could you kindly tell us: Is this still relevant to you; did you ever find a cause/solution to this problem?

**Comment by Suor** [comment] 2022-09-12 10:46
Haven't used backintime for some time, but don't remember any issues last time. So maybe it work now 🤔

**Comment by emtiu** [comment] 2022-09-12 11:06
Thanks for the information, we'll close this issue then :)

**Closed by emtiu** 2022-09-12 11:06 UTC
Labels: Bug, Feedback
