### ISSUE TITLE
Backup Failed in Ubuntu 16.04 Server

### ISSUE THREAD

**Issue by hokgt** [bit-team/backintime#1011] opened 2019-06-22 03:41 UTC
I clone backintime from github and installed only common without qt as I'm using headless server. Installation going smoothly, I installed all depedencies with python 3.5 and after installation setup config file, learn it carefully from man backintime-config and change parameters from example config file then copy it to config folder.

```
 +--------------------------------+
 |  Check/prepair snapshot path   |
 +--------------------------------+
Check/prepair snapshot path: done

 +--------------------------------+
 |          Check config          |
 +--------------------------------+
Check config: done

 +--------------------------------+
 |        Install crontab         |
 +--------------------------------+
Install crontab: done

Config /home/hok/.config/backintime/config profile 'Main profile' is fine.
```

Then I check the config file with backintime check-config to make sure everything fine. But when I try to take snapshot manually backintime backup, it's not taking the snapshot with below messages:

```
Back In Time
Version: 1.2.0

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
WARNING: Inhibit Suspend failed.
INFO: Take a new snapshot. Profile: 1 Main profile
INFO: Call rsync to take the snapshot
INFO: Nothing changed, no new snapshot necessary
WARNING: No new snapshot
INFO: Unlock
```

I try to debug the backup process by backintime backup --debug
```
DEBUG: [common/backintime.py:670 getConfig] config file: /home/hok/.config/backintime/config
DEBUG: [common/backintime.py:671 getConfig] share path: /home/hok/.local/share/backintime
DEBUG: [common/backintime.py:673 getConfig] profiles: 1=Main profile
DEBUG: [common/pluginmanager.py:90 PluginManager.load] Register plugin path /usr/share/backintime/plugins
INFO: [common/snapshots.py:634 Snapshots.backup] Lock
WARNING: [common/tools.py:1188 inhibitSuspend] Inhibit Suspend failed.
DEBUG: [common/tools.py:822 keyringSupported] No appropriate keyring found. 'keyring.backends.chainer' can't be used with BackInTime
DEBUG: [common/mount.py:73 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:82 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
INFO: [common/snapshots.py:666 Snapshots.backup] Take a new snapshot. Profile: 1 Main profile
INFO: [common/snapshots.py:1022 Snapshots.takeSnapshot] Call rsync to take the snapshot
DEBUG: [common/snapshots.py:692 Snapshots.backup] Call command "rsync --recursive --times --devices --specials --hard-links --human-readable --links --perms --executability --group --owner --info=progress2 --no-inc-recursive --delete --delete-excluded -v -i --out-format=BACKINTIME: %i %n%L --chmod=Du+wx --exclude=/home/hok/backup/server-snapshot --exclude=/home/hok/.local/share/backintime --exclude=.local/share/backintime/mnt --include=/home/USER/ --include=/home/ --exclude=.gvfs --exclude=.cache* --exclude=[Cc]ache* --exclude=.thumbnails* --exclude=[Tt]rash* --exclude=*.backup* --exclude=*~ --exclude=/home/USER/Ubuntu One --exclude=.dropbox* --exclude=/proc/* --exclude=/sys/* --exclude=/dev/* --exclude=/run/* --include=/home/USER/** --exclude=* / /home/hok/backup/server-snapshot/backintime/mserver/hok/1/new_snapshot/backup"
DEBUG: [common/snapshots.py:692 Snapshots.backup] Command "rsync --recursiv..." returns 0
DEBUG: [common/snapshots.py:1059 Execute.takeSnapshot] Call command "rsync -a --delete /tmp/tmp70z3uwtw/ /home/hok/backup/server-snapshot/backintime/mserver/hok/1/new_snapshot"
DEBUG: [common/snapshots.py:1059 Execute.takeSnapshot] Command "rsync -a --delet..." returns 0
INFO: [common/snapshots.py:1060 Snapshots.takeSnapshot] Nothing changed, no new snapshot necessary
DEBUG: [common/tools.py:1117 writeTimeStamp] write timestamp '20190622 1020' into file '/home/hok/.local/share/backintime/anacron/1_Main_profile'
DEBUG: [common/snapshots.py:701 Execute.backup] Call command "rsync -a --delete /tmp/tmpufherbfl/ /home/hok/backup/server-snapshot/backintime/mserver/hok/1/20190622-102022-384"
DEBUG: [common/snapshots.py:701 Execute.backup] Command "rsync -a --delet..." returns 0
WARNING: [common/snapshots.py:708 Snapshots.backup] No new snapshot
DEBUG: [common/snapshots.py:1398 Snapshots.freeSpace] No snapshots. Skip freeSpace
DEBUG: [common/tools.py:822 keyringSupported] No appropriate keyring found. 'keyring.backends.chainer' can't be used with BackInTime
DEBUG: [common/mount.py:73 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:82 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
INFO: [common/snapshots.py:739 Snapshots.backup] Unlock
```

I realized the are some problem with the keyring from the message 
`No appropriate keyring found. 'keyring.backends.chainer' can't be used with BackInTime`
Then I do some study and found something from #545, check version of my server python keyring, the version is 7.3 then I upgrade the keyring to version 19.02 (latest) but the problem still persist. 

I already installed `python-keyring` `libcanberra-gtk-module` `python-secretstorage` `python-gnomekeyring`.

Try running `backintime pw-cache stop` show below messages:
```
WARNING: Failed to read PID and process name from /home/hok/.local/share/backintime/password_cache/PID: [2] No such file or directory
ERROR: pidfile /home/hok/.local/share/backintime/password_cache/PID does not exist. Daemon not running?
```

Here is what I get when running `python -c "import keyring; print(keyring.get_keyring())"`
`<keyring.backends.file.EncryptedKeyring object at 0x7fe564630190>`

**Comment by hokgt** [comment] 2019-06-29 23:23
Hi, anybody can help me with this? Thank you

**Comment by buhtzz** [comment] 2022-09-26 08:41
@hokgt There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Bug, Feedback

Is it a duplicate of #988 ?

**Comment by aryoda** [comment] 2022-10-07 14:15
May be related to #1321 but only if you are using a keyring to store the password for a backintime backup...

**Comment by emtiu** [comment] 2022-10-22 20:40
Closing, because the reporter isn't responding and we cannot reproduce.

**Closed by emtiu** 2022-10-22 20:40 UTC
Labels: Bug, Feedback
