### ISSUE TITLE
Failed to unlock SSH private key after update to 1.1.14

### ISSUE THREAD

**Issue by mauromol** [bit-team/backintime#726] opened 2017-03-27 19:42 UTC
After updating to BIT 1.1.14, my scheduled backups are failing. Today I realised it by chance :-(

In syslog I find:

    Mar 25 20:00:02 hppb backintime (mauro/3): INFO: Lock
    Mar 25 20:00:02 hppb backintime (mauro/3): INFO: Inhibit Suspend started. Reason: take snapshot
    Mar 25 20:00:02 hppb backintime (mauro/3): ERROR: Failed to unlock SSH private key /home/mauro/.ssh/id_rsa: Error reading response length from authentication socket.#012Could not add identity: /home/mauro/.ssh/id_rsa
    Mar 25 20:00:02 hppb backintime (mauro/3): ERROR: Non ho potuto sbloccare la chiave privata ssh. Password errata o non disponibile per cron.
    Mar 25 20:00:02 hppb backintime (mauro/3): INFO: Unlock

Running BIT from the main window "Take snapshot" toolbar button works fine.

Using Linux Mint 17.3 KDE (based on Ubuntu Trusty).

**Comment by Germar** [comment] 2017-03-27 19:53
Duplicate of #722. Sorry for the troubles, I'm working on it.

**Closed by Germar** 2017-03-27 19:53 UTC
Labels: duplicate

**Comment by mauromol** [comment] 2017-03-30 10:55
Thank you! I saw #722 but I didn't understand it was the same issue.
Yesterday I say BIT 1.1.18 has been released, I'll try it and let you know.

**Comment by mauromol** [comment] 2017-04-09 10:55
I confirm the scheduled snapshot work perfectly again with BIT 1.1.18, thank you! :+1:
