### ISSUE TITLE
Moved to Ubuntu Mate 20.04, backintime does full backup, few files have changed.

### ISSUE THREAD

**Issue by ekimtrah** [bit-team/backintime#1093] opened 2020-05-27 11:43 UTC
Hi, I have been running Backintime on Ubuntu Mate 18.04 for a couple of years, it was moved from 16.04. I recently installed Ubuntu Mate 20.04 and backintime. I changed the name of the backup folder to match the new host name and changed the host name in the backintime settings to match. This is what I did when moving from 16.04 to 18.04 and it worked well.
This time though, when backintime does a snapshot it is doing a full backup rather than hardlinking the files that have changed. I noticed this because the drive on which the backup is stored filled up (the full size of the backed up data is 123G and there wss 94G free before the backup).

The following is the list of directories in the backup, as shown in the backintime FAQ, only counting the 1st hard link per file
```
$ du -chd0 /media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/*
93G	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20151222-100001-386
55G	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20161221-081307-985
71G	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20171220-100012-226
14G	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20180629-100004-726
7.2G	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20180731-100004-909
1.6G	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20180831-100002-665
379M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20180928-100004-333
244M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20181031-100002-818
319M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20181130-100004-616
538M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20181221-100001-130
1.4G	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20190130-100001-280
757M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20190228-100004-468
7.1G	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20190331-100004-160
667M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20190430-100004-413
730M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20190531-100001-808
875M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20190629-100001-464
1.3G	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20190731-100001-171
330M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20190831-100001-723
261M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20190927-100002-231
71G	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20191030-100002-492
393M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20191130-100001-589
185M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20191221-100001-222
244M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20200131-100001-994
1.5G	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20200228-100004-422
735M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20200331-100001-158
5.7G	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20200426-100002-948
197M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20200430-100001-517
142M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20200503-100002-141
139M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20200507-100002-402
140M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20200508-100002-131
138M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20200509-100001-541
138M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20200510-100002-485
148M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20200511-100004-662
138M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20200512-100002-973
138M	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20200513-100001-989
0	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/last_snapshot
335G	total

```
This is the last folder from du counting hard links multiple times to show the size of a full backup.
```
$ du -chld0 /media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/*
123G	/media/michael/TouroPro/backintime/Dell1NGSWX1UbuMate2004sdx5/michael/1/20200513-100001-989

```
I have looked in the backintime log for the last backup (/home/michael/.local/share/backintime/takesnapshot_.log), which is timestamped at the time when I attempted to backup (on the new 20.04 system), and it looks like all the files are marked as Changed, for example,

```
[I] Take snapshot (rsync: BACKINTIME: cf...p..... media/michael/sda9/Docs/MyDocuments/AsusComputerSpecs.txt)
[C] cf...p..... media/michael/sda9/Docs/MyDocuments/AsusComputerSpecs.txt

```
Looking at the original followed by the last (on the old 18.04 system) backup of this file

```
$ ls --full-time AsusComputerSpecs.txt 
 -rw-rw-rw- 1 michael michael 2453 2006-03-24 20:35:00.000000000 +1100 AsusComputerSpecs.txt 
-r--r--r-- 35 michael michael 2453 2006-03-24 20:35:00.000000000 +1100 AsusComputerSpecs.txt

```
Diff shows no differences between the files.

So I can't work out why backintime is doing a full backup now, perhaps someone can help me find out how to fix it,

Thanks,
Michael

**Comment by colinl** [comment] 2020-05-27 12:49
Possibly a duplicate of #988

**Comment by ekimtrah** [comment] 2020-05-29 00:48
Thanks [colini](https://github.com/colinl), Looks like it was, I first tried [this one from there](https://github.com/bit-team/backintime/issues/988#issuecomment-504665090) which didn't work, then [this one](https://github.com/bit-team/backintime/issues/988#issuecomment-623734008), which seems to work pretty well

**Comment by emtiu** [comment] 2022-09-08 19:20
Closing as duplicate of #988.

**Closed by emtiu** 2022-09-08 19:20 UTC
