### ISSUE TITLE
local encrypted asks password even I want to change other settings (exclude, auto-remove...)

### ISSUE THREAD

**Issue by foretastesynergy** [bit-team/backintime#962] opened 2018-12-09 12:01 UTC
Local encrypted mode asks password even I want to change other settings (exclude, auto-remove...)
I don't want to "cache" or "save" password and I am not going to change password but backintime asks it every time.
BTW, after creating encrypted storage by encfs it is impossible to change password. You can only delete it and create new one. So requirement of setting password after creating it at first time is unnecessary.

**Comment by buhtzz** [comment] 2022-09-26 09:00
@foretastesynergy There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback, Discussion

I have no opinion here.

**Comment by emtiu** [comment] 2022-10-09 10:56
Closing as duplicate of #1118.

**Closed by emtiu** 2022-10-09 10:56 UTC
