### ISSUE TITLE
Its a wrong version - I can't delete it, Sorry

### ISSUE THREAD

**Issue by ftomasch** [bit-team/backintime#1667] opened 2024-03-14 08:49 UTC
Hello!
Is it possible to edit folder names in a directory structure that were automatically created by Back-in-time?
The folders in question are saved on a removable disk drive. You can't access it with either Bach-in-time or Discover. I can't access it with Dolphin. A message appears stating that this data medium can only be read. I tried changing the names in question using F2 in Dolphin and using chown via the console. Unfortunately I had no success. The folders are read-only

I use three internal hard drives for my digital photo. One hard drive has two partitions: one for the system and one for my work files.
I installed Kubuntu 23.10 as the operating system. After my first installation, the three disks were mounted in the "mnt" folder.
Now I set up Kubuntu a second time and made sure that the hard drives were mounted in the “/media/[user]/” folder.
Now my problem:
For the next backup, I would like to adapt the three directories in the backup folder to the new path. So replace “mnt” with “media”.
This means I can continue to use the old backups

I tried to change the three names in Back-in-time, Discover and with the help of the console. - unfortunately in vain. The backup media is “read only”
Is there a way to adapt the folder names to the new environment, or do the backups have to be run completely again?

I installed back-in-time (root) using Discover, Version 1.3.3-4, distributor: Ubuntu
Here are the backintime --diagnostics:

```
{
    "backintime": {
        "name": "Back In Time",
        "version": "1.3.3",
        "latest-config-version": 6,
        "local-config-file": "/home/UsernameReplaced/.config/backintime/config",
        "local-config-file-found": true,
        "global-config-file": "/etc/backintime/config",
        "global-config-file-found": false,
        "started-from": "/usr/share/backintime/common",
        "running-as-root": false,
        "user-callback": "/home/UsernameReplaced/.config/backintime/user-callback",
        "keyring-supported": true
    },
    "host-setup": {
        "platform": "Linux-6.5.0-25-generic-x86_64-with-glibc2.38",
        "system": "Linux #25-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 14:58:39 UTC 2024",
        "os-release": {
            "NAME": "Ubuntu",
            "ID": "ubuntu",
            "PRETTY_NAME": "Ubuntu 23.10",
            "VERSION_ID": "23.10",
            "VERSION": "23.10 (Mantic Minotaur)",
            "VERSION_CODENAME": "mantic",
            "ID_LIKE": "debian",
            "HOME_URL": "https://www.ubuntu.com/",
            "SUPPORT_URL": "https://help.ubuntu.com/",
            "BUG_REPORT_URL": "https://bugs.launchpad.net/ubuntu/",
            "PRIVACY_POLICY_URL": "https://www.ubuntu.com/legal/terms-and-policies/privacy-policy",
            "UBUNTU_CODENAME": "mantic",
            "LOGO": "ubuntu-logo"
        },
        "display-system": "x11",
        "locale": "de_DE, UTF-8",
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin",
        "RSYNC_OLD_ARGS": "(not set)",
        "RSYNC_PROTECT_ARGS": "(not set)"
    },
    "python-setup": {
        "python": "3.11.6 main Oct  8 2023 05:06:43 CPython GCC 13.2.0",
        "python-executable": "/usr/bin/python3",
        "python-executable-symlink": true,
        "python-executable-resolved": "/usr/bin/python3.11",
        "sys.path": [
            "/usr/share/backintime/qt/plugins",
            "/usr/share/backintime/common/plugins",
            "/usr/share/backintime/plugins",
            "/usr/share/backintime/common",
            "/usr/lib/python311.zip",
            "/usr/lib/python3.11",
            "/usr/lib/python3.11/lib-dynload",
            "/usr/local/lib/python3.11/dist-packages",
            "/usr/lib/python3/dist-packages"
        ],
        "qt": "PyQt 5.15.9 / Qt 5.15.10"
    },
    "external-programs": {
        "rsync": {
            "program": "rsync",
            "version": "3.2.7",
            "protocol": "31.0",
            "copyright": "(C) 1996-2022 by Andrew Tridgell, Wayne Davison, and others.",
            "url": "https://rsync.samba.org/",
            "capabilities": {
                "file_bits": 64,
                "inum_bits": 64,
                "timestamp_bits": 64,
                "long_int_bits": 64,
                "socketpairs": true,
                "symlinks": true,
                "symtimes": true,
                "hardlinks": true,
                "hardlink_specials": true,
                "hardlink_symlinks": true,
                "IPv6": true,
                "atimes": true,
                "batchfiles": true,
                "inplace": true,
                "append": true,
                "ACLs": true,
                "xattrs": true,
                "secluded_args": "optional",
                "iconv": true,
                "prealloc": true,
                "stop_at": true,
                "crtimes": false
            },
            "optimizations": {
                "SIMD_roll": true,
                "asm_roll": false,
                "openssl_crypto": true,
                "asm_MD5": false
            },
            "checksum_list": [
                "xxh128",
                "xxh3",
                "xxh64",
                "md5",
                "md4",
                "sha1",
                "none"
            ],
            "compress_list": [
                "zstd",
                "lz4",
                "zlibx",
                "zlib",
                "none"
            ],
            "daemon_auth_list": [
                "sha512",
                "sha256",
                "sha1",
                "md5",
                "md4"
            ],
            "license": "GPLv3",
            "caveat": "rsync comes with ABSOLUTELY NO WARRANTY"
        },
        "ssh": "OpenSSH_9.3p1 Ubuntu-1ubuntu3.2, OpenSSL 3.0.10 1 Aug 2023",
        "sshfs": "3.7.3",
        "encfs": "(no encfs)",
        "shell": "/bin/bash",
        "shell-version": "GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)"
    }
}


```

**Comment by buhtz** [comment] 2024-03-14 09:55
Do I understand it correct that this Issue can be closed because it is a duplicate of #1668 ?
Please feel free to re-open if I am wrong.

**Closed as completed by buhtz** 2024-03-14 09:55 UTC
