### ISSUE TITLE
Backup Stalled at 32%

### ISSUE THREAD

**Issue by acestu** [bit-team/backintime#804] opened 2017-08-21 15:25 UTC
HI,

I have installed Backintime, added my files chosen the drive then clicked on take snapshot, when I returned the process had stopped at 32 %  , I closed the gui because it is all i could do, when i restarted the dialog box came up that said the app was not configured so I am thinking maybe it didn't save ? I will try again this evening.

thanks
Stuart

**Comment by acestu** [comment] 2017-08-21 17:21
Hi,
I just tried it again and sat with it for a while and there were error messages coming up while it was backing up photographs, it was saying in/out error ?

thanks
Stuart

**Comment by Germar** [comment] 2017-08-21 19:16
Please check your drives (both source and backup) for consistency with `sudo fsck /dev/sdXX` where `sdXX` is device name (first column in `df /` and `df /media/USER/DRIVE`)

**Comment by buhtz** [comment] 2017-10-02 13:19
@acestu Can you please give us feedback about your current state of the Issue.

- Where there a problem with the consistency of your drive?
- Can you still reproduce the problem?

**Comment by buhtzz** [comment] 2022-09-25 07:50
@acestu There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

**Comment by emtiu** [comment] 2022-10-22 14:15
Closing, since the reporter isn't responding. From the avaiable information, it was most likely a filesystem/drive failure.

**Closed by emtiu** 2022-10-22 14:15 UTC
