### ISSUE TITLE
Refusing to render service to dead parents.

### ISSUE THREAD

**Issue by tarmtrollet** [bit-team/backintime#593] opened 2016-06-25 12:37 UTC
Hi,

I can no longer start backintime (root) using the .desktop file in gnome
journalctl says "backintime-qt4-root.desktop[9653]: Refusing to render service to dead parents."

i recently upgraded to fedora 24 from fedora 23, im not sure if it started after that but it might.

starting from the terminal using "pkexec backintime-qt4" works fine so im not sure why it wont start from the gui as it uses the same exec.

let me know if you need more info.

great work! regards

**Comment by Germar** [comment] 2016-06-25 12:45
This is a duplicate of #549 and was fixed in current master with #550

Until next release you can manually install current master

**Closed by Germar** 2016-06-25 12:45 UTC
Labels: duplicate

**Comment by tarmtrollet** [comment] 2016-06-25 12:49
awesome, thanks for the fast reply!

**Comment by chrstn-hntschl** [comment] 2017-03-16 14:28
I tried Exec=sh -c "pkexec backintime-qt" and this apparently works as well without a wrapper script
